(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const screens=$$('.screen'), canvas=$('#gameCanvas'), ctx=canvas.getContext('2d'), W=canvas.width,H=canvas.height;
const rewards=['🦖','🚜','🛸','🐳','🏰','🤖','🦊','🚒','🐢','🦁','🚀','🐙','🦋','🚂','🦄','🐼','🛶','🦜','🚁','🐬','🏎️','🦒','🐝','⛵','🐘','🛸','🐧','🚜','🦕','👑'];
const worlds=['🌿','🌊','🪐','🦕','🏗️','🏰','❄️','🏜️','🤖','🌈'];
const types=['match','sort','build','memory','maze','pattern','catch','stack','shadow','shield'];
const skills={match:'Coordination',sort:'Logic',build:'Building',memory:'Memory',maze:'Problem solving',pattern:'Logic',catch:'Coordination',stack:'Building',shadow:'Problem solving',shield:'Coordination'};
const levels=Array.from({length:30},(_,i)=>({n:i+1,type:types[i%10],world:worlds[i%10],difficulty:1+Math.floor(i/10),reward:rewards[i]}));
const defaults={unlocked:1,stars:{},collected:{},profile:null,settings:{sessionLimit:20,reducedMotion:false,calmMode:false,sound:true},skillXP:{Logic:0,Memory:0,Coordination:0,Building:0,'Problem solving':0},playSeconds:0,sessionStart:Date.now()};
function load(){try{const p=JSON.parse(localStorage.getItem('brainquestKidsState')||'{}');return {...defaults,...p,settings:{...defaults.settings,...(p.settings||{})},skillXP:{...defaults.skillXP,...(p.skillXP||{})}}}catch{return structuredClone(defaults)}}
let state=load(), current=1, game=null, tutorialTimer=null, ticker=null;
function save(){localStorage.setItem('brainquestKidsState',JSON.stringify(state));updateTop()}
function show(id){screens.forEach(s=>s.classList.remove('active'));$(id).classList.add('active');if(id==='#mapScreen')renderMap();if(id==='#treasureScreen')renderTreasure();if(id==='#parentScreen')renderParent()}
function totalStars(){return Object.values(state.stars).reduce((a,b)=>a+b,0)}
function updateTop(){$('#starCount').textContent=totalStars();$('#soundBtn').textContent=state.settings.sound?'🔊':'🔇'}
function rnd(a,b){return a+Math.random()*(b-a)}function rndi(a,b){return Math.floor(rnd(a,b+1))}function shuffle(a){for(let i=a.length-1;i>0;i--){const j=rndi(0,i);[a[i],a[j]]=[a[j],a[i]]}return a}
function tone(freq=520,dur=.08){if(!state.settings.sound)return;try{const ac=new(window.AudioContext||window.webkitAudioContext)(),o=ac.createOscillator(),g=ac.createGain();o.connect(g);g.connect(ac.destination);o.frequency.value=freq;g.gain.value=.055;o.start();g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+dur);o.stop(ac.currentTime+dur)}catch{}}
function speak(text){if(!state.settings.sound||!('speechSynthesis'in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.9;u.pitch=1.15;u.volume=.7;speechSynthesis.speak(u)}catch{}}
function feedback(ok=true){const f=$('#feedback');f.textContent=ok?'✨':'💫';f.classList.remove('show');void f.offsetWidth;f.classList.add('show');tone(ok?700:220,ok?.12:.08)}
function clear(bg='#f8fbff'){ctx.fillStyle=bg;ctx.fillRect(0,0,W,H)}
function rr(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=4;ctx.stroke()}}
function emoji(s,x,y,size=64,alpha=1){ctx.globalAlpha=alpha;ctx.font=`${size}px serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(s,x,y);ctx.globalAlpha=1}
function eventPos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture?.(e.pointerId);game?.down?.(eventPos(e))});canvas.addEventListener('pointermove',e=>game?.move?.(eventPos(e)));canvas.addEventListener('pointerup',e=>game?.up?.(eventPos(e)));
function progress(n,total){$('#progressDots').innerHTML=Array.from({length:Math.min(total,6)},(_,i)=>`<span class="${i<n?'on':''}"></span>`).join('')}
function tutorial(type){clearTimeout(tutorialTimer);const t=$('#tutorial'),s=$('#tutorialScene');const scenes={match:'🐶 <span class="hint-target">🐶</span>',sort:'🍎 <span class="hint-target">🧺</span>',build:'🧱 <span class="hint-target">🌉</span>',memory:'🐸 <span class="hint-target">❓</span>',maze:'🔵 <span class="hint-target">⭐</span>',pattern:'🔴 🔵 🔴 <span class="hint-target">🔵</span>',catch:'⭐ <span class="hint-target">👆</span>',stack:'🧱 <span class="hint-target">🏗️</span>',shadow:'🦋 <span class="hint-target">⬛</span>',shield:'🔵 <span class="hint-target">🛡️</span>'};s.innerHTML=scenes[type];t.classList.remove('hidden');tutorialTimer=setTimeout(()=>t.classList.add('hidden'),state.settings.calmMode?3200:2200)}
const speech={match:'Match the same pictures',sort:'Put each one in the matching basket',build:'Build the bridge',memory:'Find the matching pairs',maze:'Guide the blue ball to the star',pattern:'Choose what comes next',catch:'Tap the stars',stack:'Build the tower',shadow:'Match the picture to its shadow',shield:'Tap the shield that matches'};
function renderMap(){const m=$('#levelMap');m.innerHTML='';levels.forEach(l=>{const b=document.createElement('button');b.className='level-node'+(l.n>state.unlocked?' locked':'');b.disabled=l.n>state.unlocked;b.innerHTML=`<span class="emoji">${l.world}</span>${l.n}<span class="mini-stars">${'⭐'.repeat(state.stars[l.n]||0)}</span>`;b.onclick=()=>start(l.n);m.appendChild(b)})}
function renderTreasure(){const g=$('#collectionGrid');g.innerHTML='';levels.forEach(l=>{const d=document.createElement('div');d.className='collectible'+(state.collected[l.n]?'':' missing');d.textContent=l.reward;g.appendChild(d)})}
function start(n){current=n;show('#gameScreen');$('#levelBadge').textContent=n;$('#tapControls').innerHTML='';const l=levels[n-1];tutorial(l.type);setTimeout(()=>speak(speech[l.type]),250);game=createGame(l);game.draw()}
function complete(score=3){state.stars[current]=Math.max(state.stars[current]||0,score);state.unlocked=Math.max(state.unlocked,Math.min(30,current+1));state.collected[current]=true;state.skillXP[skills[levels[current-1].type]]=(state.skillXP[skills[levels[current-1].type]]||0)+score*8;save();feedback(true);setTimeout(()=>{$('#rewardStars').textContent='⭐'.repeat(score);$('#rewardItem').textContent=levels[current-1].reward;show('#rewardScreen');if(current>=5&&!state.profile)setTimeout(()=>show('#parentGate'),900)},500)}
function wrong(){feedback(false);game?.nudge?.()}
function createGame(l){return({match:matchGame,sort:sortGame,build:buildGame,memory:memoryGame,maze:mazeGame,pattern:patternGame,catch:catchGame,stack:stackGame,shadow:shadowGame,shield:shieldGame})[l.type](l.difficulty)}
function matchGame(d){let drag=null,done=0;const pool=shuffle(['🐶','🐱','🦊','🐼','🐸','🦁','🐵','🐰']),count=3+d,syms=pool.slice(0,count),targets=syms.map((s,i)=>({s,x:120+i*(760/(count-1)),y:150,r:58})),pieces=shuffle(syms.map(s=>({s}))).map((p,i)=>({...p,x:120+i*(760/(count-1)),y:500,r:54,ok:false}));function draw(){clear('#effcf4');targets.forEach(t=>{rr(t.x-66,t.y-66,132,132,28,'#dcfce7');emoji(t.s,t.x,t.y,72,.32)});pieces.forEach(p=>{if(!p.ok){rr(p.x-62,p.y-62,124,124,28,'#fff');emoji(p.s,p.x,p.y,68)}});progress(done,count)}function hit(p,o){return Math.hypot(p.x-o.x,p.y-o.y)<75}return{draw,down(p){drag=pieces.find(o=>!o.ok&&hit(p,o))||null},move(p){if(drag){drag.x=p.x;drag.y=p.y;draw()}},up(p){if(!drag)return;const t=targets.find(t=>t.s===drag.s);if(hit(p,t)){drag.ok=true;done++;feedback(true);if(done===count)return complete()}else{wrong();const i=pieces.indexOf(drag);drag.x=120+i*(760/(count-1));drag.y=500}drag=null;draw()}}}
function sortGame(d){const categories=[{icon:'🍎',items:['🍎','🍓','🍒','🍊']},{icon:'🚗',items:['🚗','🚕','🚙','🏎️']},{icon:'🐟',items:['🐟','🐠','🐡','🦈']}];let active=shuffle(categories).slice(0,2),items=shuffle(active.flatMap((c,ci)=>c.items.slice(0,2+d).map(s=>({s,ci}))));items=items.slice(0,4+d).map((o,i)=>({...o,x:120+(i%4)*250,y:430+Math.floor(i/4)*120,ok:false}));let drag=null,done=0;const bins=active.map((c,i)=>({x:i?720:280,y:150,ci:i,icon:c.icon}));function draw(){clear('#fff7ed');bins.forEach(b=>{rr(b.x-120,b.y-85,240,170,30,'#ffedd5','#fb923c');emoji(b.icon,b.x,b.y,78)});items.forEach(o=>{if(!o.ok){rr(o.x-55,o.y-55,110,110,24,'#fff');emoji(o.s,o.x,o.y,60)}});progress(done,items.length)}function hit(p,o){return Math.hypot(p.x-o.x,p.y-o.y)<70}return{draw,down(p){drag=items.find(o=>!o.ok&&hit(p,o))||null},move(p){if(drag){drag.x=p.x;drag.y=p.y;draw()}},up(p){if(!drag)return;const b=bins.find(b=>Math.abs(p.x-b.x)<130&&Math.abs(p.y-b.y)<100);if(b&&b.ci===drag.ci){drag.ok=true;done++;feedback(true);if(done===items.length)return complete()}else{wrong();const i=items.indexOf(drag);drag.x=120+(i%4)*250;drag.y=430+Math.floor(i/4)*120}drag=null;draw()}}}
function buildGame(d){const count=3+d,slots=Array.from({length:count},(_,i)=>({x:190+i*(620/(count-1)),y:315,w:105,h:58,id:i})),blocks=shuffle(Array.from({length:count},(_,i)=>({id:i}))).map((b,i)=>({...b,x:170+i*(660/(count-1)),y:530,ok:false}));let drag=null,done=0;function draw(){clear('#e0f2fe');ctx.fillStyle='#38bdf8';ctx.fillRect(0,385,W,125);ctx.fillStyle='#7c3f18';ctx.fillRect(0,510,W,140);slots.forEach(s=>{ctx.setLineDash([9,8]);rr(s.x-s.w/2,s.y-s.h/2,s.w,s.h,12,null,'#64748b');ctx.setLineDash([])});blocks.forEach(b=>{if(!b.ok){rr(b.x-48,b.y-28,96,56,10,'#f59e0b');ctx.fillStyle='#92400e';ctx.fillRect(b.x-35,b.y-5,70,10)}});progress(done,count)}function hit(p,b){return Math.abs(p.x-b.x)<65&&Math.abs(p.y-b.y)<55}return{draw,down(p){drag=blocks.find(b=>!b.ok&&hit(p,b))||null},move(p){if(drag){drag.x=p.x;drag.y=p.y;draw()}},up(p){if(!drag)return;const s=slots[drag.id];if(Math.hypot(p.x-s.x,p.y-s.y)<85){drag.ok=true;done++;feedback(true);if(done===count)return complete()}else{wrong();const i=blocks.indexOf(drag);drag.x=170+i*(660/(count-1));drag.y=530}drag=null;draw()}}}
function memoryGame(d){const count=2+d,syms=shuffle(['🐶','🐱','🐸','🚗','⭐','🍎','🦋']).slice(0,count),cards=shuffle([...syms,...syms]).map((s,i)=>({s,i,open:false,ok:false}));let first=null,lock=false,done=0;function pos(i){const cols=4,x=175+(i%cols)*215,y=150+Math.floor(i/cols)*190;return{x,y}}function draw(){clear('#fef3c7');cards.forEach(c=>{const p=pos(c.i);rr(p.x-70,p.y-70,140,140,25,c.ok?'#dcfce7':'#fff');emoji(c.open||c.ok?c.s:'❓',p.x,p.y,64)});progress(done,count)}function pick(p){return cards.find(c=>{const q=pos(c.i);return !c.ok&&Math.abs(p.x-q.x)<75&&Math.abs(p.y-q.y)<75})}return{draw,down(p){if(lock)return;const c=pick(p);if(!c||c.open)return;c.open=true;draw();if(!first){first=c;tone(480)}else if(first.s===c.s){first.ok=c.ok=true;first=null;done++;feedback(true);if(done===count)return setTimeout(()=>complete(),350)}else{lock=true;wrong();setTimeout(()=>{first.open=c.open=false;first=null;lock=false;draw()},700)}}}}
function mazeGame(d){const n=6+d,cell=Math.min(76,500/n),ox=(W-cell*n)/2,oy=65;let walls=[],player={x:0,y:0};function generate(){for(let tries=0;tries<100;tries++){walls=[];for(let y=0;y<n;y++)for(let x=0;x<n;x++)if(Math.random()<.2&&!((x===0&&y===0)||(x===n-1&&y===n-1)))walls.push(`${x},${y}`);const q=[[0,0]],seen=new Set(['0,0']);while(q.length){const [x,y]=q.shift();if(x===n-1&&y===n-1)return;[[1,0],[-1,0],[0,1],[0,-1]].forEach(([dx,dy])=>{const nx=x+dx,ny=y+dy,k=`${nx},${ny}`;if(nx>=0&&ny>=0&&nx<n&&ny<n&&!walls.includes(k)&&!seen.has(k)){seen.add(k);q.push([nx,ny])}})}}walls=[]}generate();function draw(){clear('#ecfeff');for(let y=0;y<n;y++)for(let x=0;x<n;x++)rr(ox+x*cell+2,oy+y*cell+2,cell-4,cell-4,10,walls.includes(`${x},${y}`)?'#334155':'#fff');emoji('🔵',ox+(player.x+.5)*cell,oy+(player.y+.5)*cell,cell*.65);emoji('⭐',ox+(n-.5)*cell,oy+(n-.5)*cell,cell*.65)}function move(dx,dy){const nx=player.x+dx,ny=player.y+dy;if(nx<0||ny<0||nx>=n||ny>=n||walls.includes(`${nx},${ny}`)){wrong();return}player={x:nx,y:ny};tone(450,.04);draw();if(nx===n-1&&ny===n-1)complete()}const c=$('#tapControls');[['⬆️',0,-1],['⬅️',-1,0],['⬇️',0,1],['➡️',1,0]].forEach(([e,dx,dy])=>{const b=document.createElement('button');b.textContent=e;b.onclick=()=>move(dx,dy);c.appendChild(b)});return{draw}}
function patternGame(d){const sets=[['🔴','🔵'],['⭐','🌙'],['🔺','🟩','🟡'],['🐟','🐠','🐡']],base=sets[rndi(0,sets.length-1)],len=4+d,seq=Array.from({length:len},(_,i)=>base[i%base.length]),answer=base[len%base.length],choices=shuffle([...new Set([...base,'🟣','🟠','⬡'])]).slice(0,4);if(!choices.includes(answer))choices[0]=answer;function draw(){clear('#f5f3ff');seq.forEach((s,i)=>emoji(s,120+i*(650/(seq.length-1)),250,64));emoji('❓',850,250,70);progress(0,1)}const c=$('#tapControls');choices.forEach(ch=>{const b=document.createElement('button');b.textContent=ch;b.onclick=()=>{if(ch===answer){feedback(true);complete()}else wrong()};c.appendChild(b)});return{draw}}
function catchGame(d){let stars=Array.from({length:5+d*2},()=>({x:rnd(90,910),y:rnd(100,560),r:34,ok:false})),done=0;function draw(){clear('#e0f2fe');stars.forEach(s=>{if(!s.ok)emoji('⭐',s.x,s.y,62)});progress(done,stars.length)}return{draw,down(p){const s=stars.find(s=>!s.ok&&Math.hypot(p.x-s.x,p.y-s.y)<60);if(s){s.ok=true;done++;feedback(true);draw();if(done===stars.length)complete()}else wrong()}}}
function stackGame(d){const count=4+d,blocks=Array.from({length:count},(_,i)=>({x:120+i*(760/(count-1)),y:540,ok:false,id:i})),slots=Array.from({length:count},(_,i)=>({x:500,y:500-i*72,id:i}));let drag=null,done=0;function draw(){clear('#f0fdf4');ctx.fillStyle='#86efac';ctx.fillRect(0,580,W,70);slots.forEach(s=>{ctx.setLineDash([8,7]);rr(s.x-70,s.y-28,140,56,12,null,'#94a3b8');ctx.setLineDash([])});blocks.forEach(b=>{if(!b.ok)rr(b.x-58,b.y-26,116,52,12,['#f59e0b','#60a5fa','#34d399','#f472b6','#a78bfa','#f87171'][b.id%6])});progress(done,count)}return{draw,down(p){drag=blocks.find(b=>!b.ok&&Math.abs(p.x-b.x)<70&&Math.abs(p.y-b.y)<50)||null},move(p){if(drag){drag.x=p.x;drag.y=p.y;draw()}},up(p){if(!drag)return;const s=slots[done];if(Math.hypot(p.x-s.x,p.y-s.y)<90){drag.ok=true;done++;feedback(true);if(done===count)return complete()}else{wrong();const i=blocks.indexOf(drag);drag.x=120+i*(760/(count-1));drag.y=540}drag=null;draw()}}}
function shadowGame(d){const count=3+d,pool=shuffle(['🦋','🐢','🐟','🚗','✈️','🚲']),syms=pool.slice(0,count),targets=syms.map((s,i)=>({s,x:130+i*(740/(count-1)),y:155})),pieces=shuffle(syms.map(s=>({s}))).map((p,i)=>({...p,x:130+i*(740/(count-1)),y:500,ok:false}));let drag=null,done=0;function draw(){clear('#f8fafc');targets.forEach(t=>{rr(t.x-66,t.y-66,132,132,28,'#e2e8f0');emoji(t.s,t.x,t.y,70,.18)});pieces.forEach(p=>{if(!p.ok){rr(p.x-60,p.y-60,120,120,28,'#fff');emoji(p.s,p.x,p.y,68)}});progress(done,count)}return{draw,down(p){drag=pieces.find(o=>!o.ok&&Math.hypot(p.x-o.x,p.y-o.y)<75)||null},move(p){if(drag){drag.x=p.x;drag.y=p.y;draw()}},up(p){if(!drag)return;const t=targets.find(t=>t.s===drag.s);if(Math.hypot(p.x-t.x,p.y-t.y)<82){drag.ok=true;done++;feedback(true);if(done===count)return complete()}else{wrong();const i=pieces.indexOf(drag);drag.x=130+i*(740/(count-1));drag.y=500}drag=null;draw()}}}
function shieldGame(d){const colours=[['🔵','🛡️'],['🔴','🛡️'],['🟢','🛡️'],['🟡','🛡️']],rounds=4+d;let round=0,target='';function next(){target=colours[rndi(0,colours.length-1)][0];draw()}function draw(){clear('#eef2ff');emoji('🤖',500,170,120);emoji(target,500,330,86);emoji('⚡',500,430,68);progress(round,rounds)}const c=$('#tapControls');colours.forEach(([ball])=>{const b=document.createElement('button');b.textContent=ball+'🛡️';b.onclick=()=>{if(ball===target){round++;feedback(true);if(round===rounds)return complete();next()}else wrong()};c.appendChild(b)});next();return{draw}}
function renderParent(){$('#dashLevel').textContent=state.unlocked;$('#dashStars').textContent=totalStars();$('#dashMinutes').textContent=Math.floor(state.playSeconds/60);const g=$('#skillBars');g.innerHTML='';Object.entries(state.skillXP).forEach(([k,v])=>{const pct=Math.min(100,v);g.innerHTML+=`<div class="skill"><span>${k}</span><div class="skill-track"><div class="skill-fill" style="width:${pct}%"></div></div><strong>${pct}</strong></div>`});$('#sessionLimit').value=state.settings.sessionLimit;$('#reducedMotion').checked=state.settings.reducedMotion;$('#calmMode').checked=state.settings.calmMode;$('#profilePrompt').classList.toggle('hidden',!!state.profile)}
function startTicker(){if(ticker)return;ticker=setInterval(()=>{if($('#gameScreen').classList.contains('active')){state.playSeconds++;if(state.settings.sessionLimit&&Date.now()-state.sessionStart>state.settings.sessionLimit*60000)show('#restScreen');if(state.playSeconds%10===0)save()}},1000)}
$('#playBtn').onclick=()=>start(Math.min(state.unlocked,30));$('#mapBtn').onclick=()=>show('#mapScreen');$('#homeBtn').onclick=()=>show('#homeScreen');$('#backToMapBtn').onclick=()=>show('#mapScreen');$('#restartBtn').onclick=()=>start(current);$('#rewardMapBtn').onclick=()=>show('#mapScreen');$('#retryBtn').onclick=()=>start(current);$('#nextBtn').onclick=()=>current<30?start(current+1):show('#treasureScreen');$('#treasureBtn').onclick=()=>show('#treasureScreen');$('#treasureBackBtn').onclick=()=>show('#homeScreen');$('#soundBtn').onclick=()=>{state.settings.sound=!state.settings.sound;save()};$('#parentBtn').onclick=()=>show('#parentGate');$('#gateCancel').onclick=()=>show('#homeScreen');$('#parentClose').onclick=()=>show('#homeScreen');$('#restHomeBtn').onclick=()=>{state.sessionStart=Date.now();show('#homeScreen')};
let holdStart=null,holdLoop=null,left=false,right=false;function gate(){if(left&&right&&!holdStart){holdStart=Date.now();holdLoop=setInterval(()=>{const p=Math.min(1,(Date.now()-holdStart)/3000);$('#holdProgress').style.width=(p*100)+'%';if(p>=1){clearInterval(holdLoop);holdStart=null;show('#parentScreen')}},50)}else if(!(left&&right)){clearInterval(holdLoop);holdStart=null;$('#holdProgress').style.width='0'}}[['#gateLeft','left'],['#gateRight','right']].forEach(([id,side])=>{const b=$(id);b.onpointerdown=()=>{if(side==='left')left=true;else right=true;gate()};['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>{if(side==='left')left=false;else right=false;gate()}))});
$('#profileForm').onsubmit=e=>{e.preventDefault();state.profile={name:$('#childName').value.trim(),age:+$('#childAge').value,email:$('#parentEmail').value.trim()};save();renderParent()};['sessionLimit','reducedMotion','calmMode'].forEach(id=>$('#'+id).addEventListener('change',e=>{state.settings[id]=e.target.type==='checkbox'?e.target.checked:+e.target.value;save()}));$('#resetBtn').onclick=()=>{if(confirm('Reset all BrainQuest Kids progress on this device?')){localStorage.removeItem('brainquestKidsState');location.reload()}};
updateTop();startTicker();
})();
