(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],canvas=$('#gameCanvas'),ctx=canvas.getContext('2d'),W=1000,H=650,screens=$$('.screen');
const TYPES=['match','sort','bridge','memory','maze','pattern','catch','tower','shadow','battle'];
const ICONS=['🦁','🐬','🚀','🦖','🏗️','🏰','🐧','🏜️','🤖','🦸'];
const REW=['🦖','🚜','🛸','🐳','🏰','🤖','🦊','🚒','🐢','🦁','🚀','🐙','🦋','🚂','🦄','🐼','🛶','🦜','🚁','🐬','🏎️','🦒','🐝','⛵','🐘','🛸','🐧','🚜','🦕','👑'];
const skills={match:'Coordination',sort:'Logic',bridge:'Building',memory:'Memory',maze:'Problem solving',pattern:'Logic',catch:'Coordination',tower:'Building',shadow:'Visual thinking',battle:'Problem solving'};
const def={unlocked:1,stars:{},collected:{},attempts:{},profile:null,settings:{sessionLimit:20,reducedMotion:false,calmMode:false,siblingMode:false,sound:true},skillXP:{Logic:0,Memory:0,Coordination:0,Building:0,'Problem solving':0,'Visual thinking':0},playSeconds:0,sessionStart:Date.now()};
let state=load(),current=1,game=null,drag=null,particles=[],raf=0;
function load(){try{let x=JSON.parse(localStorage.getItem('brainquestKidsState')||'{}');return{...def,...x,settings:{...def.settings,...x.settings},skillXP:{...def.skillXP,...x.skillXP}}}catch{return structuredClone(def)}}
function save(){localStorage.setItem('brainquestKidsState',JSON.stringify(state));top()}
function top(){$('#starCount').textContent=Object.values(state.stars).reduce((a,b)=>a+b,0);$('#soundBtn').textContent=state.settings.sound?'🔊':'🔇'}
function show(id){screens.forEach(x=>x.classList.remove('active'));$(id).classList.add('active');if(id==='#mapScreen')map();if(id==='#treasureScreen')treasure();if(id==='#parentScreen')parent()}
const rnd=(a,b)=>a+Math.random()*(b-a),ri=(a,b)=>Math.floor(rnd(a,b+1)),shuffle=a=>[...a].sort(()=>Math.random()-.5);
function tone(f=500,d=.08){if(!state.settings.sound)return;try{let a=new(window.AudioContext||webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=f;g.gain.value=.07;o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.stop(a.currentTime+d)}catch{}}
function speak(t){if(!state.settings.sound||!('speechSynthesis'in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.rate=.9;u.pitch=1.18;speechSynthesis.speak(u)}
function rr(x,y,w,h,r,c){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=c;ctx.fill()}
function bg(a='#7de3ff',b='#d9a7ff'){let g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,a);g.addColorStop(1,b);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.globalAlpha=.22;for(let i=0;i<18;i++){ctx.fillStyle=i%2?'#fff':'#ffe45e';ctx.beginPath();ctx.arc((i*173)%W,(i*97)%H,10+(i%4)*5,0,7);ctx.fill()}ctx.globalAlpha=1}
function confetti(x=W/2,y=H/2){for(let i=0;i<34;i++)particles.push({x,y,vx:rnd(-7,7),vy:rnd(-10,-2),life:50,e:['⭐','✨','💥','🎉'][i%4]});anim()}
function anim(){cancelAnimationFrame(raf);let tick=()=>{if(game)game.draw();particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.25;p.life--;ctx.font='24px serif';ctx.fillText(p.e,p.x,p.y)});particles=particles.filter(p=>p.life>0);if(particles.length)raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick)}
function demo(icon,text){$('#demoStrip').innerHTML=`<span>${icon}</span><span>✨</span>`;setTimeout(()=>speak(text),250)}
function map(){let m=$('#levelMap');m.innerHTML='';for(let n=1;n<=30;n++){let b=document.createElement('button'),locked=n>state.unlocked;b.className='level-node'+(locked?' locked':'');b.disabled=locked;b.innerHTML=`<span class="emoji">${ICONS[(n-1)%10]}</span>${n}<span class="mini-stars">${'⭐'.repeat(state.stars[n]||0)}</span>`;b.onclick=()=>start(n);m.appendChild(b)}}
function treasure(){let g=$('#collectionGrid');g.innerHTML='';REW.forEach((e,i)=>{let d=document.createElement('div');d.className='collectible'+(state.collected[i+1]?'':' missing');d.textContent=e;g.appendChild(d)})}
function lives(n){$('#lifeDots').textContent='●'.repeat(n)+'○'.repeat(Math.max(0,3-n))}
function start(n){current=n;show('#gameScreen');$('#levelBadge').textContent=n;$('#tapControls').innerHTML='';state.attempts[n]=(state.attempts[n]||0)+1;save();game=make(TYPES[(n-1)%10],1+Math.floor((n-1)/10));lives(3);game.reset();game.draw()}
function make(t,d){return({match:match,sort:sort,bridge:bridge,memory:memory,maze:maze,pattern:pattern,catch:catcher,tower:tower,shadow:shadow,battle:battle})[t](d)}
function win(){confetti();tone(780,.22);setTimeout(()=>{let s=game.lives===3?3:game.lives===2?2:1,old=state.stars[current]||0;state.stars[current]=Math.max(old,s);state.unlocked=Math.max(state.unlocked,Math.min(30,current+1));state.collected[current]=true;let sk=skills[TYPES[(current-1)%10]];state.skillXP[sk]=(state.skillXP[sk]||0)+s*8;save();$('#rewardStars').textContent='⭐'.repeat(s);$('#rewardItem').textContent=REW[current-1];show('#rewardScreen');speak('Amazing! You did it!')},650)}
function wrong(){game.lives--;lives(game.lives);tone(170,.12);speak('Try again');if(game.lives<=0){game.lives=3;lives(3);game.reset()}game.draw()}
function pos(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
canvas.onpointerdown=e=>{drag=pos(e);game?.down?.(drag)};canvas.onpointermove=e=>{if(e.buttons)game?.move?.(pos(e))};canvas.onpointerup=e=>{game?.up?.(pos(e));drag=null};
function match(d){let G={lives:3,items:[],targets:[],reset(){demo('🐶 ↔️ 🐶','Drag each picture to its matching picture.');let a=shuffle(['🐶','🦊','🐸','🦁','🐼','🐵']).slice(0,3+d);this.targets=a.map((e,i)=>({e,x:130+i*740/(a.length-1),y:155}));this.items=shuffle(a).map((e,i)=>({e,x:130+i*740/(a.length-1),y:495,homeX:0,homeY:0}));this.sel=null},draw(){bg('#70e7ff','#ffb0dc');ctx.textAlign='center';ctx.textBaseline='middle';this.targets.forEach(t=>{rr(t.x-67,t.y-67,134,134,30,'rgba(255,255,255,.48)');ctx.font='76px serif';ctx.globalAlpha=.38;ctx.fillText(t.e,t.x,t.y);ctx.globalAlpha=1});this.items.forEach(o=>{if(o.ok)return;rr(o.x-64,o.y-64,128,128,30,'#fff');ctx.font='74px serif';ctx.fillText(o.e,o.x,o.y)});ctx.font='36px serif';ctx.fillText('🌈',500,325)},down(p){this.sel=this.items.find(o=>!o.ok&&Math.hypot(p.x-o.x,p.y-o.y)<80)},move(p){if(this.sel){this.sel.x=p.x;this.sel.y=p.y;this.draw()}},up(p){if(!this.sel)return;let t=this.targets.find(t=>t.e===this.sel.e);if(Math.hypot(p.x-t.x,p.y-t.y)<95){this.sel.ok=1;tone(620);confetti(t.x,t.y);if(this.items.every(x=>x.ok))win()}else{this.reset();wrong()}this.sel=null;this.draw()}};return G}
function sort(d){let G={lives:3,reset(){demo('🍎 ➡️ 🧺','Put each thing in the right home.');let food=['🍎','🍌','🍓'],animals=['🐶','🐱','🐰'];this.bins=[{e:'🧺',x:260,y:160,type:0},{e:'🏡',x:740,y:160,type:1}];this.items=shuffle([...food.slice(0,2+d),...animals.slice(0,2+d)]).map((e,i)=>({e,type:food.includes(e)?0:1,x:120+(i%5)*190,y:470+Math.floor(i/5)*105}));},draw(){bg('#ffe56d','#7ee8b6');ctx.textAlign='center';this.bins.forEach(b=>{rr(b.x-115,b.y-90,230,180,38,'rgba(255,255,255,.75)');ctx.font='100px serif';ctx.fillText(b.e,b.x,b.y+20)});this.items.forEach(o=>{if(!o.ok){ctx.font='68px serif';ctx.fillText(o.e,o.x,o.y)}})},down(p){this.sel=this.items.find(o=>!o.ok&&Math.hypot(p.x-o.x,p.y-o.y)<65)},move(p){if(this.sel){this.sel.x=p.x;this.sel.y=p.y;this.draw()}},up(p){if(!this.sel)return;let b=this.bins[this.sel.type];if(Math.hypot(p.x-b.x,p.y-b.y)<140){this.sel.ok=1;tone(600);confetti(b.x,b.y);if(this.items.every(x=>x.ok))win()}else wrong();this.sel=null;this.draw()}};return G}
function bridge(d){let G={lives:3,reset(){demo('🧱 🌉 🚗','Build the bridge so the car can cross.');this.n=3+d;this.slots=Array.from({length:this.n},(_,i)=>({x:250+i*500/(this.n-1),y:330,id:i}));this.blocks=shuffle(this.slots.map((_,i)=>i)).map((id,i)=>({id,x:160+i*680/(this.n-1),y:535}))},draw(){bg('#74dfff','#6ee7a0');ctx.fillStyle='#37b7ed';ctx.fillRect(0,365,W,150);ctx.font='60px serif';ctx.fillText('🚗',70,310);ctx.fillText('🏁',920,300);this.slots.forEach(s=>{ctx.strokeStyle='#fff';ctx.lineWidth=6;ctx.setLineDash([12,8]);ctx.strokeRect(s.x-55,s.y-30,110,60)});ctx.setLineDash([]);this.blocks.forEach(o=>{if(!o.ok){rr(o.x-52,o.y-28,104,56,10,['#ff7b7b','#ffd34e','#8b72ff','#55d6be'][o.id%4]);ctx.fillStyle='#fff';ctx.font='25px sans-serif';ctx.fillText(o.id+1,o.x,o.y+8)}})},down(p){this.sel=this.blocks.find(o=>!o.ok&&Math.hypot(p.x-o.x,p.y-o.y)<65)},move(p){if(this.sel){this.sel.x=p.x;this.sel.y=p.y;this.draw()}},up(p){if(!this.sel)return;let s=this.slots[this.sel.id];if(Math.hypot(p.x-s.x,p.y-s.y)<80){this.sel.ok=1;confetti(s.x,s.y);if(this.blocks.every(x=>x.ok))win()}else wrong();this.sel=null;this.draw()}};return G}
function memory(d){let G={lives:3,reset(){demo('🧠 🃏','Find all the matching pairs.');let n=3+d,a=shuffle(['🦄','🚀','🍉','⚽','🐙','🎸']).slice(0,n);this.cards=shuffle([...a,...a]).map((e,i)=>({e,x:170+(i%4)*220,y:145+Math.floor(i/4)*190,open:false,done:false}));this.first=null;this.lock=false},draw(){bg('#b49cff','#ff9bc8');ctx.textAlign='center';this.cards.forEach(c=>{rr(c.x-78,c.y-70,156,140,24,c.open||c.done?'#fff':'#6650d8');ctx.font='65px serif';ctx.fillText(c.open||c.done?c.e:'⭐',c.x,c.y)})},down(p){if(this.lock)return;let c=this.cards.find(c=>!c.done&&!c.open&&Math.hypot(p.x-c.x,p.y-c.y)<90);if(!c)return;c.open=true;if(!this.first){this.first=c;this.draw();return}if(this.first.e===c.e){c.done=this.first.done=true;this.first=null;confetti(c.x,c.y);if(this.cards.every(x=>x.done))win()}else{this.lock=true;this.draw();setTimeout(()=>{c.open=this.first.open=false;this.first=null;this.lock=false;wrong()},650)}this.draw()}};return G}
function maze(d){let G={lives:3,reset(){demo('🦸 ➡️ 💎','Guide the hero to the power crystal.');this.n=6+d;this.p={x:0,y:0};this.goal={x:this.n-1,y:this.n-1};this.walls=new Set();for(let y=0;y<this.n;y++)for(let x=0;x<this.n;x++)if(Math.random()<.12&&x!==y&&!(x===0&&y===0))this.walls.add(`${x},${y}`);let c=$('#tapControls');c.innerHTML='';[['⬆️',0,-1],['⬅️',-1,0],['⬇️',0,1],['➡️',1,0]].forEach(q=>{let b=document.createElement('button');b.textContent=q[0];b.onclick=()=>this.go(q[1],q[2]);c.appendChild(b)})},go(dx,dy){let x=this.p.x+dx,y=this.p.y+dy;if(x<0||y<0||x>=this.n||y>=this.n||this.walls.has(`${x},${y}`)){wrong();return}this.p={x,y};tone(450,.04);this.draw();if(x===this.goal.x&&y===this.goal.y)win()},draw(){bg('#59d8ff','#94f0bc');let z=500/this.n,ox=250,oy=55;for(let y=0;y<this.n;y++)for(let x=0;x<this.n;x++){rr(ox+x*z+2,oy+y*z+2,z-4,z-4,8,this.walls.has(`${x},${y}`)?'#5b4b8a':'rgba(255,255,255,.75)')}ctx.font=`${z*.65}px serif`;ctx.fillText('🦸',ox+(this.p.x+.5)*z,oy+(this.p.y+.5)*z);ctx.fillText('💎',ox+(this.goal.x+.5)*z,oy+(this.goal.y+.5)*z)}};return G}
function pattern(d){let G={lives:3,reset(){demo('🧩 ❓','What comes next in the pattern?');let sets=[['🔴','🔵'],['🌞','🌙'],['🐸','🦊','🐼'],['⭐','💎','⭐','❤️']];this.base=sets[ri(0,sets.length-1)];this.len=4+d;this.seq=Array.from({length:this.len},(_,i)=>this.base[i%this.base.length]);this.ans=this.base[this.len%this.base.length];let opts=shuffle([...new Set([...this.base,'🟢','🟣','🔶'])]).slice(0,4);if(!opts.includes(this.ans))opts[0]=this.ans;let c=$('#tapControls');c.innerHTML='';shuffle(opts).forEach(e=>{let b=document.createElement('button');b.textContent=e;b.onclick=()=>{if(e===this.ans)win();else wrong()};c.appendChild(b)})},draw(){bg('#ffcf69','#ff91c8');ctx.textAlign='center';ctx.font='82px serif';this.seq.forEach((e,i)=>ctx.fillText(e,140+i*(720/(this.seq.length-1)),290));rr(435,420,130,120,28,'#fff');ctx.font='75px serif';ctx.fillText('❓',500,485)}};return G}
function catcher(d){let G={lives:3,reset(){demo('⭐ 🧺','Catch the stars. Avoid the storm clouds.');this.player=500;this.objects=[];this.score=0;this.need=5+d*2;this.last=0;this.running=true;this.loop()},loop(t=0){if(!this.running)return;if(t-this.last>600){this.objects.push({x:rnd(70,930),y:-30,bad:Math.random()<.25});this.last=t}this.objects.forEach(o=>o.y+=4+d);this.objects.forEach(o=>{if(o.y>520&&o.y<600&&Math.abs(o.x-this.player)<90&&!o.hit){o.hit=true;if(o.bad){wrong()}else{this.score++;tone(700);confetti(o.x,o.y);if(this.score>=this.need){this.running=false;win()}}}});this.objects=this.objects.filter(o=>o.y<650&&!o.hit);this.draw();if(this.running)requestAnimationFrame(x=>this.loop(x))},draw(){bg('#3d7bff','#b55cff');ctx.font='38px serif';ctx.fillText(`⭐ ${this.score}/${this.need}`,80,55);this.objects.forEach(o=>{ctx.font='55px serif';ctx.fillText(o.bad?'🌩️':'⭐',o.x,o.y)});ctx.font='85px serif';ctx.fillText('🧺',this.player,575)},down(p){this.player=p.x},move(p){this.player=p.x}};return G}
function tower(d){let G={lives:3,reset(){demo('🏗️ 🏰','Stack the blocks from biggest to smallest.');this.n=4+d;this.slots=Array.from({length:this.n},(_,i)=>({x:500,y:500-i*75,id:i}));this.blocks=shuffle(Array.from({length:this.n},(_,i)=>i)).map((id,i)=>({id,x:130+i*740/(this.n-1),y:585,w:145-id*13}))},draw(){bg('#ffdc6c','#75dcff');ctx.fillStyle='#65c56e';ctx.fillRect(0,610,W,40);this.slots.forEach(s=>{ctx.strokeStyle='rgba(255,255,255,.7)';ctx.lineWidth=4;ctx.strokeRect(s.x-80,s.y-28,160,56)});this.blocks.forEach(o=>{if(!o.ok){rr(o.x-o.w/2,o.y-28,o.w,56,12,['#ff627d','#6e5cff','#32cbd1','#ffae32'][o.id%4])}})},down(p){this.sel=this.blocks.find(o=>!o.ok&&Math.abs(p.x-o.x)<90&&Math.abs(p.y-o.y)<55)},move(p){if(this.sel){this.sel.x=p.x;this.sel.y=p.y;this.draw()}},up(p){if(!this.sel)return;let s=this.slots[this.sel.id];if(Math.hypot(p.x-s.x,p.y-s.y)<85){this.sel.ok=1;confetti(s.x,s.y);if(this.blocks.every(x=>x.ok))win()}else wrong();this.sel=null;this.draw()}};return G}
function shadow(d){let G={lives:3,reset(){demo('🔎 🐾','Find the picture that matches the shadow.');this.opts=shuffle(['🦖','🚀','🐘','🚲','🐠','🦋']).slice(0,3+d);this.ans=this.opts[ri(0,this.opts.length-1)]},draw(){bg('#65e0c0','#8aa5ff');ctx.textAlign='center';rr(370,80,260,210,38,'#fff');ctx.globalAlpha=.18;ctx.font='130px serif';ctx.fillText(this.ans,500,190);ctx.globalAlpha=1;this.opts.forEach((e,i)=>{let x=120+i*760/(this.opts.length-1);rr(x-65,430,130,130,28,'#fff');ctx.font='75px serif';ctx.fillText(e,x,500)})},down(p){let i=Math.round((p.x-120)/(760/(this.opts.length-1)));i=Math.max(0,Math.min(this.opts.length-1,i));if(p.y>400){if(this.opts[i]===this.ans)win();else wrong()}}};return G}
function battle(d){let G={lives:3,reset(){demo('🦸 🛡️ 🤖','Hero mission! Choose the power that beats the robot challenge.');this.round=0;this.need=3+d;this.hero=0;this.newRound()},newRound(){let challenges=[{bad:'🔥',good:'💧'},{bad:'🧊',good:'🔥'},{bad:'⚡',good:'🛡️'},{bad:'🪨',good:'💥'}];this.q=challenges[ri(0,challenges.length-1)];this.opts=shuffle([this.q.good,...shuffle(['💧','🔥','🛡️','💥','🌪️']).filter(x=>x!==this.q.good).slice(0,2)]);let c=$('#tapControls');c.innerHTML='';this.opts.forEach(e=>{let b=document.createElement('button');b.textContent=e;b.onclick=()=>this.choose(e);c.appendChild(b)})},choose(e){if(e===this.q.good){this.round++;this.hero+=90;tone(150+d*40,.05);confetti(700,310);if(this.round>=this.need)return win();this.newRound();this.draw()}else{wrong();this.newRound();this.draw()}},draw(){bg('#3c3a83','#e85e9c');ctx.fillStyle='rgba(255,255,255,.18)';for(let x=0;x<W;x+=90)ctx.fillRect(x,500-(x%180?40:0),70,150);ctx.font='125px serif';ctx.fillText('🦸',220,390);ctx.fillText('🤖',780,390);ctx.font='85px serif';ctx.fillText(this.q.bad,650,205);ctx.font='30px sans-serif';ctx.fillStyle='#fff';ctx.fillText(`⭐ ${this.round}/${this.need}`,500,65);ctx.fillStyle='#50e38e';ctx.fillRect(120,500,Math.min(360,this.hero),18)}};return G}
$('#playBtn').onclick=()=>start(Math.min(state.unlocked,30));$('#mapBtn').onclick=()=>show('#mapScreen');$('#homeBtn').onclick=()=>show('#homeScreen');$('#backToMapBtn').onclick=()=>show('#mapScreen');$('#restartBtn').onclick=()=>start(current);$('#rewardMapBtn').onclick=()=>show('#mapScreen');$('#retryBtn').onclick=()=>start(current);$('#nextBtn').onclick=()=>current<30?start(current+1):show('#mapScreen');$('#treasureBtn').onclick=()=>show('#treasureScreen');$('#treasureBackBtn').onclick=()=>show('#homeScreen');$('#soundBtn').onclick=()=>{state.settings.sound=!state.settings.sound;save()};
let hold=0,timer;function gate(){show('#parentGate')}$('#parentBtn').onclick=gate;function hs(){hold++;$('.holdbar span').style.width=(hold/30*100)+'%';if(hold>=30){clearInterval(timer);hold=0;show('#parentScreen')}}function begin(){if(!timer)timer=setInterval(hs,100)}function end(){clearInterval(timer);timer=null;hold=0;$('.holdbar span').style.width='0'};['#gateLeft','#gateRight'].forEach(s=>{$(s).onpointerdown=begin;$(s).onpointerup=end});$('#gateCancel').onclick=()=>show('#homeScreen');$('#parentClose').onclick=()=>show('#homeScreen');
function parent(){$('#dashLevel').textContent=state.unlocked;$('#dashStars').textContent=Object.values(state.stars).reduce((a,b)=>a+b,0);$('#dashMinutes').textContent=Math.floor(state.playSeconds/60);$('#profilePrompt').classList.toggle('hidden',!!state.profile);let box=$('#skillBars');box.innerHTML='';Object.entries(state.skillXP).forEach(([k,v])=>box.innerHTML+=`<div class="skill"><span>${k}</span><div class="skill-track"><div class="skill-fill" style="width:${Math.min(100,v)}%"></div></div><b>${v}</b></div>`);$('#sessionLimit').value=state.settings.sessionLimit;$('#reducedMotion').checked=state.settings.reducedMotion;$('#calmMode').checked=state.settings.calmMode;$('#siblingMode').checked=state.settings.siblingMode}
$('#profileForm').onsubmit=e=>{e.preventDefault();state.profile={name:$('#childName').value,age:+$('#childAge').value,email:$('#parentEmail').value};save();parent()};['sessionLimit','reducedMotion','calmMode','siblingMode'].forEach(id=>$('#'+id).onchange=e=>{state.settings[id]=e.target.type==='checkbox'?e.target.checked:+e.target.value;save()});$('#resetBtn').onclick=()=>{if(confirm('Reset all game progress on this device?')){localStorage.removeItem('brainquestKidsState');location.reload()}};$('#exportBtn').onclick=()=>alert(JSON.stringify({...state,profile:state.profile?{...state.profile,email:'hidden'}:null},null,2));$('#restHomeBtn').onclick=()=>show('#homeScreen');
setInterval(()=>{state.playSeconds++;if(state.playSeconds%30===0)save()},1000);top();show('#homeScreen');
})();