(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],canvas=$('#gameCanvas'),ctx=canvas.getContext('2d'),W=1000,H=650,screens=$$('.screen');
const TYPES=['match','sort','bridge','memory','maze','pattern','catch','tower','shadow','battle','scavenge','sequence'];
const ICONS=['🐶','🧺','🌉','🧠','🦸','🧩','⭐','🏗️','🔎','⚔️','🗺️','🎵'];
const REW=['🦄','🚀','🏰','🤖','🐬','🦖','🛸','🦊','🐼','👑','💎','🏆'];
const skillFor={match:'Coordination',sort:'Logic',bridge:'Building',memory:'Memory',maze:'Problem solving',pattern:'Logic',catch:'Coordination',tower:'Building',shadow:'Visual thinking',battle:'Problem solving',scavenge:'Observation',sequence:'Memory'};
const def={unlocked:1,stars:{},collected:{},attempts:{},profile:null,settings:{sessionLimit:20,reducedMotion:false,calmMode:false,sound:true},skillXP:{Logic:0,Memory:0,Coordination:0,Building:0,'Problem solving':0,'Visual thinking':0,Observation:0},playSeconds:0,sessionStart:Date.now()};
let state=load(),current=1,game=null,particles=[],raf=0,lastType='';
const ASSET_URLS={map:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Treasure%20map.svg',castle:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Castle%20%28color%29.svg',island:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Treasure%20island.svg'};
const images={};Object.entries(ASSET_URLS).forEach(([k,u])=>{let im=new Image();im.crossOrigin='anonymous';im.onload=()=>game?.draw?.();im.onerror=()=>{};im.src=u;images[k]=im});
let music=null;function ensureMusic(){if(!music){music=new Audio('https://opengameart.org/sites/default/files/flowerbed_fields.ogg');music.loop=true;music.volume=.14;music.preload='auto'}if(state.settings.sound&&music.paused)music.play().catch(()=>{})}
function stopMusic(){try{music?.pause()}catch{}}
function load(){try{let x=JSON.parse(localStorage.getItem('brainquestKidsState')||'{}');return{...def,...x,settings:{...def.settings,...x.settings},skillXP:{...def.skillXP,...x.skillXP}}}catch{return structuredClone(def)}}
function save(){localStorage.setItem('brainquestKidsState',JSON.stringify(state));top()}
function top(){$('#starCount').textContent=Object.values(state.stars).reduce((a,b)=>a+b,0);$('#soundBtn').textContent=state.settings.sound?'🔊':'🔇'}
function show(id){screens.forEach(x=>x.classList.remove('active'));$(id).classList.add('active');if(id==='#mapScreen')map();if(id==='#treasureScreen')treasure();if(id==='#parentScreen')parent()}
const rnd=(a,b)=>a+Math.random()*(b-a),ri=(a,b)=>Math.floor(rnd(a,b+1)),shuffle=a=>[...a].sort(()=>Math.random()-.5),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function tone(f=500,d=.08){if(!state.settings.sound)return;try{let a=new(window.AudioContext||webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.type='triangle';o.frequency.value=f;g.gain.value=.06;o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.stop(a.currentTime+d)}catch{}}
function speak(t){if(!state.settings.sound||!('speechSynthesis'in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.rate=.93;u.pitch=1.16;speechSynthesis.speak(u)}
function rr(x,y,w,h,r,c){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=c;ctx.fill()}
function bg(a='#74ddff',b='#c594ff'){let g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,a);g.addColorStop(1,b);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.globalAlpha=.18;for(let i=0;i<22;i++){ctx.fillStyle=i%3?'#fff':'#ffe968';ctx.beginPath();ctx.arc((i*173)%W,(i*97)%H,8+(i%4)*5,0,7);ctx.fill()}ctx.globalAlpha=1}
function sceneGround(){ctx.fillStyle='#6edb7f';ctx.fillRect(0,535,W,115);ctx.fillStyle='#4bb965';ctx.fillRect(0,535,W,18);ctx.font='55px serif';ctx.fillText('🌳',90,520);ctx.fillText('🌼',180,555);ctx.fillText('🌳',895,520);ctx.fillText('🌈',510,95)}
function confetti(x=W/2,y=H/2){for(let i=0;i<28;i++)particles.push({x,y,vx:rnd(-7,7),vy:rnd(-10,-2),life:42,e:['⭐','✨','🎉','💫'][i%4]});animate()}
function animate(){cancelAnimationFrame(raf);const tick=()=>{try{game?.draw?.();particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.28;p.life--;ctx.font='24px serif';ctx.fillText(p.e,p.x,p.y)});particles=particles.filter(p=>p.life>0);if(particles.length||game?.continuous)raf=requestAnimationFrame(tick)}catch(e){renderError(e)}};raf=requestAnimationFrame(tick)}
function renderError(){ctx.clearRect(0,0,W,H);bg('#80ddff','#ffb1d5');ctx.textAlign='center';ctx.font='96px serif';ctx.fillText('🛠️',500,250);ctx.font='52px serif';ctx.fillText('🔄',500,390);}
function tutorial(icon,text){let t=$('#tutorial');if(t){$('#tutorialScene').textContent=icon;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),1500)}setTimeout(()=>speak(text),200)}
function map(){let m=$('#levelMap');m.innerHTML='';for(let n=1;n<=60;n++){let type=TYPES[(n-1)%TYPES.length],b=document.createElement('button'),locked=n>state.unlocked;b.className='level-node'+(locked?' locked':'');b.disabled=locked;b.innerHTML=`<span class="emoji">${ICONS[TYPES.indexOf(type)]}</span>${n}<span class="mini-stars">${'⭐'.repeat(state.stars[n]||0)}</span>`;b.onclick=()=>start(n);m.appendChild(b)}}
function treasure(){let g=$('#collectionGrid');g.innerHTML='';for(let i=1;i<=60;i++){let d=document.createElement('div');d.className='collectible'+(state.collected[i]?'':' missing');d.textContent=REW[(i-1)%REW.length];g.appendChild(d)}}
function lives(n){$('#lifeDots').textContent='●'.repeat(n)+'○'.repeat(Math.max(0,3-n))}
function start(n){current=n;ensureMusic();show('#gameScreen');$('#levelBadge').textContent=n;$('#tapControls').innerHTML='';state.attempts[n]=(state.attempts[n]||0)+1;save();let type=TYPES[(n-1)%TYPES.length],d=1+Math.floor((n-1)/12);lastType=type;try{game=make(type,d);game.lives=3;lives(3);game.reset();game.draw();if(game.continuous)animate()}catch(e){renderError(e)}}
function make(t,d){return({match,sort,bridge,memory,maze,pattern,catch:catcher,tower,shadow,battle,scavenge,sequence})[t](d)}
function win(){if(!game||game.finished)return;game.finished=true;confetti();tone(820,.25);setTimeout(()=>{let s=game.lives===3?3:game.lives===2?2:1,old=state.stars[current]||0;state.stars[current]=Math.max(old,s);state.unlocked=Math.max(state.unlocked,Math.min(60,current+1));state.collected[current]=true;let sk=skillFor[lastType];state.skillXP[sk]=(state.skillXP[sk]||0)+s*8;save();$('#rewardStars').textContent='⭐'.repeat(s);$('#rewardItem').textContent=REW[(current-1)%REW.length];show('#rewardScreen');speak('Amazing! Mission complete!')},500)}
function wrong(){if(!game||game.finished)return;game.lives=Math.max(0,(game.lives||3)-1);lives(game.lives);tone(180,.12);if(game.lives<=0){game.lives=3;lives(3);setTimeout(()=>game.reset(),250)}else speak('Try again')}
function pos(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
canvas.onpointerdown=e=>{let p=pos(e);game?.down?.(p);canvas.setPointerCapture?.(e.pointerId)};canvas.onpointermove=e=>{if(e.buttons)game?.move?.(pos(e))};canvas.onpointerup=e=>game?.up?.(pos(e));
function match(d){let G={lives:3,reset(){tutorial('🐶 ➜ 🐶','Drag each picture to its matching picture.');let a=shuffle(['🐶','🦊','🐸','🦁','🐼','🐵','🦄']).slice(0,Math.min(6,3+d));this.targets=a.map((e,i)=>({e,x:120+i*760/(a.length-1),y:155}));this.items=shuffle(a).map((e,i)=>({e,x:120+i*760/(a.length-1),y:485}));this.sel=null},draw(){bg('#66e4ff','#ff9fd1');sceneGround();ctx.textAlign='center';ctx.textBaseline='middle';this.targets.forEach(t=>{rr(t.x-66,t.y-66,132,132,28,'rgba(255,255,255,.6)');ctx.globalAlpha=.28;ctx.font='78px serif';ctx.fillText(t.e,t.x,t.y);ctx.globalAlpha=1});this.items.forEach(o=>{if(!o.ok){rr(o.x-62,o.y-62,124,124,28,'#fff');ctx.font='72px serif';ctx.fillText(o.e,o.x,o.y)}})},down(p){this.sel=this.items.find(o=>!o.ok&&dist(p,o)<80)},move(p){if(this.sel){this.sel.x=p.x;this.sel.y=p.y;this.draw()}},up(p){if(!this.sel)return;let t=this.targets.find(x=>x.e===this.sel.e);if(dist(p,t)<95){this.sel.ok=1;confetti(t.x,t.y);tone(640);if(this.items.every(x=>x.ok))win()}else wrong();this.sel=null;this.draw()}};return G}
function sort(d){let G={lives:3,reset(){tutorial('🍎 ➜ 🧺','Put each thing in the right home.');let food=['🍎','🍌','🍓','🥕'],animals=['🐶','🐱','🐰','🦊'];this.bins=[{e:'🧺',x:260,y:170,type:0},{e:'🏡',x:740,y:170,type:1}];let n=Math.min(4,2+d);this.items=shuffle([...food.slice(0,n),...animals.slice(0,n)]).map((e,i)=>({e,type:food.includes(e)?0:1,x:120+(i%5)*190,y:455+Math.floor(i/5)*95}))},draw(){bg('#ffe26b','#70e7b3');sceneGround();ctx.textAlign='center';this.bins.forEach(b=>{rr(b.x-120,b.y-90,240,180,36,'rgba(255,255,255,.84)');ctx.font='100px serif';ctx.fillText(b.e,b.x,b.y+25)});this.items.forEach(o=>{if(!o.ok){ctx.font='68px serif';ctx.fillText(o.e,o.x,o.y)}})},down(p){this.sel=this.items.find(o=>!o.ok&&dist(p,o)<70)},move(p){if(this.sel){this.sel.x=p.x;this.sel.y=p.y;this.draw()}},up(p){if(!this.sel)return;let b=this.bins[this.sel.type];if(dist(p,b)<145){this.sel.ok=1;confetti(b.x,b.y);if(this.items.every(x=>x.ok))win()}else wrong();this.sel=null;this.draw()}};return G}
function bridge(d){let G={lives:3,reset(){tutorial('🧱 🌉 🚗','Build the bridge in number order.');this.n=Math.min(7,3+d);this.slots=Array.from({length:this.n},(_,i)=>({x:230+i*540/(this.n-1),y:335,id:i}));this.blocks=shuffle(this.slots.map((_,i)=>i)).map((id,i)=>({id,x:150+i*700/(this.n-1),y:520}))},draw(){bg('#5ad8ff','#7fe69a');ctx.fillStyle='#32bce8';ctx.fillRect(0,370,W,155);ctx.font='65px serif';ctx.fillText('🚗',70,310);ctx.fillText('🏁',930,305);this.slots.forEach(s=>{ctx.strokeStyle='#fff';ctx.lineWidth=5;ctx.setLineDash([10,8]);ctx.strokeRect(s.x-55,s.y-30,110,60)});ctx.setLineDash([]);this.blocks.forEach(o=>{if(!o.ok){rr(o.x-52,o.y-28,104,56,11,['#ff7474','#ffd14a','#7a68ff','#49d1c1'][o.id%4]);ctx.fillStyle='#fff';ctx.font='bold 25px sans-serif';ctx.textAlign='center';ctx.fillText(o.id+1,o.x,o.y+9)}})},down(p){this.sel=this.blocks.find(o=>!o.ok&&dist(p,o)<70)},move(p){if(this.sel){this.sel.x=p.x;this.sel.y=p.y;this.draw()}},up(p){if(!this.sel)return;let s=this.slots[this.sel.id];if(dist(p,s)<82){this.sel.ok=1;confetti(s.x,s.y);if(this.blocks.every(x=>x.ok))win()}else wrong();this.sel=null;this.draw()}};return G}
function memory(d){let G={lives:3,reset(){tutorial('🧠 🃏','Find all matching pairs.');let n=Math.min(6,3+d),a=shuffle(['🦄','🚀','🍉','⚽','🐙','🎸','🦖']).slice(0,n);this.cards=shuffle([...a,...a]).map((e,i)=>({e,x:155+(i%4)*230,y:130+Math.floor(i/4)*175,open:false,done:false}));this.first=null;this.lock=false},draw(){bg('#a891ff','#ff91c2');ctx.textAlign='center';this.cards.forEach(c=>{rr(c.x-76,c.y-65,152,130,24,c.open||c.done?'#fff':'#594ac8');ctx.font='62px serif';ctx.fillText(c.open||c.done?c.e:'⭐',c.x,c.y+5)})},down(p){if(this.lock)return;let c=this.cards.find(c=>!c.done&&!c.open&&dist(p,c)<85);if(!c)return;c.open=true;if(!this.first){this.first=c;this.draw();return}if(this.first.e===c.e){c.done=this.first.done=true;this.first=null;confetti(c.x,c.y);if(this.cards.every(x=>x.done))win()}else{this.lock=true;this.draw();setTimeout(()=>{c.open=this.first.open=false;this.first=null;this.lock=false;wrong();this.draw()},650)}}};return G}
function maze(d){let G={lives:3,reset(){tutorial('🦸 ➜ 💎','Guide the hero to the crystal.');this.n=Math.min(10,6+d);this.p={x:0,y:0};this.goal={x:this.n-1,y:this.n-1};this.walls=new Set();for(let y=0;y<this.n;y++)for(let x=0;x<this.n;x++)if(Math.random()<.12&&x!==y&&!(x===0&&y===0)&&!(x===this.n-1&&y===this.n-1))this.walls.add(`${x},${y}`);let c=$('#tapControls');c.innerHTML='';[['⬆️',0,-1],['⬅️',-1,0],['⬇️',0,1],['➡️',1,0]].forEach(q=>{let b=document.createElement('button');b.textContent=q[0];b.onclick=()=>this.go(q[1],q[2]);c.appendChild(b)})},go(dx,dy){let x=this.p.x+dx,y=this.p.y+dy;if(x<0||y<0||x>=this.n||y>=this.n||this.walls.has(`${x},${y}`)){wrong();return}this.p={x,y};tone(460,.04);this.draw();if(x===this.goal.x&&y===this.goal.y)win()},draw(){bg('#52d9ff','#92f0bc');let z=500/this.n,ox=250,oy=60;for(let y=0;y<this.n;y++)for(let x=0;x<this.n;x++)rr(ox+x*z+2,oy+y*z+2,z-4,z-4,8,this.walls.has(`${x},${y}`)?'#5b4b8a':'rgba(255,255,255,.78)');ctx.font=`${z*.65}px serif`;ctx.fillText('🦸',ox+(this.p.x+.5)*z,oy+(this.p.y+.5)*z);ctx.fillText('💎',ox+(this.goal.x+.5)*z,oy+(this.goal.y+.5)*z)}};return G}
function pattern(d){let G={lives:3,reset(){tutorial('🧩 ❓','What comes next?');let sets=[['🔴','🔵'],['🌞','🌙'],['🐸','🦊','🐼'],['⭐','💎','⭐','❤️'],['🍎','🍌','🍎']];this.base=sets[ri(0,sets.length-1)];this.len=Math.min(8,4+d);this.seq=Array.from({length:this.len},(_,i)=>this.base[i%this.base.length]);this.ans=this.base[this.len%this.base.length];let opts=shuffle([...new Set([...this.base,'🟢','🟣','🔶','🟡'])]).slice(0,4);if(!opts.includes(this.ans))opts[0]=this.ans;let c=$('#tapControls');c.innerHTML='';shuffle(opts).forEach(e=>{let b=document.createElement('button');b.textContent=e;b.onclick=()=>e===this.ans?win():wrong();c.appendChild(b)})},draw(){bg('#ffcf69','#ff91c8');ctx.textAlign='center';ctx.font='76px serif';this.seq.forEach((e,i)=>ctx.fillText(e,120+i*(760/(this.seq.length-1)),280));rr(435,405,130,120,28,'#fff');ctx.font='75px serif';ctx.fillText('❓',500,475)}};return G}
function catcher(d){let G={lives:3,continuous:true,reset(){tutorial('⭐ 🧺','Catch the stars and avoid storm clouds.');this.player=500;this.objects=[];this.score=0;this.need=5+d*2;this.last=performance.now();this.finished=false},update(){let t=performance.now();if(t-this.last>650){this.objects.push({x:rnd(70,930),y:-30,bad:Math.random()<.24});this.last=t}this.objects.forEach(o=>o.y+=3.3+d*.7);this.objects.forEach(o=>{if(o.y>500&&o.y<590&&Math.abs(o.x-this.player)<80&&!o.hit){o.hit=true;if(o.bad)wrong();else{this.score++;tone(720);confetti(o.x,o.y);if(this.score>=this.need)win()}}});this.objects=this.objects.filter(o=>o.y<660&&!o.hit)},draw(){if(this.finished)return;this.update();bg('#3d7bff','#b55cff');ctx.font='38px serif';ctx.fillText(`⭐ ${this.score}/${this.need}`,85,55);this.objects.forEach(o=>{ctx.font='55px serif';ctx.fillText(o.bad?'🌩️':'⭐',o.x,o.y)});ctx.font='90px serif';ctx.fillText('🧺',this.player,575)},down(p){this.player=p.x},move(p){this.player=p.x}};return G}
function tower(d){let G={lives:3,reset(){tutorial('🏗️ 🏰','Stack biggest to smallest.');this.n=Math.min(7,4+d);this.slots=Array.from({length:this.n},(_,i)=>({x:500,y:505-i*66,id:i}));this.blocks=shuffle(Array.from({length:this.n},(_,i)=>i)).map((id,i)=>({id,x:120+i*760/(this.n-1),y:585,w:155-id*14}))},draw(){bg('#ffdc6c','#75dcff');ctx.fillStyle='#65c56e';ctx.fillRect(0,610,W,40);if(images.castle.complete&&images.castle.naturalWidth){ctx.globalAlpha=.16;ctx.drawImage(images.castle,40,70,190,320);ctx.globalAlpha=1}this.slots.forEach(s=>{ctx.strokeStyle='rgba(255,255,255,.8)';ctx.lineWidth=4;ctx.strokeRect(s.x-85,s.y-28,170,56)});this.blocks.forEach(o=>{if(!o.ok)rr(o.x-o.w/2,o.y-28,o.w,56,12,['#ff627d','#6e5cff','#32cbd1','#ffae32'][o.id%4])})},down(p){this.sel=this.blocks.find(o=>!o.ok&&Math.abs(p.x-o.x)<90&&Math.abs(p.y-o.y)<55)},move(p){if(this.sel){this.sel.x=p.x;this.sel.y=p.y;this.draw()}},up(p){if(!this.sel)return;let s=this.slots[this.sel.id];if(dist(p,s)<85){this.sel.ok=1;confetti(s.x,s.y);if(this.blocks.every(x=>x.ok))win()}else wrong();this.sel=null;this.draw()}};return G}
function shadow(d){let G={lives:3,reset(){tutorial('🔎 🐾','Find the picture matching the shadow.');this.opts=shuffle(['🦖','🚀','🐘','🚲','🐠','🦋','🏰']).slice(0,Math.min(6,3+d));this.ans=this.opts[ri(0,this.opts.length-1)]},draw(){bg('#65e0c0','#8aa5ff');ctx.textAlign='center';rr(370,75,260,210,38,'#fff');ctx.globalAlpha=.18;ctx.font='130px serif';ctx.fillText(this.ans,500,190);ctx.globalAlpha=1;this.opts.forEach((e,i)=>{let x=110+i*780/(this.opts.length-1);rr(x-60,420,120,120,25,'#fff');ctx.font='70px serif';ctx.fillText(e,x,490)})},down(p){if(p.y<390)return;let i=Math.round((p.x-110)/(780/(this.opts.length-1)));i=Math.max(0,Math.min(this.opts.length-1,i));this.opts[i]===this.ans?win():wrong()}};return G}
function battle(d){let G={lives:3,reset(){tutorial('🦸 ⚔️ 🤖','Hero battle! Choose the power that beats the robot attack.');this.round=0;this.need=3+d;this.heroHP=4+d;this.botHP=3+d;this.finished=false;this.newRound()},newRound(){let q=[{bad:'🔥',good:'💧'},{bad:'🧊',good:'🔥'},{bad:'⚡',good:'🛡️'},{bad:'🪨',good:'💥'},{bad:'🌪️',good:'🪨'}];this.q=q[ri(0,q.length-1)];this.opts=shuffle([this.q.good,...shuffle(['💧','🔥','🛡️','💥','🪨']).filter(x=>x!==this.q.good).slice(0,2)]);let c=$('#tapControls');c.innerHTML='';this.opts.forEach(e=>{let b=document.createElement('button');b.textContent=e;b.onclick=()=>this.choose(e);c.appendChild(b)})},choose(e){if(e===this.q.good){this.round++;this.botHP--;tone(250+d*30,.06);confetti(760,330);if(this.botHP<=0||this.round>=this.need)return win();this.newRound();this.draw()}else{this.heroHP--;wrong();if(this.heroHP<=0)this.reset();else{this.newRound();this.draw()}}},draw(){bg('#38356f','#dc5b97');ctx.fillStyle='rgba(255,255,255,.16)';for(let x=0;x<W;x+=110)ctx.fillRect(x,480-(x%220?35:0),85,170);ctx.font='145px serif';ctx.fillText('🦸',215,390);ctx.fillText('🤖',785,390);ctx.font='90px serif';ctx.fillText(this.q.bad,650,195);ctx.fillStyle='#38e68a';ctx.fillRect(90,520,Math.max(20,this.heroHP*55),22);ctx.fillStyle='#ff6078';ctx.fillRect(650,520,Math.max(20,this.botHP*55),22);ctx.fillStyle='#fff';ctx.font='30px sans-serif';ctx.fillText(`⭐ ${this.round}/${this.need}`,470,65)}};return G}
function scavenge(d){let G={lives:3,reset(){tutorial('🗺️ 🔎 💎','Scavenger hunt! Find every hidden item on the map.');this.need=Math.min(7,4+d);let pool=shuffle(['🔑','💎','🧭','👑','🐚','🍎','⚽','🚀','🦋','🪙']);this.items=pool.slice(0,this.need).map((e,i)=>({e,x:rnd(100,900),y:rnd(135,545),r:42,found:false}));this.decoys=shuffle(pool.slice(this.need)).slice(0,3).map(e=>({e,x:rnd(100,900),y:rnd(135,545),r:42}));this.found=0},draw(){if(images.map.complete&&images.map.naturalWidth){ctx.fillStyle='#f5e1a5';ctx.fillRect(0,0,W,H);ctx.globalAlpha=.62;ctx.drawImage(images.map,0,0,W,H);ctx.globalAlpha=1}else{bg('#e9d18b','#8fd8a8');ctx.font='65px serif';['🌴','⛰️','🏕️','🌊','🪨','🌳'].forEach((e,i)=>ctx.fillText(e,120+i*150,150+(i%2)*260))}rr(18,18,964,82,28,'rgba(255,255,255,.86)');ctx.font='48px serif';ctx.textAlign='left';let x=45;this.items.forEach(o=>{ctx.globalAlpha=o.found?.25:1;ctx.fillText(o.found?'✅':o.e,x,68);ctx.globalAlpha=1;x+=110});ctx.textAlign='center';[...this.items,...this.decoys].forEach(o=>{if(o.found)return;ctx.font='56px serif';ctx.fillText(o.e,o.x,o.y)})},down(p){let o=this.items.find(o=>!o.found&&dist(p,o)<55);if(o){o.found=true;this.found++;tone(760);confetti(o.x,o.y);if(this.found===this.need)win();this.draw()}else{let hit=this.decoys.find(o=>dist(p,o)<55);if(hit)wrong()}}};return G}
function sequence(d){let G={lives:3,reset(){tutorial('🎵 👂 ✨','Watch the magic sequence, then repeat it.');this.buttons=['🔴','🔵','🟢','🟡'];this.seq=Array.from({length:Math.min(8,3+d)},()=>ri(0,3));this.input=[];this.flash=-1;this.lock=true;this.show(0)},show(i){if(i>=this.seq.length){this.lock=false;this.flash=-1;this.draw();return}this.flash=this.seq[i];tone([440,520,620,740][this.flash],.12);this.draw();setTimeout(()=>{this.flash=-1;this.draw();setTimeout(()=>this.show(i+1),180)},380)},draw(){bg('#382f7e','#ff69a8');ctx.textAlign='center';ctx.font='68px serif';ctx.fillText('✨',500,95);this.buttons.forEach((e,i)=>{let x=210+(i%2)*580,y=245+Math.floor(i/2)*220;rr(x-105,y-78,210,156,35,this.flash===i?'#fff':'rgba(255,255,255,.72)');ctx.font='92px serif';ctx.fillText(e,x,y)})},down(p){if(this.lock)return;let coords=[[210,245],[790,245],[210,465],[790,465]],i=coords.findIndex(([x,y])=>Math.hypot(p.x-x,p.y-y)<130);if(i<0)return;tone([440,520,620,740][i],.09);if(i===this.seq[this.input.length]){this.input.push(i);this.flash=i;this.draw();setTimeout(()=>{this.flash=-1;this.draw()},160);if(this.input.length===this.seq.length)win()}else{this.input=[];wrong()}}};return G}
$('#playBtn').onclick=()=>start(Math.min(state.unlocked,60));$('#mapBtn').onclick=()=>show('#mapScreen');$('#homeBtn').onclick=()=>show('#homeScreen');$('#backToMapBtn').onclick=()=>show('#mapScreen');$('#restartBtn').onclick=()=>start(current);$('#rewardMapBtn').onclick=()=>show('#mapScreen');$('#retryBtn').onclick=()=>start(current);$('#nextBtn').onclick=()=>current<60?start(current+1):show('#mapScreen');$('#treasureBtn').onclick=()=>show('#treasureScreen');$('#treasureBackBtn').onclick=()=>show('#homeScreen');
$('#soundBtn').onclick=()=>{state.settings.sound=!state.settings.sound;save();if(state.settings.sound)ensureMusic();else{stopMusic();speechSynthesis?.cancel?.()}};
let hold=0,timer;function gate(){show('#parentGate')}$('#parentBtn').onclick=gate;function hs(){hold++;$('#holdProgress').style.width=(hold/30*100)+'%';if(hold>=30){clearInterval(timer);hold=0;show('#parentScreen')}}function hd(){clearInterval(timer);hold=0;$('#holdProgress').style.width='0'};['gateLeft','gateRight'].forEach(id=>{let b=$('#'+id);b.onpointerdown=()=>{if(!timer)timer=setInterval(hs,100)};b.onpointerup=hd;b.onpointerleave=hd});$('#gateCancel').onclick=()=>show('#homeScreen');$('#parentClose').onclick=()=>show('#homeScreen');
function parent(){$('#dashLevel').textContent=state.unlocked;$('#dashStars').textContent=Object.values(state.stars).reduce((a,b)=>a+b,0);$('#dashMinutes').textContent=Math.floor(state.playSeconds/60);$('#profilePrompt').classList.toggle('hidden',!!state.profile);let box=$('#skillBars');box.innerHTML='';Object.entries(state.skillXP).forEach(([k,v])=>{let d=document.createElement('div');d.className='skill';d.innerHTML=`<span>${k}</span><div class="skill-track"><div class="skill-fill" style="width:${Math.min(100,v/3)}%"></div></div><b>${v}</b>`;box.appendChild(d)});$('#sessionLimit').value=state.settings.sessionLimit;$('#reducedMotion').checked=state.settings.reducedMotion;$('#calmMode').checked=state.settings.calmMode}
$('#profileForm').onsubmit=e=>{e.preventDefault();state.profile={name:$('#childName').value.trim(),age:+$('#childAge').value,email:$('#parentEmail').value.trim()};save();parent()};$('#sessionLimit').onchange=e=>{state.settings.sessionLimit=+e.target.value;save()};$('#reducedMotion').onchange=e=>{state.settings.reducedMotion=e.target.checked;save()};$('#calmMode').onchange=e=>{state.settings.calmMode=e.target.checked;save()};$('#resetBtn').onclick=()=>{if(confirm('Reset all BrainQuest Kids progress on this device?')){localStorage.removeItem('brainquestKidsState');location.reload()}};$('#restHomeBtn').onclick=()=>show('#homeScreen');
setInterval(()=>{if(!document.hidden){state.playSeconds++;if(state.settings.sessionLimit&&Date.now()-state.sessionStart>state.settings.sessionLimit*60000)show('#restScreen');if(state.playSeconds%15===0)save()}},1000);
window.addEventListener('error',()=>renderError());top();
})();
