export const ZONES=[
 {id:'castle',name:'Puzzle Castle',icon:'🏰',x:185,y:165,color:'#9468ff'},
 {id:'forest',name:'Mystery Forest',icon:'🌳',x:390,y:130,color:'#42c779'},
 {id:'space',name:'Space World',icon:'🚀',x:630,y:120,color:'#6a63ff'},
 {id:'pirate',name:'Pirate Island',icon:'🏴‍☠️',x:910,y:150,color:'#e6ad3f'},
 {id:'dino',name:'Dinosaur Valley',icon:'🦖',x:1110,y:235,color:'#78bd52'},
 {id:'robot',name:'Robot City',icon:'🤖',x:1010,y:420,color:'#6e8da8'},
 {id:'ocean',name:'Underwater Kingdom',icon:'🌊',x:1080,y:600,color:'#37bbdf'},
 {id:'race',name:'Racing World',icon:'🏎️',x:810,y:610,color:'#ff6a65'},
 {id:'builder',name:'Builder World',icon:'🧱',x:560,y:610,color:'#f5a341'},
 {id:'hero',name:'Hero Academy',icon:'🦸',x:335,y:590,color:'#ff5d8d'},
 {id:'candy',name:'Candy Land',icon:'🍭',x:135,y:535,color:'#ff8cc9'},
 {id:'snake',name:'Snake Arena',icon:'🐍',x:105,y:350,color:'#58cc6a'},
 {id:'caves',name:'Treasure Caves',icon:'💎',x:300,y:355,color:'#3fc5df'},
 {id:'brain',name:'Brain Lab',icon:'🧠',x:570,y:365,color:'#9d72ff'},
 {id:'volcano',name:'Volcano Adventure',icon:'🌋',x:810,y:350,color:'#e95b45'}
];

export const MISSIONS=[
 {id:1,zone:'forest',type:'scavenge',title:'Golden Star Hunt',icon:'⭐',goal:5,theme:'forest'},
 {id:2,zone:'castle',type:'maze',title:'Three Castle Keys',icon:'🔑',goal:3,theme:'castle'},
 {id:3,zone:'snake',type:'snake',title:'Fruit Dash',icon:'🍎',goal:14,theme:'grass'},
 {id:4,zone:'builder',type:'builder',title:'Bridge Rescue',icon:'🌉',goal:8,theme:'river',variant:'bridge'},
 {id:5,zone:'hero',type:'hero',title:'Training Bots',icon:'🤖',goal:5,theme:'academy'},
 {id:6,zone:'race',type:'race',title:'Sunny Circuit',icon:'🏁',goal:3,theme:'road'},
 {id:7,zone:'castle',type:'memory',title:'Royal Memory',icon:'👑',goal:4,theme:'castle'},
 {id:8,zone:'space',type:'platform',title:'Moon Jump',icon:'🌙',goal:7,theme:'space'},
 {id:9,zone:'pirate',type:'scavenge',title:'Treasure Map Pieces',icon:'🗺️',goal:6,theme:'island'},
 {id:10,zone:'brain',type:'pattern',title:'Colour Reactor',icon:'🟣',goal:5,theme:'lab'},
 {id:11,zone:'dino',type:'scavenge',title:'Dino Egg Rescue',icon:'🥚',goal:5,theme:'dino'},
 {id:12,zone:'robot',type:'logic',title:'Battery Sort',icon:'🔋',goal:6,theme:'robot'},
 {id:13,zone:'ocean',type:'race',title:'Coral Boat Run',icon:'🛶',goal:4,theme:'ocean'},
 {id:14,zone:'candy',type:'match',title:'Sweet Shapes',icon:'🍬',goal:6,theme:'candy'},
 {id:15,zone:'caves',type:'hidden',title:'Crystal Cave',icon:'💎',goal:7,theme:'cave'},
 {id:16,zone:'volcano',type:'platform',title:'Lava Leap',icon:'🌋',goal:8,theme:'volcano'},
 {id:17,zone:'castle',type:'math',title:'Number Bridge',icon:'➕',goal:5,theme:'castle'},
 {id:18,zone:'forest',type:'science',title:'Animal Homes',icon:'🐾',goal:6,theme:'forest'},
 {id:19,zone:'space',type:'scavenge',title:'Lost Moon Rocks',icon:'🪨',goal:6,theme:'space'},
 {id:20,zone:'pirate',type:'maze',title:'Secret Lagoon Maze',icon:'🧭',goal:1,theme:'island'},
 {id:21,zone:'dino',type:'platform',title:'Raptor Ridge',icon:'🦕',goal:9,theme:'dino'},
 {id:22,zone:'robot',type:'hero',title:'Magnet Bot Battle',icon:'🧲',goal:6,theme:'robot',power:'magnet'},
 {id:23,zone:'ocean',type:'scavenge',title:'Pearl Search',icon:'🦪',goal:7,theme:'ocean'},
 {id:24,zone:'race',type:'race',title:'Rocket Sprint',icon:'🚀',goal:5,theme:'space'},
 {id:25,zone:'builder',type:'builder',title:'Tower Challenge',icon:'🏗️',goal:12,theme:'builder',variant:'tower'},
 {id:26,zone:'hero',type:'hero',title:'Shield School',icon:'🛡️',goal:7,theme:'academy',power:'shield'},
 {id:27,zone:'candy',type:'snake',title:'Candy Snake',icon:'🍭',goal:20,theme:'candy'},
 {id:28,zone:'caves',type:'logic',title:'Gem Path',icon:'🔷',goal:6,theme:'cave'},
 {id:29,zone:'brain',type:'memory',title:'Sound Lights',icon:'🎵',goal:5,theme:'lab'},
 {id:30,zone:'volcano',type:'math',title:'Cool the Lava',icon:'❄️',goal:6,theme:'volcano'},
 {id:31,zone:'castle',type:'word',title:'Magic Letters',icon:'🔤',goal:5,theme:'castle'},
 {id:32,zone:'forest',type:'hidden',title:'Butterfly Search',icon:'🦋',goal:8,theme:'forest'},
 {id:33,zone:'space',type:'race',title:'Asteroid Run',icon:'☄️',goal:5,theme:'space'},
 {id:34,zone:'pirate',type:'builder',title:'Raft Builder',icon:'🪵',goal:10,theme:'island',variant:'raft'},
 {id:35,zone:'dino',type:'science',title:'Fossil Match',icon:'🦴',goal:6,theme:'dino'},
 {id:36,zone:'robot',type:'pattern',title:'Robot Code',icon:'⚙️',goal:6,theme:'robot'},
 {id:37,zone:'ocean',type:'maze',title:'Coral Maze',icon:'🐠',goal:1,theme:'ocean'},
 {id:38,zone:'race',type:'race',title:'Dragon Dash',icon:'🐉',goal:6,theme:'fantasy'},
 {id:39,zone:'builder',type:'builder',title:'Animal House',icon:'🏠',goal:14,theme:'builder',variant:'house'},
 {id:40,zone:'hero',type:'boss',title:'Pattern Shield Boss',icon:'⚡',goal:4,theme:'academy'},
 {id:41,zone:'candy',type:'math',title:'Cookie Counting',icon:'🍪',goal:7,theme:'candy'},
 {id:42,zone:'caves',type:'scavenge',title:'Three Secret Keys',icon:'🔑',goal:3,theme:'cave'},
 {id:43,zone:'brain',type:'logic',title:'Pipe Connector',icon:'🔗',goal:7,theme:'lab'},
 {id:44,zone:'volcano',type:'hero',title:'Wind Power Rescue',icon:'🌪️',goal:8,theme:'volcano',power:'wind'},
 {id:45,zone:'forest',type:'word',title:'Picture Words',icon:'🅰️',goal:6,theme:'forest'},
 {id:46,zone:'space',type:'pattern',title:'Planet Sequence',icon:'🪐',goal:7,theme:'space'},
 {id:47,zone:'pirate',type:'hidden',title:'Captain’s Lost Coins',icon:'🪙',goal:10,theme:'island'},
 {id:48,zone:'dino',type:'race',title:'Dino Ride',icon:'🦖',goal:6,theme:'dino'},
 {id:49,zone:'robot',type:'boss',title:'Mega Robot Lab',icon:'🤖',goal:5,theme:'robot'},
 {id:50,zone:'caves',type:'boss',title:'Treasure Guardian',icon:'👑',goal:6,theme:'cave'}
];

export const PETS=['🐶','🐱','🐼','🦖','🤖','🐉','🦄'];
export const OUTFITS=['🟦','🟥','🟩','🟪','🟨'];
export const zoneMissions=id=>MISSIONS.filter(m=>m.zone===id);
