import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.185.1/build/three.module.js';

const POS={castle:[-18,-18],forest:[-34,-3],space:[-8,-38],pirate:[20,-35],dino:[38,-16],robot:[36,12],ocean:[26,36],race:[2,38],builder:[-21,32],hero:[-38,20],candy:[-42,2],snake:[-30,-24],caves:[-10,12],brain:[10,8],volcano:[27,-3]};
const C={sky:0x66cfff,grass:0x53c85a,grass2:0x2f9d47,path:0xe9d18a,blue:0x3f75ff,pink:0xff4f93,purple:0x7657f5,yellow:0xffd33f,orange:0xff9b38,green:0x39c86b,red:0xff525f,dark:0x263052,white:0xffffff,water:0x31b8ee};
const mat=(c,r=.55)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:.02});
const glow=(c)=>new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:.85,roughness:.22});
function box(w,h,d,c,r=.55){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c,r));m.castShadow=m.receiveShadow=true;return m}
function cyl(a,b,h,c,s=16){const m=new THREE.Mesh(new THREE.CylinderGeometry(a,b,h,s),mat(c));m.castShadow=m.receiveShadow=true;return m}
function ball(r,c){const m=new THREE.Mesh(new THREE.SphereGeometry(r,18,12),mat(c,.42));m.castShadow=m.receiveShadow=true;return m}
function pad(c){const g=new THREE.Group(),b=cyl(5.5,5.7,.7,0xf4f4f4,32),t=cyl(5.1,5.1,.38,c,32);b.position.y=.3;t.position.y=.72;g.add(b,t);return g}
function sign(text,color=0xffffff){const c=document.createElement('canvas');c.width=512;c.height=144;const x=c.getContext('2d');x.fillStyle='rgba(20,26,48,.9)';x.fillRect(18,24,476,96);x.strokeStyle='#fff';x.lineWidth=6;x.strokeRect(18,24,476,96);x.fillStyle=color;x.font='900 38px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(text,256,72);const tx=new THREE.CanvasTexture(c);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:tx,transparent:true,depthWrite:false}));s.scale.set(8.6,2.4,1);return s}
function portal(id,x,z,c,name){const g=pad(c);const frame=box(5.8,6,.7,0xeeeeee,.28);frame.position.y=3.45;g.add(frame);const hole=box(4.3,4.6,.8,C.dark,.7);hole.position.set(0,3.25,.05);g.add(hole);const inner=box(3.65,4.05,.9,c,.25);inner.position.set(0,3.25,.12);inner.material=glow(c);inner.userData.pulse=true;g.add(inner);const s=sign(name);s.position.set(0,7.2,0);s.userData.zoneSign=true;g.add(s);g.position.set(x,0,z);g.userData.zoneId=id;return g}
function castle(x,z,name){const g=pad(C.purple),base=box(7,4.7,5,0x8066e8);base.position.y=3;g.add(base);for(const dx of[-3.3,3.3]){const t=box(2.1,6,2.1,0x6550ca);t.position.set(dx,3.6,0);g.add(t);for(let k=-1;k<=1;k++){const cren=box(.55,.65,.55,C.white);cren.position.set(dx+k*.65,6.9,0);g.add(cren)}}const door=box(1.8,2.9,.35,C.dark);door.position.set(0,1.8,2.7);g.add(door);const s=sign(name);s.position.set(0,8.1,0);g.add(s);g.position.set(x,0,z);return g}
function rocket(x,z,name){const g=pad(0x5d78ff);const body=box(2.2,5,2.2,C.white);body.position.y=3.5;g.add(body);const nose=new THREE.Mesh(new THREE.ConeGeometry(1.55,2.2,4),mat(C.pink));nose.rotation.y=Math.PI/4;nose.position.y=7.05;g.add(nose);const flame=box(1,1.5,1,C.orange);flame.position.y=.45;flame.material=glow(C.orange);flame.userData.pulse=true;g.add(flame);const s=sign(name);s.position.set(0,9,0);g.add(s);g.position.set(x,0,z);return g}
function lab(x,z,name){const g=pad(0xcfc9ff),b=box(7,4,5,0xf4f6ff);b.position.y=2.7;g.add(b);for(const [dx,c] of[[-2,0x26dfff],[0,0xff55ae],[2,0xffdc36]]){const q=box(1.2,3.2,1.2,c);q.position.set(dx,4.5,0);q.material=glow(c);g.add(q)}const s=sign(name);s.position.set(0,7.3,0);g.add(s);g.position.set(x,0,z);return g}
function volcano(x,z,name){const g=pad(0xff865c);for(let y=0;y<5;y++){const w=8-y*1.25,b=box(w,1.1,w,0x71473d);b.position.y=.9+y*1.05;g.add(b)}const lava=box(3.2,.35,3.2,0xff3c20);lava.position.y=6.25;lava.material=glow(0xff3c20);lava.userData.pulse=true;g.add(lava);const s=sign(name);s.position.set(0,8.1,0);g.add(s);g.position.set(x,0,z);return g}
function marker(z,x,y){if(z.id==='castle')return castle(x,y,z.name);if(z.id==='space')return rocket(x,y,z.name);if(z.id==='brain')return lab(x,y,z.name);if(z.id==='volcano')return volcano(x,y,z.name);const cc={forest:0x3bc86c,pirate:0xf0aa3a,dino:0x7ac44f,robot:0x7089b0,ocean:0x2dbbe9,race:0xff5b58,builder:0xf2a43c,hero:0xf84f8d,candy:0xff77c9,snake:0x47c75d,caves:0x52637e};return portal(z.id,x,y,cc[z.id]||0x7657f5,z.name)}
function tree(x,z,s=1){const g=new THREE.Group(),tr=box(.85,3.1,.85,0x82522e),a=box(3.4,2.2,3.4,0x31a957),b=box(2.4,1.8,2.4,0x4ec56e);tr.position.y=1.55;a.position.y=4.05;b.position.set(.6,5,.2);g.add(tr,a,b);g.position.set(x,0,z);g.scale.setScalar(s);return g}
function avatar(color=C.blue,skin=0xf0b27c){const g=new THREE.Group();const torso=box(1.8,2.3,1.05,color,.42),head=box(1.5,1.5,1.5,skin,.36),al=box(.5,1.55,.52,skin,.42),ar=al.clone(),ll=box(.58,1.6,.66,0x26396b,.5),lr=ll.clone();torso.position.y=2.45;head.position.y=4.35;al.position.set(-1.16,2.4,0);ar.position.set(1.16,2.4,0);ll.position.set(-.5,.78,0);lr.position.set(.5,.78,0);g.add(torso,head,al,ar,ll,lr);const eyeL=box(.12,.12,.05,C.dark),eyeR=eyeL.clone();eyeL.position.set(-.3,4.45,.78);eyeR.position.set(.3,4.45,.78);g.add(eyeL,eyeR);g.userData={armL:al,armR:ar,legL:ll,legR:lr,torso,head};return g}
function home(){const g=pad(0xffdf67),b=box(6.2,4,5,0xffe17a),roof=box(6.7,1.1,5.5,0xff6b53),door=box(1.8,2.4,.35,C.dark);b.position.y=2.8;roof.position.y=5.35;door.position.set(0,1.7,2.68);g.add(b,roof,door);const s=sign('Hero Home');s.position.set(0,7.4,0);g.add(s);return g}
function obby(scene){const colors=[C.red,C.orange,C.yellow,C.green,C.blue,C.purple,C.pink];for(let i=0;i<16;i++){const p=box(2.6,.45,2.6,colors[i%7],.35);p.position.set(-13+i*1.8,.6+(i%4)*.75,11+i*.8);p.rotation.y=(i%3)*.22;p.userData.obby=true;scene.add(p)}for(let i=0;i<5;i++){const p=box(4,.4,1.3,[C.blue,C.pink,C.yellow,C.green,C.orange][i]);p.position.set(9+i*2.4,1.4+i*.75,10+i*2);p.userData.mover={base:p.position.clone(),axis:i%2?'x':'z',phase:i};scene.add(p)}const jp=box(3.2,.25,3.2,0x2bf4ff);jp.position.set(13,.28,17);jp.material=glow(0x2bf4ff);jp.userData.jumpPad=true;scene.add(jp)}
function npc(x,z,c,phase){const n=avatar(c);n.scale.setScalar(.82);n.position.set(x,0,z);n.userData.npc={cx:x,cz:z,phase};return n}

export function createHub3D({canvas,ZONES,onNearChange,onCollect,onStep,onLand}){
 const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;
 const scene=new THREE.Scene();scene.background=new THREE.Color(C.sky);scene.fog=new THREE.Fog(C.sky,145,245);
 const camera=new THREE.PerspectiveCamera(58,1,.2,280);scene.add(new THREE.HemisphereLight(0xf8ffff,0x466c3a,2.9));const sun=new THREE.DirectionalLight(0xfff5dc,3);sun.position.set(-35,50,25);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);scene.add(sun);
 const ocean=box(140,.7,140,C.water,.35);ocean.position.y=-1;scene.add(ocean);const island=box(114,1,114,C.grass2,.7);island.position.y=-.55;scene.add(island);const ground=box(108,.35,108,C.grass,.72);ground.position.y=-.02;scene.add(ground);const plaza=cyl(12,12,.38,0xead69b,48);plaza.position.y=.19;scene.add(plaza);
 for(const [,[x,z]] of Object.entries(POS)){const len=Math.hypot(x,z),p=box(3.8,.25,len,C.path,.8);p.position.set(x/2,.2,z/2);p.rotation.y=Math.atan2(x,z);scene.add(p)}
 const zones=[];for(const z of ZONES){const p=POS[z.id];if(!p)continue;const obj=marker(z,...p);scene.add(obj);zones.push({z,x:p[0],zz:p[1],obj})}scene.add(home());
 for(let i=0;i<26;i++){const a=i*2.399,r=17+(i*17)%31,x=Math.sin(a)*r,z=Math.cos(a)*r;if(zones.some(q=>Math.hypot(x-q.x,z-q.zz)<7))continue;scene.add(tree(x,z,.7+((i*5)%4)*.18))}
 obby(scene);const npcs=[npc(-5,6,C.pink,0),npc(7,-4,C.green,1.4),npc(-10,-7,C.orange,2.8)];npcs.forEach(n=>scene.add(n));
 const h=avatar();h.position.set(0,0,7);scene.add(h);const pet=box(.9,.9,.9,C.yellow);pet.position.set(-1.3,.48,8.5);scene.add(pet);
 const coins=[];for(let i=0;i<34;i++){const a=i*1.91,r=8+(i*8)%43,m=new THREE.Mesh(new THREE.CylinderGeometry(.45,.45,.14,18),new THREE.MeshStandardMaterial({color:0xffca19,metalness:.35,roughness:.25,emissive:0x4f3500,emissiveIntensity:.15}));m.rotation.z=Math.PI/2;m.position.set(Math.sin(a)*r,1.25,Math.cos(a)*r);scene.add(m);coins.push({m,taken:false})}
 let near=null,jumpV=0,walk=0,t=0,onGround=true,stepClock=0,camYaw=.55,camPitch=.34,drag=null;
 function resize(){const r=canvas.getBoundingClientRect(),w=Math.max(1,r.width),hh=Math.max(1,r.height);renderer.setSize(w,hh,false);camera.aspect=w/hh;camera.updateProjectionMatrix()}const ro=new ResizeObserver(resize);ro.observe(canvas);resize();
 canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture?.(e.pointerId)});
 canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;camYaw-=dx*.006;camPitch=Math.max(.18,Math.min(.62,camPitch+dy*.004))});
 canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);
 function update(dt,input){t+=dt;const speed=input.run?19:15.5,mag=Math.hypot(input.x,input.y),moving=mag>.055;if(moving){const ang=Math.atan2(input.x,input.y)+camYaw-Math.PI;const x=Math.sin(ang),z=Math.cos(ang);h.position.x+=x*speed*dt;h.position.z+=z*speed*dt;const d=Math.hypot(h.position.x,h.position.z);if(d>51){h.position.x*=51/d;h.position.z*=51/d}h.rotation.y=Math.atan2(x,z);walk+=dt*(input.run?18:15);stepClock-=dt;if(stepClock<=0&&h.position.y<=.02){onStep?.();stepClock=.28}}else stepClock=0;
 if(input.jump&&h.position.y<=.01){jumpV=8;onGround=false}jumpV-=20*dt;const prevY=h.position.y;h.position.y=Math.max(0,h.position.y+jumpV*dt);if(h.position.y===0&&prevY>0&&!onGround){onGround=true;jumpV=0;onLand?.()}else if(h.position.y===0&&jumpV<0)jumpV=0;
 const u=h.userData;if(moving){u.armL.rotation.x=Math.sin(walk)*.82;u.armR.rotation.x=-Math.sin(walk)*.82;u.legL.rotation.x=-Math.sin(walk)*.68;u.legR.rotation.x=Math.sin(walk)*.68;u.torso.rotation.z=Math.sin(walk*2)*.025}else{for(const p of[u.armL,u.armR,u.legL,u.legR])p.rotation.x*=.72;u.torso.rotation.z*=.75;u.armL.rotation.z=.08*Math.sin(t*2);u.armR.rotation.z=-.08*Math.sin(t*2)}
 pet.position.lerp(new THREE.Vector3(h.position.x-1.5*Math.sin(h.rotation.y),.48,h.position.z-1.5*Math.cos(h.rotation.y)),Math.min(1,dt*9));
 for(const q of coins){if(q.taken)continue;q.m.rotation.y+=dt*6;q.m.position.y=1.25+Math.sin(t*5+q.m.position.x)*.2;if(h.position.distanceTo(q.m.position)<1.45){q.taken=true;q.m.visible=false;onCollect?.()}}
 scene.traverse(o=>{if(o.userData.pulse){const s=1+Math.sin(t*5+o.position.x)*.045;o.scale.setScalar(s)}if(o.userData.obby)o.rotation.y+=dt*.16;if(o.userData.mover){const m=o.userData.mover,v=Math.sin(t*1.6+m.phase)*2.5;o.position[m.axis]=m.base[m.axis]+v}});
 npcs.forEach((n,i)=>{const q=n.userData.npc,a=t*.45+q.phase;n.position.x=q.cx+Math.cos(a)*2.2;n.position.z=q.cz+Math.sin(a)*2.2;n.rotation.y=-a+Math.PI/2;const uu=n.userData;uu.armL.rotation.x=Math.sin(t*7+i)*.5;uu.armR.rotation.x=-Math.sin(t*7+i)*.5;uu.legL.rotation.x=-Math.sin(t*7+i)*.45;uu.legR.rotation.x=Math.sin(t*7+i)*.45});
 let n=null,best=999;for(const q of zones){const d=Math.hypot(h.position.x-q.x,h.position.z-q.zz);if(d<5&&d<best){best=d;n=q.z}}const dh=Math.hypot(h.position.x,h.position.z);if(dh<4.8)n={id:'home',name:'Hero Home',icon:'🎒'};if(n?.id!==near?.id){near=n;onNearChange?.(near)}
 const dist=13.5,height=7.8,cp=Math.cos(camPitch),sp=Math.sin(camPitch),desired=new THREE.Vector3(h.position.x+Math.sin(camYaw)*dist*cp,h.position.y+height+sp*4,h.position.z+Math.cos(camYaw)*dist*cp);camera.position.lerp(desired,1-Math.pow(.00015,dt));camera.lookAt(h.position.x,h.position.y+2.4,h.position.z);renderer.render(scene,camera)}
 function setVisible(v){canvas.style.display=v?'block':'none';if(v)resize()}return{update,setVisible,getNear:()=>near,jump(){if(h.position.y<=.01){jumpV=8;onGround=false}},dispose(){ro.disconnect();renderer.dispose()}}
}
