import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.185.1/build/three.module.js';

const POS={castle:[-18,-18],forest:[-34,-3],space:[-8,-38],pirate:[20,-35],dino:[38,-16],robot:[36,12],ocean:[26,36],race:[2,38],builder:[-21,32],hero:[-38,20],candy:[-42,2],snake:[-30,-24],caves:[-10,12],brain:[10,8],volcano:[27,-3]};
const C={sky:0x50d5ff,grass:0x38c956,water:0x16bff2,path:0xf5cf69,blue:0x3f69f5,pink:0xff4d8a,purple:0x7049e8,yellow:0xffd33f};
const mat=(c,r=.34)=>new THREE.MeshPhysicalMaterial({color:c,roughness:r,metalness:.02,clearcoat:.65,clearcoatRoughness:.2});
function box(w,h,d,c){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));m.castShadow=m.receiveShadow=true;return m}
function cyl(a,b,h,c,s=20){const m=new THREE.Mesh(new THREE.CylinderGeometry(a,b,h,s),mat(c));m.castShadow=m.receiveShadow=true;return m}
function ball(r,c){const m=new THREE.Mesh(new THREE.SphereGeometry(r,20,14),mat(c));m.castShadow=m.receiveShadow=true;return m}
function pad(c){const g=new THREE.Group(),b=cyl(5.2,5.4,.5,0xffffff,32),t=cyl(4.85,4.85,.3,c,32);b.position.y=.25;t.position.y=.58;g.add(b,t);return g}
function portal(x,z,c){const g=pad(c),r=new THREE.Mesh(new THREE.TorusGeometry(2.35,.42,16,36),new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:.8,roughness:.18}));r.rotation.y=Math.PI/2;r.position.y=3.3;g.add(r);g.position.set(x,0,z);return g}
function castle(x,z){const g=pad(C.purple),b=box(6.3,4.5,4.6,0x7a56e8);b.position.y=2.9;g.add(b);for(const dx of[-3.2,3.2]){const t=cyl(1.2,1.3,5.5,0x6645d5);t.position.set(dx,3,0);const roof=new THREE.Mesh(new THREE.ConeGeometry(1.5,2.3,18),mat(C.pink));roof.position.set(dx,7,0);g.add(t,roof)}g.position.set(x,0,z);return g}
function lab(x,z){const g=pad(0xdcd7ff),b=box(6.6,3.6,4.8,0xf7f9ff);b.position.y=2.5;g.add(b);const d=new THREE.Mesh(new THREE.SphereGeometry(2.4,24,16,0,Math.PI*2,0,Math.PI/2),new THREE.MeshPhysicalMaterial({color:0x6b54ee,transparent:true,opacity:.88,clearcoat:1}));d.position.y=4.1;g.add(d);g.position.set(x,0,z);return g}
function volcano(x,z){const g=pad(0xff7d54),v=new THREE.Mesh(new THREE.ConeGeometry(5,7.8,24),mat(0x644139,.72));v.position.y=4.2;g.add(v);const l=cyl(1.3,1.5,.4,0xff351d,24);l.position.y=8.1;g.add(l);g.position.set(x,0,z);return g}
function rocket(x,z){const g=pad(0x5c6df4),b=cyl(.85,1.05,4.6,0xffffff,24);b.position.y=3.3;g.add(b);const n=new THREE.Mesh(new THREE.ConeGeometry(.86,1.8,24),mat(C.pink));n.position.y=6.5;g.add(n);g.position.set(x,0,z);return g}
function marker(id,x,z){if(id==='castle')return castle(x,z);if(id==='brain')return lab(x,z);if(id==='volcano')return volcano(x,z);if(id==='space')return rocket(x,z);const cc={forest:0x25c85c,pirate:0xf4a52a,dino:0x66c845,robot:0x6684b1,ocean:0x18bff2,race:0xff5050,builder:0xffa035,hero:0xf43c82,candy:0xff6bc3,snake:0x38c95c,caves:0x425777};return portal(x,z,cc[id]||0x6a4cff)}
function tree(x,z,s=1){const g=new THREE.Group(),tr=cyl(.4,.52,3,0x87502a,12),a=ball(1.75,0x18ad4f),b=ball(1.15,0x35c969);tr.position.y=1.5;a.position.y=4.2;b.position.set(.7,4.65,.15);g.add(tr,a,b);g.position.set(x,0,z);g.scale.setScalar(s);return g}
function hero(){const g=new THREE.Group(),body=box(1.55,2.05,.95,C.blue),head=ball(.76,0xf2b77f),al=box(.38,1.4,.42,0xf2b77f),ar=al.clone(),ll=box(.45,1.35,.55,0x24386c),lr=ll.clone();body.position.y=2.05;head.position.y=3.65;al.position.set(-.95,2.05,0);ar.position.set(.95,2.05,0);ll.position.set(-.38,.63,0);lr.position.set(.38,.63,0);g.add(body,head,al,ar,ll,lr);g.userData={armL:al,armR:ar,legL:ll,legR:lr};g.scale.setScalar(1.12);return g}
function home(){const g=pad(0xffdf68),b=box(5.2,3.6,4.3,0xffe17c),r=new THREE.Mesh(new THREE.ConeGeometry(4,2.5,4),mat(0xff694f));b.position.y=2.7;r.rotation.y=Math.PI/4;r.position.y=5.4;g.add(b,r);return g}

export function createHub3D({canvas,ZONES,onNearChange,onCollect}){
 const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;
 const scene=new THREE.Scene();scene.background=new THREE.Color(C.sky);scene.fog=new THREE.Fog(0x78ddff,130,220);
 const camera=new THREE.PerspectiveCamera(44,1,.2,240);scene.add(new THREE.HemisphereLight(0xf7ffff,0x3d6d34,2.7));const sun=new THREE.DirectionalLight(0xfff3d5,2.8);sun.position.set(-30,44,24);sun.castShadow=true;scene.add(sun);
 const ocean=new THREE.Mesh(new THREE.CircleGeometry(115,64),mat(C.water,.18));ocean.rotation.x=-Math.PI/2;ocean.position.y=-.7;scene.add(ocean);const ground=new THREE.Mesh(new THREE.CircleGeometry(58,64),mat(C.grass,.48));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);const beach=new THREE.Mesh(new THREE.RingGeometry(53,58,64),mat(0xffd66e,.5));beach.rotation.x=-Math.PI/2;beach.position.y=.03;scene.add(beach);const plaza=cyl(10.5,10.7,.32,0xf6d582,48);plaza.position.y=.14;scene.add(plaza);
 for(const [,[x,z]] of Object.entries(POS)){const len=Math.hypot(x,z),p=box(3.2,.2,len,C.path);p.position.set(x/2,.16,z/2);p.rotation.y=Math.atan2(x,z);scene.add(p)}
 const zones=[];for(const z of ZONES){const p=POS[z.id];if(!p)continue;const obj=marker(z.id,...p);scene.add(obj);zones.push({z,x:p[0],zz:p[1],obj})}scene.add(home());
 for(let i=0;i<32;i++){const a=i*2.399,r=16+(i*17)%33,x=Math.sin(a)*r,z=Math.cos(a)*r;if(zones.some(q=>Math.hypot(x-q.x,z-q.zz)<7))continue;scene.add(tree(x,z,.65+((i*7)%5)/10))}
 const h=hero();h.position.set(0,0,7);scene.add(h);const pet=ball(.46,C.yellow);pet.position.set(-1.2,.46,8.3);scene.add(pet);
 const coins=[];for(let i=0;i<24;i++){const a=i*2.1,r=10+(i*9)%38,m=new THREE.Mesh(new THREE.CylinderGeometry(.42,.42,.14,20),new THREE.MeshPhysicalMaterial({color:0xffc400,metalness:.45,roughness:.18,clearcoat:1}));m.rotation.z=Math.PI/2;m.position.set(Math.sin(a)*r,1.25,Math.cos(a)*r);scene.add(m);coins.push({m,taken:false})}
 let near=null,jumpV=0,walk=0,t=0;
 function resize(){const r=canvas.getBoundingClientRect(),w=Math.max(1,r.width),hh=Math.max(1,r.height);renderer.setSize(w,hh,false);camera.aspect=w/hh;camera.updateProjectionMatrix()}const ro=new ResizeObserver(resize);ro.observe(canvas);resize();
 function update(dt,input){t+=dt;const speed=input.run?18:14.5,mag=Math.hypot(input.x,input.y),moving=mag>.06;if(moving){const x=input.x/mag,z=input.y/mag;h.position.x+=x*speed*dt;h.position.z+=z*speed*dt;const d=Math.hypot(h.position.x,h.position.z);if(d>51){h.position.x*=51/d;h.position.z*=51/d}h.rotation.y=Math.atan2(x,z);walk+=dt*(input.run?17:14.5)}if(input.jump&&h.position.y<=.01)jumpV=7.2;jumpV-=18*dt;h.position.y=Math.max(0,h.position.y+jumpV*dt);if(h.position.y===0&&jumpV<0)jumpV=0;const u=h.userData;if(moving){u.armL.rotation.x=Math.sin(walk)*.72;u.armR.rotation.x=-Math.sin(walk)*.72;u.legL.rotation.x=-Math.sin(walk)*.58;u.legR.rotation.x=Math.sin(walk)*.58}else for(const p of[u.armL,u.armR,u.legL,u.legR])p.rotation.x*=.8;pet.position.lerp(new THREE.Vector3(h.position.x-1.5*Math.sin(h.rotation.y),.46,h.position.z-1.5*Math.cos(h.rotation.y)),Math.min(1,dt*8));for(const q of coins){if(q.taken)continue;q.m.rotation.y+=dt*5;q.m.position.y=1.25+Math.sin(t*4+q.m.position.x)*.17;if(h.position.distanceTo(q.m.position)<1.35){q.taken=true;q.m.visible=false;onCollect?.()}}let n=null,best=999;for(const q of zones){const d=Math.hypot(h.position.x-q.x,h.position.z-q.zz);if(d<4.9&&d<best){best=d;n=q.z}}const dh=Math.hypot(h.position.x,h.position.z);if(dh<4.8)n={id:'home',name:'Hero Home',icon:'🎒'};if(n?.id!==near?.id){near=n;onNearChange?.(near)}const desired=new THREE.Vector3(h.position.x+13.5,15.5,h.position.z+20);camera.position.lerp(desired,1-Math.pow(.00055,dt));camera.lookAt(h.position.x,2.1+h.position.y,h.position.z);renderer.render(scene,camera)}
 function setVisible(v){canvas.style.display=v?'block':'none';if(v)resize()}return{update,setVisible,getNear:()=>near,jump(){if(h.position.y<=.01)jumpV=7.2},dispose(){ro.disconnect();renderer.dispose()}}
}
