import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.185.1/build/three.module.js';

const POS={castle:[-20,-22],forest:[-38,-5],space:[-10,-44],pirate:[24,-40],dino:[43,-18],robot:[40,14],ocean:[28,42],race:[3,44],builder:[-24,37],hero:[-42,23],candy:[-46,3],snake:[-34,-29],caves:[-12,15],brain:[12,10],volcano:[31,-4]};
const C={sky:0x86c9ef,grass:0x5fa85d,grass2:0x477f48,path:0xc9ad78,blue:0x3978d4,pink:0xd75b8d,purple:0x6d5bb4,yellow:0xe9bd42,orange:0xd98743,green:0x4f9b63,red:0xc95858,dark:0x26334b,white:0xf4f1e8,water:0x3e98bc,brown:0x76523b};
const mat=(c,r=.72,m=0)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m});
function box(w,h,d,c,r=.72){const q=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c,r));q.castShadow=q.receiveShadow=true;return q}
function cyl(a,b,h,c,s=16){const q=new THREE.Mesh(new THREE.CylinderGeometry(a,b,h,s),mat(c));q.castShadow=q.receiveShadow=true;return q}
function glow(c){return new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:.45,roughness:.45})}
function tree(x,z,s=1){const g=new THREE.Group(),tr=cyl(.42,.55,3.7,C.brown,8);tr.position.y=1.85;g.add(tr);for(const [dx,y,dz,r] of[[0,4,0,1.8],[-1,4.2,.2,1.25],[1,4.35,.1,1.3],[.2,5.25,0,1.45]]){const q=new THREE.Mesh(new THREE.IcosahedronGeometry(r,1),mat(0x4d9258,.88));q.position.set(dx,y,dz);q.castShadow=true;g.add(q)}g.position.set(x,0,z);g.scale.setScalar(s);return g}
function rock(x,z,s=1){const q=new THREE.Mesh(new THREE.DodecahedronGeometry(s,0),mat(0x78858a,.95));q.position.set(x,s*.55,z);q.scale.y=.65;q.castShadow=q.receiveShadow=true;return q}
function sign(text){const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d');x.fillStyle='rgba(28,35,48,.88)';x.roundRect(20,20,472,88,24);x.fill();x.fillStyle='#fff';x.font='800 34px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(text,256,64);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthWrite:false}));s.scale.set(7.4,1.85,1);return s}
function portal(z,x,pz){const g=new THREE.Group(),base=cyl(4.2,4.5,.45,0x9b9b96,24);base.position.y=.22;g.add(base);const col={forest:0x52a66c,pirate:0xd49648,dino:0x7eaa55,robot:0x738ba6,ocean:0x429cc4,race:0xc95a5a,builder:0xd08d4b,hero:0xbd5b86,candy:0xd879a7,snake:0x4e9b5d,caves:0x65717f}[z.id]||0x7164b5;for(const sx of[-1,1]){const p=box(.65,4.5,.7,0xddd8ce);p.position.set(sx*2.25,2.55,0);g.add(p)}const top=box(5.15,.65,.7,0xddd8ce);top.position.y=4.8;g.add(top);const field=box(3.8,3.7,.18,col,.5);field.position.set(0,2.55,.08);field.material=glow(col);field.userData.pulse=true;g.add(field);const s=sign(z.name);s.position.set(0,6.4,0);s.userData.zoneSign=true;g.add(s);g.position.set(x,0,pz);return g}
function special(z,x,pz){if(!['castle','space','brain','volcano'].includes(z.id))return portal(z,x,pz);const g=new THREE.Group();if(z.id==='castle'){const b=box(7,4.5,5,0x8172b2);b.position.y=2.3;g.add(b);for(const dx of[-3,3]){const t=box(2,6,2,0x665a96);t.position.set(dx,3,0);g.add(t)}const d=box(1.7,2.7,.3,C.dark);d.position.set(0,1.4,2.65);g.add(d)}if(z.id==='space'){const b=cyl(1.2,1.2,5,C.white,16);b.position.y=3.2;g.add(b);const n=new THREE.Mesh(new THREE.ConeGeometry(1.5,2.4,16),mat(C.red));n.position.y=7;g.add(n)}if(z.id==='brain'){const b=box(7,4.5,5,0xb8bec7);b.position.y=2.3;g.add(b);for(const dx of[-2,0,2]){const q=cyl(.6,.6,3,[0x4f91a8,0xb76587,0xc79d4e][dx/2+1],16);q.position.set(dx,4.5,0);g.add(q)}}if(z.id==='volcano'){for(let i=0;i<5;i++){const q=cyl(5-i*.7,6-i*.7,1.2,0x695049,12);q.position.y=.6+i*1.05;g.add(q)}const l=cyl(1.8,1.8,.25,0xc94c37,16);l.position.y=5.8;l.material=glow(0xc94c37);g.add(l)}const s=sign(z.name);s.position.set(0,8,0);s.userData.zoneSign=true;g.add(s);g.position.set(x,0,pz);return g}
function avatar(color=C.blue,skin=0xd6a06f){const g=new THREE.Group(),torso=box(1.45,2.1,.85,color,.62),head=new THREE.Mesh(new THREE.SphereGeometry(.76,18,14),mat(skin,.68)),al=box(.42,1.75,.44,skin),ar=al.clone(),ll=box(.5,1.75,.58,0x34435f),lr=ll.clone();torso.position.y=2.55;head.position.y=4.15;al.position.set(-.96,2.55,0);ar.position.set(.96,2.55,0);ll.position.set(-.42,.88,0);lr.position.set(.42,.88,0);g.add(torso,head,al,ar,ll,lr);const hair=new THREE.Mesh(new THREE.SphereGeometry(.78,14,8,0,Math.PI*2,0,Math.PI/2),mat(0x2d2524));hair.position.y=4.38;g.add(hair);g.userData={armL:al,armR:ar,legL:ll,legR:lr,torso,head};return g}
function home(){const g=new THREE.Group(),b=box(7,4.2,5.5,0xd6bd82);b.position.y=2.1;g.add(b);const roof=new THREE.Mesh(new THREE.ConeGeometry(5.2,2.4,4),mat(0xa85b4c));roof.rotation.y=Math.PI/4;roof.position.y=5.4;g.add(roof);const d=box(1.6,2.6,.25,C.dark);d.position.set(0,1.3,2.9);g.add(d);g.position.set(0,0,0);return g}
function obby(scene){const colors=[0xb85b5b,0xd28c4f,0xc7a84e,0x5a9c69,0x527ca9,0x7869a8];for(let i=0;i<11;i++){const p=box(2.8,.45,2.8,colors[i%colors.length]);p.position.set(-14+i*2.25,.45+(i%3)*.7,15+i*.8);p.userData.obby=true;scene.add(p)}for(let i=0;i<4;i++){const p=box(4,.45,1.4,colors[(i+3)%colors.length]);p.position.set(10+i*3,1.2+i*.7,15+i*2);p.userData.mover={base:p.position.clone(),axis:i%2?'x':'z',phase:i};scene.add(p)}}
export function createHub3D({canvas,ZONES,onNearChange,onCollect,onStep,onLand}){
 const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
 const scene=new THREE.Scene();scene.background=new THREE.Color(C.sky);scene.fog=new THREE.FogExp2(C.sky,.0065);const camera=new THREE.PerspectiveCamera(62,1,.2,260);
 scene.add(new THREE.HemisphereLight(0xd9ecff,0x536a43,1.65));const sun=new THREE.DirectionalLight(0xffe7c2,2.35);sun.position.set(-32,48,28);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);sun.shadow.camera.left=-65;sun.shadow.camera.right=65;sun.shadow.camera.top=65;sun.shadow.camera.bottom=-65;scene.add(sun);
 const ocean=box(140,.8,140,C.water,.4);ocean.position.y=-1;scene.add(ocean);const island=box(116,1,116,C.grass2,.9);island.position.y=-.55;scene.add(island);const ground=box(110,.3,110,C.grass,.95);ground.position.y=-.02;scene.add(ground);
 for(const [,[x,z]] of Object.entries(POS)){const len=Math.hypot(x,z),p=box(3.1,.16,len,C.path,.96);p.position.set(x/2,.15,z/2);p.rotation.y=Math.atan2(x,z);scene.add(p)}
 const zones=[];for(const z of ZONES){const p=POS[z.id];if(!p)continue;const obj=special(z,...p);scene.add(obj);zones.push({z,x:p[0],zz:p[1],obj})}scene.add(home());
 for(let i=0;i<46;i++){const a=i*2.399,r=13+(i*13)%39,x=Math.sin(a)*r,z=Math.cos(a)*r;if(Math.hypot(x,z)<8||zones.some(q=>Math.hypot(x-q.x,z-q.zz)<7))continue;scene.add(tree(x,z,.65+(i%5)*.1))}for(let i=0;i<28;i++){const a=i*3.17,r=12+(i*9)%42;scene.add(rock(Math.sin(a)*r,Math.cos(a)*r,.35+(i%4)*.16))}obby(scene);
 const hero=avatar();hero.position.set(0,0,8);scene.add(hero);const pet=avatar(C.yellow,0xc98d61);pet.scale.setScalar(.3);pet.position.set(-1.6,0,9.5);scene.add(pet);
 const npcs=[[8,-5,C.green,0],[-8,6,C.pink,2],[16,9,C.orange,4],[-18,-4,C.purple,6]].map(([x,z,c,p])=>{const n=avatar(c);n.scale.setScalar(.82);n.position.set(x,0,z);n.userData.patrol={x,z,p};scene.add(n);return n});
 const coins=[];for(let i=0;i<30;i++){const a=i*1.83,r=9+(i*7)%43,m=cyl(.42,.42,.12,C.yellow,20);m.rotation.z=Math.PI/2;m.position.set(Math.sin(a)*r,1.1,Math.cos(a)*r);scene.add(m);coins.push({m,taken:false})}
 const clouds=[];for(let i=0;i<9;i++){const g=new THREE.Group();for(let j=0;j<4;j++){const q=new THREE.Mesh(new THREE.SphereGeometry(2+j*.3,12,8),mat(0xf0f2f1,1));q.position.set(j*2.1,Math.sin(j)*.4,0);g.add(q)}g.position.set(-60+i*16,24+(i%3)*4,-30+(i%4)*18);scene.add(g);clouds.push(g)}
 let near=null,jumpV=0,onGround=true,walk=0,t=0,stepClock=0,camYaw=.15,camPitch=.12,drag=null;
 function resize(){const r=canvas.getBoundingClientRect(),w=Math.max(1,r.width),h=Math.max(1,r.height);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}const ro=new ResizeObserver(resize);ro.observe(canvas);resize();
 canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;camYaw-=(e.clientX-drag.x)*.006;camPitch=Math.max(-.08,Math.min(.38,camPitch+(e.clientY-drag.y)*.004));drag.x=e.clientX;drag.y=e.clientY});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);
 function update(dt,input){t+=dt;const mag=Math.hypot(input.x,input.y),moving=mag>.05,speed=input.run?22:18;if(moving){const ang=Math.atan2(input.x,input.y)+camYaw-Math.PI,x=Math.sin(ang),z=Math.cos(ang);hero.position.x+=x*speed*dt;hero.position.z+=z*speed*dt;const d=Math.hypot(hero.position.x,hero.position.z);if(d>53){hero.position.x*=53/d;hero.position.z*=53/d}hero.rotation.y=Math.atan2(x,z);walk+=dt*(input.run?15:12);stepClock-=dt;if(stepClock<=0&&hero.position.y<.02){onStep?.();stepClock=.34}}else stepClock=0;
 if(input.jump&&hero.position.y<=.01){jumpV=9;onGround=false}jumpV-=23*dt;const py=hero.position.y;hero.position.y=Math.max(0,hero.position.y+jumpV*dt);if(hero.position.y===0&&py>0&&!onGround){onGround=true;jumpV=0;onLand?.()}else if(hero.position.y===0&&jumpV<0)jumpV=0;
 const u=hero.userData;if(moving){u.armL.rotation.x=Math.sin(walk)*.72;u.armR.rotation.x=-Math.sin(walk)*.72;u.legL.rotation.x=-Math.sin(walk)*.62;u.legR.rotation.x=Math.sin(walk)*.62;u.torso.position.y=2.55+Math.abs(Math.sin(walk))*0.06}else{u.armL.rotation.x*=.78;u.armR.rotation.x*=.78;u.legL.rotation.x*=.78;u.legR.rotation.x*=.78;u.torso.position.y=2.55+Math.sin(t*2)*.025}
 pet.position.lerp(new THREE.Vector3(hero.position.x-1.8*Math.sin(hero.rotation.y),0,hero.position.z-1.8*Math.cos(hero.rotation.y)),Math.min(1,dt*5.5));pet.rotation.y=hero.rotation.y;
 for(const q of coins){if(q.taken)continue;q.m.rotation.y+=dt*4;q.m.position.y=1.1+Math.sin(t*3+q.m.position.x)*.14;if(hero.position.distanceTo(q.m.position)<1.4){q.taken=true;q.m.visible=false;onCollect?.()}}
 scene.traverse(o=>{if(o.userData.pulse){const s=1+Math.sin(t*3+o.position.x)*.025;o.scale.setScalar(s)}if(o.userData.mover){const m=o.userData.mover;o.position[m.axis]=m.base[m.axis]+Math.sin(t*1.25+m.phase)*2}});npcs.forEach((n,i)=>{const p=n.userData.patrol,a=t*.25+p.p;n.position.x=p.x+Math.cos(a)*3;n.position.z=p.z+Math.sin(a)*3;n.rotation.y=-a+Math.PI/2;const q=n.userData;q.armL.rotation.x=Math.sin(t*5+i)*.35;q.armR.rotation.x=-q.armL.rotation.x;q.legL.rotation.x=-q.armL.rotation.x;q.legR.rotation.x=q.armL.rotation.x});clouds.forEach((c,i)=>{c.position.x+=dt*(.6+i*.03);if(c.position.x>75)c.position.x=-75});
 let n=null,best=999;for(const q of zones){const d=Math.hypot(hero.position.x-q.x,hero.position.z-q.zz);q.obj.traverse(o=>{if(o.userData.zoneSign)o.visible=d<11});if(d<5.5&&d<best){best=d;n=q.z}}if(Math.hypot(hero.position.x,hero.position.z)<4.8)n={id:'home',name:'Hero Home',icon:'🎒'};if(n?.id!==near?.id){near=n;onNearChange?.(near)}
 const dist=8.8,height=4.9,cp=Math.cos(camPitch),sp=Math.sin(camPitch),desired=new THREE.Vector3(hero.position.x+Math.sin(camYaw)*dist*cp,hero.position.y+height+sp*3,hero.position.z+Math.cos(camYaw)*dist*cp);camera.position.lerp(desired,1-Math.pow(.0008,dt));camera.lookAt(hero.position.x,hero.position.y+2.7,hero.position.z);renderer.render(scene,camera)}
 function setVisible(v){canvas.style.display=v?'block':'none';if(v)resize()}return{update,setVisible,getNear:()=>near,jump(){if(hero.position.y<=.01){jumpV=9;onGround=false}},dispose(){ro.disconnect();renderer.dispose()}}
}
