import {ZONES,MISSIONS,PETS,SKINS,HAIRS,OUTFITS,HATS,zoneMissions} from './data.js';
import {W,H,rr,text} from './art.js';
import {loadProgress,saveProgress,dailyFor,updateDaily,awardMission} from './progress.js';
import {sfx,musicStart,musicStop,musicTheme,speak} from './audio.js';
import {createGame} from './games.js';
import {createHub3D} from './hub3d.js';

const $=s=>document.querySelector(s),canvas=$('#game2d'),ctx=canvas.getContext('2d'),worldCanvas=$('#world3d');
const hud={stars:$('#stars'),coins:$('#coins'),gems:$('#gems'),level:$('#levelNo'),mission:$('#missionPill'),progress:$('#missionProgress'),objective:$('#objective'),hint:$('#hint'),toast:$('#toast'),touch:$('#touch'),a:$('#actionA'),b:$('#actionB')};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
let state=loadProgress();dailyFor(state);saveProgress(state);
function syncHud(){hud.stars.textContent=state.stars;hud.coins.textContent=Math.floor(state.coins);hud.gems.textContent=Math.floor(state.gems);hud.level.textContent=Math.min(50,Object.keys(state.completed).length+1);$('#musicBtn').textContent=state.settings.music?'🎵':'🚫';$('#sfxBtn').textContent=state.settings.sfx?'🔊':'🔇'}
function save(){saveProgress(state);syncHud()}
function toast(t){hud.toast.textContent=t;hud.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>hud.toast.classList.remove('show'),1400)}
function hint(t){hud.hint.textContent=t;hud.hint.classList.toggle('hidden',!t)}
function objective(t){hud.objective.textContent=t||'';hud.objective.classList.toggle('hidden',!t)}
function progress(v){hud.progress.style.width=clamp(v,0,100)+'%'}
let particles=[];function burst(x,y,e='⭐',n=12){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*10,vy:-2-Math.random()*6,life:45,e})}
function drawParticles(){for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.vy+=.25;p.life--;ctx.font='22px serif';ctx.fillText(p.e,p.x,p.y)}particles=particles.filter(p=>p.life>0)}
function rewardCoin(n=1){state.coins+=n;if(updateDaily(state,'coins'))toast('Daily challenge complete! +2 💎');save()}
function rewardGem(n=1){state.gems+=n;save()}
function fail(){if(!mission)return;state.fails[mission.id]=(state.fails[mission.id]||0)+1;save();if(state.fails[mission.id]===3){hint('✨ Look for the glowing or moving clue!');toast('Hint unlocked ✨')}}
function actions(a='✋',b='⬆️',visible=true){hud.touch.classList.toggle('hidden',!visible);hud.a.textContent=a;hud.b.textContent=b}

const keys={};addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(k==='e')actionA();if(k===' ')actionB()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
let stick={x:0,y:0,id:null};const stickEl=$('#stick'),knob=stickEl.querySelector('.stick-knob');
function setStick(e){const r=stickEl.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=r.width*.34,m=Math.hypot(dx,dy)||1,k=Math.min(1,max/m);stick.x=clamp(dx/max,-1,1);stick.y=clamp(dy/max,-1,1);knob.style.transform=`translate(${dx*k}px,${dy*k}px)`}
stickEl.onpointerdown=e=>{stick.id=e.pointerId;stickEl.setPointerCapture(e.pointerId);setStick(e)};stickEl.onpointermove=e=>{if(stick.id===e.pointerId)setStick(e)};function clearStick(e){if(stick.id===e.pointerId){stick={x:0,y:0,id:null};knob.style.transform=''}}stickEl.onpointerup=clearStick;stickEl.onpointercancel=clearStick;
hud.a.onpointerdown=e=>{e.preventDefault();actionA()};hud.b.onpointerdown=e=>{e.preventDefault();actionB()};
function controls(){return{x:clamp(stick.x+(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),-1,1),y:clamp(stick.y+(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0),-1,1)}}

let scene='hub',mission=null,game=null,last=performance.now(),time=0,jumpPulse=false,runPulse=false,near=null;
const ZONE_UNLOCK={castle:0,forest:0,snake:0,builder:0,hero:0,race:3,pirate:6,dino:9,brain:12,candy:15,caves:18,space:21,robot:24,ocean:27,volcano:30};
const hub=createHub3D({canvas:worldCanvas,ZONES,state,onNearChange:n=>{near=n;if(scene!=='hub')return;if(!n){hint('');hud.a.textContent='✋';return}if(n.id==='home'){hint('🎒 Hero Home');hud.a.textContent='🎒';return}const need=ZONE_UNLOCK[n.id]||0;if(state.stars<need){hint(`🔒 ${need-state.stars} more ⭐`);hud.a.textContent='🔒'}else{const list=zoneMissions(n.id),done=list.filter(m=>state.completed[m.id]).length;hint(`${n.icon} ${n.name} ${done}/${list.length}`);hud.a.textContent='🚪'}},onCollect:()=>{rewardCoin(1);sfx(state,760,.04)}});

function actionA(){if(scene==='hub'){if(!near)return;if(near.id==='home'){openWardrobe();return}const need=ZONE_UNLOCK[near.id]||0;if(state.stars<need){toast(`Earn ${need-state.stars} more stars to unlock ${near.name}! ⭐`);return}startNextInZone(near)}else game?.actionA?.()}
function actionB(){if(scene==='hub'){jumpPulse=true;runPulse=true;hub.jump();sfx(state,440,.04);setTimeout(()=>jumpPulse=false,80);setTimeout(()=>runPulse=false,550)}else game?.actionB?.()}
function startNextInZone(z){const list=zoneMissions(z.id),next=list.find(m=>!state.completed[m.id])||list[0];startMission(next)}
function startMission(m){mission=m;scene='mission';game=null;hub.setVisible(false);canvas.classList.remove('hidden-canvas');hud.mission.textContent=`${m.icon} ${m.title}`;objective(m.objective||m.title);progress(0);hint('');musicTheme(state,m.theme);game=createGame(m,env());game.reset();speak(state,m.objective||m.title);sfx(state,660,.08)}
function env(){return{ctx,state,controls,finish:finishMission,fail,sfx:(...a)=>sfx(state,...a),burst,text,rr,objective,progress,actions,toast,time:()=>time,rewardCoin,rewardGem,drawParticles,save}}
function finishMission(score=3){if(!mission||game?.done)return;if(game)game.done=true;const fresh=awardMission(state,mission,score);const skillMap={math:'maths',word:'reading',memory:'memory',pattern:'logic',logic:'logic',maze:'logic',builder:'creativity',science:'science',race:'coordination',platform:'coordination',snake:'coordination',hero:'coordination',boss:'logic',scavenge:'coordination',hidden:'logic',match:'logic'};const sk=skillMap[mission.type]||'logic';state.skills[sk]=(state.skills[sk]||0)+score;state.fails[mission.id]=0;if(fresh)updateDaily(state,mission.type==='builder'?'builder':'missions');updateDaily(state,'stars');save();progress(100);burst(W/2,H/2,'⭐',28);sfx(state,880,.25);setTimeout(()=>rewardModal(score,fresh),450)}
function rewardModal(score,fresh){const d=dailyFor(state);$('#modalBody').innerHTML=`<div class="reward-panel"><div class="big">${'⭐'.repeat(score)}</div><h1>Mission Complete!</h1><p>${fresh?`🪙 +${20+mission.id}${mission.id%5===0?' • 💎 +1':''}`:'🪙 +5 replay bonus'}</p>${mission.id%10===0?'<h2>👑 New Crown!</h2>':''}<div class="daily-card"><b>${d.icon} Daily Challenge</b><div>${d.label}</div><div>${Math.min(d.progress,d.goal)}/${d.goal}${d.claimed?' ✅':''}</div></div><button id="backIsland" class="primary">🏝️ Adventure Island</button> <button id="replay" class="secondary">↻ Play again</button></div>`;$('#modal').classList.remove('hidden');$('#backIsland').onclick=()=>{closeModal();goHub()};$('#replay').onclick=()=>{closeModal();startMission(mission)}}
function goHub(){scene='hub';mission=null;game=null;canvas.classList.add('hidden-canvas');hub.setVisible(true);hud.mission.textContent='Adventure Island';objective('Explore the island');progress(0);actions('✋','⬆️');hint('');musicTheme(state,'island')}

function openWardrobe(){const done=Object.keys(state.completed).length,petN=Math.min(PETS.length,1+Math.floor(done/7)),outN=Math.min(OUTFITS.length,2+Math.floor(done/8)),hatN=Math.min(HATS.length,1+Math.floor(done/10));$('#modalBody').innerHTML=`<h1>🎒 Hero Locker</h1><p>Choose a look. More items unlock as you play.</p><h3>Skin</h3><div class="wardrobe" id="skins">${SKINS.map((c,i)=>`<button data-i="${i}" class="${i===state.player.skin?'selected':''}" style="background:${c}">●</button>`).join('')}</div><h3>Hair</h3><div class="wardrobe" id="hairs">${HAIRS.map((c,i)=>`<button data-i="${i}" class="${i===state.player.hair?'selected':''}" style="background:${c}">●</button>`).join('')}</div><h3>Outfit</h3><div class="wardrobe" id="outfits">${OUTFITS.slice(0,outN).map((c,i)=>`<button data-i="${i}" class="${i===state.player.outfit?'selected':''}" style="background:${c}">👕</button>`).join('')}</div><h3>Hat</h3><div class="wardrobe" id="hats">${HATS.slice(0,hatN).map((h,i)=>`<button data-i="${i}" class="${i===state.player.hat?'selected':''}">${h||'🙂'}</button>`).join('')}</div><h3>Pet</h3><div class="wardrobe" id="pets">${PETS.slice(0,petN).map((p,i)=>`<button data-i="${i}" class="${i===state.player.pet?'selected':''}">${p}</button>`).join('')}</div>`;$('#modal').classList.remove('hidden');for(const [id,key] of [['skins','skin'],['hairs','hair'],['outfits','outfit'],['hats','hat'],['pets','pet']])$('#'+id).onclick=e=>{const b=e.target.closest('button');if(!b)return;state.player[key]=+b.dataset.i;save();openWardrobe()}}

canvas.onpointerdown=e=>{if(scene!=='mission'||!game)return;const p=canvasPos(e);game.down?.(p);canvas.setPointerCapture?.(e.pointerId)};canvas.onpointermove=e=>{if(scene==='mission'&&game&&e.buttons)game.move?.(canvasPos(e))};canvas.onpointerup=e=>{if(scene==='mission'&&game)game.up?.(canvasPos(e))};function canvasPos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
$('#homeBtn').onclick=goHub;$('#musicBtn').onclick=()=>{state.settings.music=!state.settings.music;if(state.settings.music)musicStart(state,mission?.theme||'island');else musicStop();save()};$('#sfxBtn').onclick=()=>{state.settings.sfx=!state.settings.sfx;save()};$('#parentBtn').onclick=openGate;$('#modalClose').onclick=closeModal;function closeModal(){$('#modal').classList.add('hidden')}
let gateDown={l:false,r:false},gateStart=0,gateRAF=0;function openGate(){$('#parentGate').classList.remove('hidden');gateDown={l:false,r:false};gateStart=0;$('#gateProgress').style.width='0'}$('#gateBack').onclick=()=>$('#parentGate').classList.add('hidden');function gatePress(side,on){gateDown[side]=on;$('#gate'+(side==='l'?'L':'R')).classList.toggle('down',on);if(gateDown.l&&gateDown.r&&!gateStart){gateStart=performance.now();tickGate()}if(!gateDown.l||!gateDown.r){gateStart=0;$('#gateProgress').style.width='0';cancelAnimationFrame(gateRAF)}}function tickGate(){if(!gateStart)return;const p=Math.min(1,(performance.now()-gateStart)/3000);$('#gateProgress').style.width=p*100+'%';if(p>=1){$('#parentGate').classList.add('hidden');openParent();gateStart=0;return}gateRAF=requestAnimationFrame(tickGate)}for(const [id,s] of [['gateL','l'],['gateR','r']]){const b=$('#'+id);b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);gatePress(s,true)};b.onpointerup=()=>gatePress(s,false);b.onpointercancel=()=>gatePress(s,false)}
function openParent(){const completed=Object.keys(state.completed).length,d=dailyFor(state);$('#modalBody').innerHTML=`<h1>Parent Dashboard</h1><div class="parent-grid"><div class="stat"><b>${Math.floor(state.playSeconds/60)}</b>minutes</div><div class="stat"><b>${completed}/50</b>missions</div><div class="stat"><b>${state.stars}</b>stars</div><div class="stat"><b>${state.coins}</b>coins</div><div class="stat"><b>${state.gems}</b>gems</div><div class="stat"><b>${state.crowns}</b>crowns</div></div><h3>Skills practised</h3><div class="parent-grid">${Object.entries(state.skills).map(([k,v])=>`<div class="stat"><b>${v}</b>${k}</div>`).join('')}</div><div class="daily-card"><b>${d.icon} Optional daily challenge</b><div>${d.label}: ${Math.min(d.progress,d.goal)}/${d.goal}${d.claimed?' ✅':''}</div><small>No streak pressure.</small></div><h3>Safety</h3><p>No chat, strangers, ads, purchases or personal information required. Progress stays on this device.</p><button id="resetProgress" class="danger">Reset progress</button>`;$('#modal').classList.remove('hidden');$('#resetProgress').onclick=()=>{if(confirm('Reset all BrainQuest progress on this device?')){localStorage.removeItem('brainquestAdventureV11');location.reload()}}}

function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;time+=dt;if(scene==='hub'){const c=controls();hub.update(dt,{x:c.x,y:c.y,jump:jumpPulse,run:runPulse})}else if(game){game.elapsed+=dt;game.update(dt);game.draw()}requestAnimationFrame(loop)}
setInterval(()=>{state.playSeconds++;if(state.playSeconds%15===0)save()},1000);syncHud();actions('✋','⬆️');objective('Explore the island');canvas.classList.add('hidden-canvas');hub.setVisible(true);musicStart(state,'island');requestAnimationFrame(loop);
