import {ZONES,MISSIONS,PETS,SKINS,HAIRS,OUTFITS,HATS,zoneMissions} from './data.js';
import {W,H,rr,text,drawHubScene,drawHero,drawPet} from './art.js';
import {loadProgress,saveProgress,dailyFor,updateDaily,awardMission} from './progress.js';
import {sfx,musicStart,musicStop,musicTheme,speak} from './audio.js';
import {createGame} from './minigames.js';

const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s);
const hud={stars:$('#stars'),coins:$('#coins'),gems:$('#gems'),level:$('#levelNo'),mission:$('#missionPill'),progress:$('#missionProgress'),objective:$('#objective'),hint:$('#hint'),toast:$('#toast'),touch:$('#touch'),a:$('#actionA'),b:$('#actionB')};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
let state=loadProgress();dailyFor(state);saveProgress(state);
function syncHud(){hud.stars.textContent=state.stars;hud.coins.textContent=Math.floor(state.coins);hud.gems.textContent=Math.floor(state.gems);hud.level.textContent=Math.min(50,Object.keys(state.completed).length+1);$('#musicBtn').textContent=state.settings.music?'🎵':'🚫';$('#sfxBtn').textContent=state.settings.sfx?'🔊':'🔇'}
function save(){saveProgress(state);syncHud()}
function toast(t){hud.toast.textContent=t;hud.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>hud.toast.classList.remove('show'),1400)}
function hint(t){hud.hint.textContent=t;hud.hint.classList.toggle('hidden',!t)}
function objective(t){hud.objective.textContent=t||'';hud.objective.classList.toggle('hidden',!t)}
function progress(v){hud.progress.style.width=clamp(v,0,100)+'%'}
let particles=[];function burst(x,y,e='⭐',n=12){for(let i=0;i<n;i++)particles.push({x,y,vx:rnd(-5,5),vy:rnd(-8,-2),life:45,e})}
function drawParticles(){for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.vy+=.25;p.life--;ctx.font='22px serif';ctx.fillText(p.e,p.x,p.y)}particles=particles.filter(p=>p.life>0)}
function rewardCoin(n=1){state.coins+=n;if(updateDaily(state,'coins'))toast('Daily challenge complete! +2 💎');save()}
function rewardGem(n=1){state.gems+=n;save()}
function fail(){if(!mission)return;state.fails[mission.id]=(state.fails[mission.id]||0)+1;save();if(state.fails[mission.id]===3){hint('✨ Hint unlocked — look for glowing or moving objects!');toast('A little hint appeared ✨')}}
function actions(a='✋',b='⬆️',visible=true){hud.touch.classList.toggle('hidden',!visible);hud.a.textContent=a;hud.b.textContent=b}

const keys={};addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(k==='e')actionA();if(k===' ')actionB()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
let stick={x:0,y:0,id:null};const stickEl=$('#stick'),knob=stickEl.querySelector('.stick-knob');
function setStick(e){const r=stickEl.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=r.width*.33,m=Math.hypot(dx,dy)||1,k=Math.min(1,max/m);stick.x=clamp(dx/max,-1,1);stick.y=clamp(dy/max,-1,1);knob.style.transform=`translate(${dx*k}px,${dy*k}px)`}
stickEl.onpointerdown=e=>{stick.id=e.pointerId;stickEl.setPointerCapture(e.pointerId);setStick(e)};stickEl.onpointermove=e=>{if(stick.id===e.pointerId)setStick(e)};function clearStick(e){if(stick.id===e.pointerId){stick={x:0,y:0,id:null};knob.style.transform=''}}stickEl.onpointerup=clearStick;stickEl.onpointercancel=clearStick;
hud.a.onpointerdown=e=>{e.preventDefault();actionA()};hud.b.onpointerdown=e=>{e.preventDefault();actionB()};
function controls(){return{x:clamp(stick.x+(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),-1,1),y:clamp(stick.y+(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0),-1,1)}}

let scene='hub',mission=null,game=null,last=performance.now(),time=0;
const player={x:640,y:405,dir:1,jump:0,run:0,swim:false};
const clouds=Array.from({length:9},()=>({x:rnd(0,W),y:rnd(60,250),s:rnd(.65,1.5),v:rnd(7,18)}));
const birds=Array.from({length:6},()=>({x:rnd(0,W),y:rnd(90,260),v:rnd(16,30)}));
const hubCoins=Array.from({length:20},(_,i)=>({x:90+(i*177)%1100,y:130+(i*91)%500,taken:false}));
const npcs=[
 {x:255,y:250,dir:1,name:'Mia',icon:'💡',line:'Puzzle Castle has secret doors!'},
 {x:725,y:210,dir:-1,name:'Nova',icon:'🚀',line:'I saw a shiny portal near Space World!'},
 {x:940,y:520,dir:-1,name:'Rex',icon:'🏁',line:'Collect stars before the next checkpoint!'},
 {x:470,y:500,dir:1,name:'Tobi',icon:'🧱',line:'Try building a bridge all the way across.'}
];
let surprise={active:false,x:0,y:0,timer:rnd(20,35),opened:false,type:'chest'};let dayPhase=0;
function spawnSurprise(){surprise={active:true,x:rnd(150,1130),y:rnd(160,620),timer:rnd(35,55),opened:false,type:Math.random()<.5?'chest':'rainbow'};toast(surprise.type==='chest'?'A treasure chest appeared! 🎁':'A rainbow surprise appeared! 🌈')}
function updateHub(dt){const c=controls(),speed=185*(1+player.run);player.x=clamp(player.x+c.x*speed*dt,35,W-35);player.y=clamp(player.y+c.y*speed*dt,95,H-35);if(c.x)player.dir=Math.sign(c.x);player.jump=Math.max(0,player.jump-130*dt);player.run=Math.max(0,player.run-dt);player.swim=player.y<120||player.y>650;dayPhase=(dayPhase+dt*.01)%1;for(const cl of clouds){cl.x+=cl.v*dt;if(cl.x>W+120)cl.x=-140}for(const b of birds){b.x+=b.v*dt;if(b.x>W+40)b.x=-60}for(const n of npcs){n.x+=Math.sin(time*.8+n.y)*4*dt;n.dir=Math.sin(time+n.y)>0?1:-1}
 for(const c of hubCoins)if(!c.taken&&Math.hypot(player.x-c.x,player.y-c.y)<28){c.taken=true;rewardCoin(1);sfx(state,760,.05);burst(c.x,c.y,'✨',5)}
 surprise.timer-=dt;if(!surprise.active&&surprise.timer<=0)spawnSurprise();if(surprise.active&&Math.hypot(player.x-surprise.x,player.y-surprise.y)<65){hint(surprise.type==='chest'?'🎁 Open surprise chest!':'🌈 Follow the rainbow!');hud.a.textContent='🎁';return}
 const npc=npcs.find(n=>Math.hypot(player.x-n.x,player.y-n.y)<70);if(npc){hint(`🙂 ${npc.name} • ✋`);hud.a.textContent='💬';return}
 const z=ZONES.find(z=>dist(player,z)<78);if(z){const list=zoneMissions(z.id),done=list.filter(m=>state.completed[m.id]).length;hint(`${z.icon} ${z.name} ${done}/${list.length} • ✋`);hud.a.textContent='🚪';return}
 if(Math.hypot(player.x-640,player.y-405)<75){hint('🎒 Hero Locker • ✋');hud.a.textContent='🎒';return}hint('');hud.a.textContent='✋'}
function drawHub(){drawHubScene(ctx,time,clouds,birds);const darkness=Math.max(0,Math.sin(dayPhase*Math.PI*2)*.12);if(darkness>0){ctx.fillStyle=`rgba(24,30,80,${darkness})`;ctx.fillRect(0,0,W,H)}for(const c of hubCoins)if(!c.taken){ctx.font='25px serif';ctx.fillText('🪙',c.x,c.y+Math.sin(time*5+c.x)*4)}for(const n of npcs){drawHero(ctx,n.x,n.y,state,time,n.dir,.62,0,false);ctx.font='23px serif';ctx.fillText(n.icon,n.x,n.y-48+Math.sin(time*3)*3)}if(surprise.active){ctx.font=surprise.type==='chest'?'52px':'70px';ctx.fillText(surprise.type==='chest'?'🎁':'🌈',surprise.x,surprise.y+Math.sin(time*5)*5);ctx.strokeStyle='rgba(255,255,255,.7)';ctx.lineWidth=4;ctx.beginPath();ctx.arc(surprise.x,surprise.y,60+Math.sin(time*4)*5,0,7);ctx.stroke()}ctx.fillStyle='#fff3c9';rr(ctx,590,367,100,78,20,'#fff3c9','#fff');ctx.font='40px serif';ctx.fillText('🎒',640,407);drawPet(ctx,player.x,player.y,state,time,player.dir);drawHero(ctx,player.x,player.y,state,time,player.dir,1,player.jump,false);if(player.swim){ctx.strokeStyle='rgba(255,255,255,.6)';ctx.lineWidth=4;ctx.beginPath();ctx.arc(player.x,player.y+22,35,0,Math.PI);ctx.stroke()}drawParticles()}
function hubAction(){if(surprise.active&&Math.hypot(player.x-surprise.x,player.y-surprise.y)<70){surprise.active=false;state.coins+=20;state.gems+=1;updateDaily(state,'treasure');save();sfx(state,940,.18);burst(surprise.x,surprise.y,'✨',18);toast('+20 🪙  +1 💎');return}const npc=npcs.find(n=>Math.hypot(player.x-n.x,player.y-n.y)<75);if(npc){toast(npc.line);speak(state,npc.line);return}const z=ZONES.find(z=>dist(player,z)<88);if(z){startNextInZone(z);return}if(Math.hypot(player.x-640,player.y-405)<85)openWardrobe()}
function actionA(){if(scene==='hub')hubAction();else game?.actionA?.()}
function actionB(){if(scene==='hub'){player.jump=34;player.run=.6;sfx(state,440,.04)}else game?.actionB?.()}
function startNextInZone(z){const list=zoneMissions(z.id),next=list.find(m=>!state.completed[m.id])||list[0];startMission(next)}
function startMission(m){mission=m;scene='mission';hud.mission.textContent=`${m.icon} ${m.title}`;objective(m.objective);progress(0);hint('');musicTheme(state,m.theme);game=createGame(m,env());game.reset();speak(state,m.objective||m.title);sfx(state,660,.08)}
function env(){return{ctx,state,controls,finish:finishMission,fail,sfx:(...a)=>sfx(state,...a),burst,text,rr,objective,progress,actions,toast,time:()=>time,rewardCoin,rewardGem,drawParticles,save}}
function finishMission(score=3){if(!mission||game?.done)return;if(game)game.done=true;const fresh=awardMission(state,mission,score);const skillMap={math:'maths',word:'reading',memory:'memory',pattern:'logic',logic:'logic',maze:'logic',builder:'creativity',science:'science',race:'coordination',platform:'coordination',snake:'coordination',hero:'coordination',boss:'logic',scavenge:'coordination',hidden:'logic',match:'logic'};const sk=skillMap[mission.type]||'logic';state.skills[sk]=(state.skills[sk]||0)+score;state.fails[mission.id]=0;if(fresh)updateDaily(state,mission.type==='builder'?'builder':'missions');updateDaily(state,'stars');save();progress(100);burst(W/2,H/2,'⭐',28);sfx(state,880,.25);setTimeout(()=>rewardModal(score,fresh),500)}
function rewardModal(score,fresh){const d=dailyFor(state);$('#modalBody').innerHTML=`<div class="reward-panel"><div class="big">${'⭐'.repeat(score)}</div><h1>Mission Complete!</h1><p>${fresh?`🪙 +${20+mission.id}${mission.id%5===0?' • 💎 +1':''}`:'🪙 +5 replay bonus'}</p>${mission.id%10===0?'<h2>👑 New Crown!</h2>':''}<div class="daily-card"><b>${d.icon} Daily Challenge</b><div>${d.label}</div><div>${Math.min(d.progress,d.goal)}/${d.goal}${d.claimed?' ✅':''}</div></div><button id="backIsland" class="primary">🏝️ Adventure Island</button> <button id="replay" class="secondary">↻ Play again</button></div>`;$('#modal').classList.remove('hidden');$('#backIsland').onclick=()=>{closeModal();goHub()};$('#replay').onclick=()=>{closeModal();startMission(mission)}}
function goHub(){scene='hub';mission=null;game=null;hud.mission.textContent='Adventure Island';objective('Explore, collect and discover!');progress(0);actions('✋','⬆️');hint('');musicTheme(state,'island');player.x=640;player.y=405}

function openWardrobe(){const done=Object.keys(state.completed).length,petN=Math.min(PETS.length,1+Math.floor(done/7)),outN=Math.min(OUTFITS.length,2+Math.floor(done/8)),hatN=Math.min(HATS.length,1+Math.floor(done/10));$('#modalBody').innerHTML=`<h1>🎒 Hero Locker</h1><p>Customise your Adventure Island hero. More items unlock by playing.</p><h3>Skin</h3><div class="wardrobe" id="skins">${SKINS.map((c,i)=>`<button data-i="${i}" class="${i===state.player.skin?'selected':''}" style="background:${c}">●</button>`).join('')}</div><h3>Hair</h3><div class="wardrobe" id="hairs">${HAIRS.map((c,i)=>`<button data-i="${i}" class="${i===state.player.hair?'selected':''}" style="background:${c}">●</button>`).join('')}</div><h3>Outfit</h3><div class="wardrobe" id="outfits">${OUTFITS.slice(0,outN).map((c,i)=>`<button data-i="${i}" class="${i===state.player.outfit?'selected':''}" style="background:${c}">👕</button>`).join('')}</div><h3>Hat</h3><div class="wardrobe" id="hats">${HATS.slice(0,hatN).map((h,i)=>`<button data-i="${i}" class="${i===state.player.hat?'selected':''}">${h||'🙂'}</button>`).join('')}</div><h3>Pet</h3><div class="wardrobe" id="pets">${PETS.slice(0,petN).map((p,i)=>`<button data-i="${i}" class="${i===state.player.pet?'selected':''}">${p}</button>`).join('')}</div>`;$('#modal').classList.remove('hidden');for(const [id,key] of [['skins','skin'],['hairs','hair'],['outfits','outfit'],['hats','hat'],['pets','pet']])$('#'+id).onclick=e=>{const b=e.target.closest('button');if(!b)return;state.player[key]=+b.dataset.i;save();openWardrobe()}}

canvas.onpointerdown=e=>{if(scene!=='mission'||!game)return;const p=canvasPos(e);game.down?.(p);canvas.setPointerCapture?.(e.pointerId)};canvas.onpointermove=e=>{if(scene==='mission'&&game&&e.buttons)game.move?.(canvasPos(e))};canvas.onpointerup=e=>{if(scene==='mission'&&game)game.up?.(canvasPos(e))};function canvasPos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
$('#homeBtn').onclick=goHub;$('#musicBtn').onclick=()=>{state.settings.music=!state.settings.music;if(state.settings.music)musicStart(state,mission?.theme||'island');else musicStop();save()};$('#sfxBtn').onclick=()=>{state.settings.sfx=!state.settings.sfx;save()};$('#parentBtn').onclick=openGate;$('#modalClose').onclick=closeModal;function closeModal(){$('#modal').classList.add('hidden')}
let gateDown={l:false,r:false},gateStart=0,gateRAF=0;function openGate(){$('#parentGate').classList.remove('hidden');gateDown={l:false,r:false};gateStart=0;$('#gateProgress').style.width='0'}$('#gateBack').onclick=()=>$('#parentGate').classList.add('hidden');function gatePress(side,on){gateDown[side]=on;$('#gate'+(side==='l'?'L':'R')).classList.toggle('down',on);if(gateDown.l&&gateDown.r&&!gateStart){gateStart=performance.now();tickGate()}if(!gateDown.l||!gateDown.r){gateStart=0;$('#gateProgress').style.width='0';cancelAnimationFrame(gateRAF)}}function tickGate(){if(!gateStart)return;const p=Math.min(1,(performance.now()-gateStart)/3000);$('#gateProgress').style.width=p*100+'%';if(p>=1){$('#parentGate').classList.add('hidden');openParent();gateStart=0;return}gateRAF=requestAnimationFrame(tickGate)}for(const [id,s] of [['gateL','l'],['gateR','r']]){const b=$('#'+id);b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);gatePress(s,true)};b.onpointerup=()=>gatePress(s,false);b.onpointercancel=()=>gatePress(s,false)}
function openParent(){const completed=Object.keys(state.completed).length,d=dailyFor(state);$('#modalBody').innerHTML=`<h1>Parent Dashboard</h1><div class="parent-grid"><div class="stat"><b>${Math.floor(state.playSeconds/60)}</b>minutes played</div><div class="stat"><b>${completed}/50</b>missions completed</div><div class="stat"><b>${state.stars}</b>stars</div><div class="stat"><b>${state.coins}</b>coins</div><div class="stat"><b>${state.gems}</b>gems</div><div class="stat"><b>${state.crowns}</b>crowns</div></div><h3>Skills practised</h3><div class="parent-grid">${Object.entries(state.skills).map(([k,v])=>`<div class="stat"><b>${v}</b>${k}</div>`).join('')}</div><div class="daily-card"><b>${d.icon} Optional daily challenge</b><div>${d.label}: ${Math.min(d.progress,d.goal)}/${d.goal}${d.claimed?' ✅':''}</div><small>No streaks or pressure to return.</small></div><h3>Audio</h3><div class="mini-row"><span class="badge">Music ${state.settings.music?'ON':'OFF'}</span><span class="badge">Sounds ${state.settings.sfx?'ON':'OFF'}</span></div><h3>Safety</h3><p>No open chat, no strangers, no ads, no purchases, no gambling, and no personal information is required. Progress stays on this device.</p><button id="resetProgress" class="danger">Reset progress</button>`;$('#modal').classList.remove('hidden');$('#resetProgress').onclick=()=>{if(confirm('Reset all BrainQuest progress on this device?')){localStorage.removeItem('brainquestAdventureV11');location.reload()}}}

function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;time+=dt;if(scene==='hub'){updateHub(dt);drawHub()}else if(game){game.elapsed+=dt;game.update(dt);game.draw()}requestAnimationFrame(loop)}
setInterval(()=>{state.playSeconds++;if(state.playSeconds%15===0)save()},1000);syncHud();actions('✋','⬆️');objective('Explore, collect and discover!');musicStart(state,'island');requestAnimationFrame(loop);
