import {ZONES,MISSIONS,PETS,OUTFITS,zoneMissions} from './data.js';

const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const W=1280,H=720,$=s=>document.querySelector(s);
const hud={stars:$('#stars'),coins:$('#coins'),gems:$('#gems'),mission:$('#missionPill'),hint:$('#hint'),toast:$('#toast'),touch:$('#touch'),a:$('#actionA'),b:$('#actionB')};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),ri=(a,b)=>Math.floor(rnd(a,b+1)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),pick=a=>a[Math.floor(Math.random()*a.length)],shuffle=a=>[...a].sort(()=>Math.random()-.5);

const DEFAULT={coins:0,gems:0,stars:0,completed:{},best:{},playSeconds:0,settings:{music:true,sfx:true},player:{outfit:0,pet:0},skills:{logic:0,memory:0,maths:0,reading:0,coordination:0,science:0,creativity:0}};
let state=load();
function load(){try{return merge(DEFAULT,JSON.parse(localStorage.getItem('brainquestAdventureV10')||'{}'))}catch{return structuredClone(DEFAULT)}}
function merge(a,b){const o={...a,...b};for(const k of Object.keys(a))if(a[k]&&typeof a[k]==='object'&&!Array.isArray(a[k]))o[k]={...a[k],...(b?.[k]||{})};return o}
function save(){localStorage.setItem('brainquestAdventureV10',JSON.stringify(state));syncHud()}
function syncHud(){hud.stars.textContent=state.stars;hud.coins.textContent=state.coins;hud.gems.textContent=state.gems}

let audioCtx=null,musicTimer=null;
function ac(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();return audioCtx}
function tone(f=520,d=.08,type='sine',vol=.05){if(!state.settings.sfx)return;try{const a=ac(),o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=f;g.gain.value=vol;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.stop(a.currentTime+d)}catch{}}
function startMusic(){if(!state.settings.music||musicTimer)return;let i=0;const notes=[262,330,392,523,392,330,294,392];musicTimer=setInterval(()=>{tone(notes[i++%notes.length],.18,'triangle',.012)},330)}
function stopMusic(){clearInterval(musicTimer);musicTimer=null}
function speak(t){if(!state.settings.sfx||!('speechSynthesis'in window))return;try{window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.rate=.95;u.pitch=1.18;window.speechSynthesis.speak(u)}catch{}}
function toast(t){hud.toast.textContent=t;hud.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>hud.toast.classList.remove('show'),1200)}
function hint(t){hud.hint.textContent=t;hud.hint.classList.toggle('hidden',!t)}

const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase()))e.preventDefault();if(e.key===' ')actionB();if(e.key.toLowerCase()==='e')actionA()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
let stick={x:0,y:0,id:null};
const stickEl=$('#stick'),knob=stickEl.querySelector('.stick-knob');
function setStick(e){const r=stickEl.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,m=Math.hypot(dx,dy)||1,max=r.width*.32,k=Math.min(1,max/m);stick.x=clamp(dx/max,-1,1);stick.y=clamp(dy/max,-1,1);knob.style.transform=`translate(${dx*k}px,${dy*k}px)`}
stickEl.onpointerdown=e=>{stick.id=e.pointerId;stickEl.setPointerCapture(e.pointerId);setStick(e)};stickEl.onpointermove=e=>{if(stick.id===e.pointerId)setStick(e)};function resetStick(e){if(stick.id===e.pointerId){stick={x:0,y:0,id:null};knob.style.transform=''}}stickEl.onpointerup=resetStick;stickEl.onpointercancel=resetStick;
hud.a.onpointerdown=e=>{e.preventDefault();actionA()};hud.b.onpointerdown=e=>{e.preventDefault();actionB()};

let scene='hub',mission=null,game=null,last=performance.now(),time=0,particles=[];
const player={x:640,y:410,vx:0,vy:0,r:23,dir:1,run:0};
function controls(){return{x:clamp(stick.x+(keys['d']||keys['arrowright']?1:0)-(keys['a']||keys['arrowleft']?1:0),-1,1),y:clamp(stick.y+(keys['s']||keys['arrowdown']?1:0)-(keys['w']||keys['arrowup']?1:0),-1,1)}}
function actionA(){if(scene==='hub')hubAction();else game?.actionA?.()}
function actionB(){if(scene==='hub'){player.run=.35;setTimeout(()=>player.run=0,400)}else game?.actionB?.()}
function showTouch(a='⚡',b='⬆️',visible=true){hud.touch.classList.toggle('hidden',!visible);hud.a.textContent=a;hud.b.textContent=b}

function rr(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function txt(t,x,y,size=28,align='center',color='#fff'){ctx.font=`900 ${size}px system-ui`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillStyle=color;ctx.fillText(t,x,y)}
function burst(x,y,emoji='⭐',n=12){for(let i=0;i<n;i++)particles.push({x,y,vx:rnd(-5,5),vy:rnd(-8,-2),life:45,e:emoji})}
function drawParticles(){particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.25;p.life--;ctx.font='22px serif';ctx.fillText(p.e,p.x,p.y)});particles=particles.filter(p=>p.life>0)}
function worldBg(theme='island'){const palettes={island:['#55dbff','#8fe37e'],forest:['#53d6ff','#69d16f'],castle:['#73cfff','#a78bfa'],space:['#17174a','#5b4bcf'],dino:['#63d5f0','#7ccf67'],robot:['#6abbd0','#7182aa'],ocean:['#1aaee6','#42dfd0'],road:['#67d5ff','#8dd37a'],builder:['#79d7ff','#d9b078'],academy:['#6fd4ff','#ff8ca8'],candy:['#79dcff','#ff9dd5'],grass:['#5bd9ff','#7bd46d'],cave:['#26354e','#6c4f92'],lab:['#65d6f7','#8b70ff'],volcano:['#493751','#e76448'],fantasy:['#7168e8','#ef8ac4'],river:['#5bd4f4','#77d06e']};let p=palettes[theme]||palettes.island;const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,p[0]);g.addColorStop(1,p[1]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function drawPlayer(x=player.x,y=player.y,scale=1){ctx.save();ctx.translate(x,y);ctx.scale(scale*(player.dir||1),scale);ctx.shadowColor='rgba(10,20,60,.25)';ctx.shadowBlur=12;ctx.fillStyle='#26315e';ctx.beginPath();ctx.ellipse(0,27,23,9,0,0,7);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle=OUTFITS[state.player.outfit%OUTFITS.length]==='🟥'?'#ef4d67':OUTFITS[state.player.outfit%OUTFITS.length]==='🟩'?'#43c77a':OUTFITS[state.player.outfit%OUTFITS.length]==='🟪'?'#865be8':OUTFITS[state.player.outfit%OUTFITS.length]==='🟨'?'#f1c84b':'#3f72e8';rr(-18,-2,36,42,13,ctx.fillStyle);ctx.fillStyle='#f3b37c';ctx.beginPath();ctx.arc(0,-18,18,0,7);ctx.fill();ctx.fillStyle='#3a2b35';ctx.beginPath();ctx.arc(0,-25,18,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-6,-18,3,0,7);ctx.arc(6,-18,3,0,7);ctx.fill();ctx.restore()}
function drawPet(){const e=PETS[state.player.pet%PETS.length];ctx.font='36px serif';ctx.textAlign='center';ctx.fillText(e,player.x-38*player.dir,player.y+24+Math.sin(time*4)*3)}

const clouds=Array.from({length:8},()=>({x:rnd(0,W),y:rnd(65,280),s:rnd(.7,1.5),v:rnd(4,10)}));
const butterflies=Array.from({length:10},()=>({x:rnd(0,W),y:rnd(150,650),a:rnd(0,6)}));
const hubCoins=Array.from({length:18},(_,i)=>({x:80+(i*173)%1120,y:120+(i*97)%500,taken:false}));
function updateHub(dt){const c=controls(),speed=190*(1+player.run);player.vx=c.x*speed;player.vy=c.y*speed;player.x=clamp(player.x+player.vx*dt,35,W-35);player.y=clamp(player.y+player.vy*dt,95,H-35);if(c.x)player.dir=Math.sign(c.x);for(const z of ZONES){if(dist(player,z)<76){hint(`${z.icon} ${z.name}  •  ⚡`);hud.a.textContent='🚪';return}}if(Math.hypot(player.x-640,player.y-420)<70){hint('🎒 Change hero & pet  •  ⚡');hud.a.textContent='🎒';return}hint('');hud.a.textContent='⚡';for(const c of hubCoins)if(!c.taken&&Math.hypot(player.x-c.x,player.y-c.y)<28){c.taken=true;state.coins++;tone(760,.05);burst(c.x,c.y,'✨',5);save()}}
function hubAction(){const z=ZONES.find(z=>dist(player,z)<88);if(z){startNextInZone(z);return}if(Math.hypot(player.x-640,player.y-420)<85)openWardrobe()}
function drawHub(){worldBg('island');ctx.fillStyle='#2bbde5';ctx.fillRect(0,0,W,92);ctx.globalAlpha=.32;for(let x=(time*40)%80-80;x<W;x+=80){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x,75,28,0,Math.PI);ctx.fill()}ctx.globalAlpha=1;clouds.forEach(c=>{c.x+=c.v*.016;if(c.x>W+100)c.x=-130;ctx.globalAlpha=.75;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(c.x,c.y,30*c.s,0,7);ctx.arc(c.x+38*c.s,c.y+5,24*c.s,0,7);ctx.arc(c.x-33*c.s,c.y+9,20*c.s,0,7);ctx.fill()});ctx.globalAlpha=1;ctx.fillStyle='#6acb69';ctx.fillRect(0,92,W,H-92);ctx.fillStyle='#5ab85b';for(let i=0;i<30;i++){ctx.beginPath();ctx.arc((i*97)%W,110+(i*73)%(H-140),8+(i%4)*3,0,7);ctx.fill()}ctx.strokeStyle='rgba(255,255,255,.45)';ctx.lineWidth=18;ctx.setLineDash([4,22]);ctx.beginPath();ctx.moveTo(640,410);ZONES.forEach(z=>ctx.lineTo(z.x,z.y));ctx.stroke();ctx.setLineDash([]);ZONES.forEach((z,i)=>{const pulse=1+Math.sin(time*2+i)*.04;ctx.save();ctx.translate(z.x,z.y);ctx.scale(pulse,pulse);ctx.globalAlpha=.2;ctx.fillStyle=z.color;ctx.beginPath();ctx.arc(0,0,68,0,7);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle=z.color;ctx.beginPath();ctx.arc(0,0,48,0,7);ctx.fill();ctx.lineWidth=5;ctx.strokeStyle='#fff';ctx.stroke();ctx.font='44px serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(z.icon,0,-2);const count=zoneMissions(z.id).filter(m=>state.completed[m.id]).length,tot=zoneMissions(z.id).length;txt(`${count}/${tot}`,0,58,14);ctx.restore()});hubCoins.forEach(c=>{if(!c.taken){ctx.font='25px serif';ctx.fillText('🪙',c.x,c.y+Math.sin(time*5+c.x)*4)}});butterflies.forEach(b=>{b.a+=.02;b.x+=Math.cos(b.a)*.25;b.y+=Math.sin(b.a*1.3)*.18;ctx.font='18px serif';ctx.fillText('🦋',b.x,b.y)});ctx.fillStyle='#fff3c9';rr(585,372,110,88,24,'#fff3c9','#fff');txt('🎒',640,410,44);drawPet();drawPlayer();drawParticles()}
function startNextInZone(z){const list=zoneMissions(z.id),next=list.find(m=>!state.completed[m.id])||list[0];startMission(next)}

function openWardrobe(){const unlockedPets=Math.min(PETS.length,1+Math.floor(Object.keys(state.completed).length/7)),unlockedOutfits=Math.min(OUTFITS.length,1+Math.floor(Object.keys(state.completed).length/10));$('#modalBody').innerHTML=`<h1>🎒 Hero Locker</h1><h3>Outfits</h3><div class="wardrobe" id="outfits">${OUTFITS.slice(0,unlockedOutfits).map((o,i)=>`<button data-i="${i}" class="${i===state.player.outfit?'selected':''}">${o}</button>`).join('')}</div><h3>Pets</h3><div class="wardrobe" id="pets">${PETS.slice(0,unlockedPets).map((o,i)=>`<button data-i="${i}" class="${i===state.player.pet?'selected':''}">${o}</button>`).join('')}</div><p>More unlock automatically as missions are completed.</p>`;$('#modal').classList.remove('hidden');$('#outfits').onclick=e=>{const b=e.target.closest('button');if(b){state.player.outfit=+b.dataset.i;save();openWardrobe()}};$('#pets').onclick=e=>{const b=e.target.closest('button');if(b){state.player.pet=+b.dataset.i;save();openWardrobe()}}}

function startMission(m){mission=m;scene='mission';hud.mission.textContent=`${m.icon} ${m.title}`;hint('');showTouch();game=createGame(m);game.reset();speak(game.voice||m.title);tone(660,.1)}
function finishMission(score=3){if(!mission)return;const was=!!state.completed[mission.id];state.completed[mission.id]=true;state.best[mission.id]=Math.max(state.best[mission.id]||0,score);if(!was){state.stars+=score;state.coins+=25+mission.id;state.gems+=(mission.id%5===0?1:0)}else state.coins+=5;skillUp(mission.type,score);save();burst(W/2,H/2,'⭐',25);tone(880,.3);setTimeout(()=>rewardModal(score),450)}
function skillUp(type,s){const map={math:'maths',word:'reading',memory:'memory',pattern:'logic',logic:'logic',maze:'logic',builder:'creativity',science:'science',race:'coordination',platform:'coordination',snake:'coordination',hero:'coordination',boss:'logic',scavenge:'coordination',hidden:'logic',match:'logic'};const k=map[type]||'logic';state.skills[k]=(state.skills[k]||0)+s;save()}
function rewardModal(score){$('#modalBody').innerHTML=`<div class="reward-panel"><div class="big">${'⭐'.repeat(score)}</div><h1>Mission Complete!</h1><p>🪙 +${25+mission.id} ${mission.id%5===0?' • 💎 +1':''}</p><button id="backIsland" class="primary">🏝️ Adventure Island</button> <button id="replay" class="secondary">↻ Play again</button></div>`;$('#modal').classList.remove('hidden');$('#backIsland').onclick=()=>{closeModal();goHub()};$('#replay').onclick=()=>{closeModal();startMission(mission)}}
function goHub(){scene='hub';mission=null;game=null;hud.mission.textContent='Adventure Island';showTouch('⚡','🏃');hint('');player.x=640;player.y=410}

function createGame(m){const f={scavenge:makeScavenge,maze:makeMaze,snake:makeSnake,builder:makeBuilder,hero:makeHero,race:makeRace,memory:makeMemory,platform:makePlatform,pattern:makePattern,logic:makeLogic,match:makeMatch,hidden:makeHidden,math:makeMath,science:makeScience,word:makeWord,boss:makeBoss}[m.type];return f(m)}
function base(m){return{m,done:false,elapsed:0,reset(){},update(){},draw(){worldBg(m.theme)},down(){},move(){},up(){},actionA(){},actionB(){}}}

function makeScavenge(m){const g=base(m);g.voice=`Find ${m.goal} hidden treasures!`;g.reset=function(){this.p={x:110,y:580};this.items=[];let tries=0;while(this.items.length<m.goal&&tries++<200){const o={x:rnd(90,1190),y:rnd(135,640),found:false};if(this.items.every(q=>dist(o,q)>95))this.items.push(o)}this.obstacles=Array.from({length:8},()=>({x:rnd(150,1130),y:rnd(170,610),r:rnd(32,60)}));showTouch('🔍','🏃')};g.update=function(dt){const c=controls(),sp=220;this.p.x=clamp(this.p.x+c.x*sp*dt,35,W-35);this.p.y=clamp(this.p.y+c.y*sp*dt,100,H-35);this.items.forEach(o=>{if(!o.found&&dist(this.p,o)<32){o.found=true;tone(780);burst(o.x,o.y,m.icon,7)}});if(this.items.every(o=>o.found))finishMission(3)};g.draw=function(){worldBg(m.theme);drawSceneDecor(m.theme);this.obstacles.forEach((o,i)=>{ctx.font=`${45+o.r/3}px serif`;ctx.fillText(i%2?'🌳':'🪨',o.x,o.y)});this.items.forEach(o=>{if(!o.found){ctx.globalAlpha=.85;ctx.font='36px serif';ctx.fillText(m.icon,o.x,o.y+Math.sin(time*5+o.x)*5);ctx.globalAlpha=1}});txt(`${m.icon} ${this.items.filter(o=>o.found).length}/${m.goal}`,W/2,105,27);drawMiniHero(this.p.x,this.p.y);drawParticles()};return g}

function makeMaze(m){const g=base(m);g.reset=function(){this.cols=14;this.rows=7;this.cell=70;this.ox=150;this.oy=130;this.p={x:0,y:0};this.goal={x:13,y:6};this.walls=new Set();const safe=new Set();let x=0,y=0;while(x<13||y<6){safe.add(`${x},${y}`);if((Math.random()<.65&&x<13)||y===6)x++;else y++}safe.add('13,6');for(let yy=0;yy<this.rows;yy++)for(let xx=0;xx<this.cols;xx++)if(!safe.has(`${xx},${yy}`)&&Math.random()<.3)this.walls.add(`${xx},${yy}`);showTouch('🔑','↗️')};g.update=function(dt){this.cool=(this.cool||0)-dt;const c=controls();if(this.cool<=0&&(Math.abs(c.x)>.45||Math.abs(c.y)>.45)){let dx=Math.abs(c.x)>Math.abs(c.y)?Math.sign(c.x):0,dy=dx?0:Math.sign(c.y),nx=this.p.x+dx,ny=this.p.y+dy;if(nx>=0&&ny>=0&&nx<this.cols&&ny<this.rows&&!this.walls.has(`${nx},${ny}`)){this.p={x:nx,y:ny};tone(430,.03);if(nx===13&&ny===6)finishMission(3)}else tone(150,.05);this.cool=.16}};g.draw=function(){worldBg(m.theme);rr(125,105,1030,535,28,'rgba(255,255,255,.18)');for(let y=0;y<this.rows;y++)for(let x=0;x<this.cols;x++)rr(this.ox+x*this.cell,this.oy+y*this.cell,this.cell-6,this.cell-6,10,this.walls.has(`${x},${y}`)?'#3f446b':'rgba(255,255,255,.72)');ctx.font='38px serif';ctx.fillText('🚪',this.ox+13*this.cell+32,this.oy+6*this.cell+36);drawMiniHero(this.ox+this.p.x*this.cell+32,this.oy+this.p.y*this.cell+37);drawParticles()};return g}

function makeSnake(m){const g=base(m);g.reset=function(){this.grid=24;this.cell=25;this.ox=340;this.oy=80;this.snake=[{x:8,y:12},{x:7,y:12},{x:6,y:12}];this.dir={x:1,y:0};this.next={...this.dir};this.food=this.spawn();this.score=0;this.acc=0;this.obstacles=Array.from({length:Math.min(12,Math.floor(m.id/4))},()=>({x:ri(2,21),y:ri(2,21)}));showTouch('⚡','↪️')};g.spawn=function(){let p;do p={x:ri(1,22),y:ri(1,22)};while(this.snake?.some(s=>s.x===p.x&&s.y===p.y));return p};g.update=function(dt){const c=controls();if(Math.abs(c.x)>.45||Math.abs(c.y)>.45){let nd=Math.abs(c.x)>Math.abs(c.y)?{x:Math.sign(c.x),y:0}:{x:0,y:Math.sign(c.y)};if(nd.x!==-this.dir.x||nd.y!==-this.dir.y)this.next=nd}this.acc+=dt;if(this.acc<.12)return;this.acc=0;this.dir=this.next;const h={x:this.snake[0].x+this.dir.x,y:this.snake[0].y+this.dir.y};if(h.x<0||h.y<0||h.x>=this.grid||h.y>=this.grid||this.snake.some(s=>s.x===h.x&&s.y===h.y)||this.obstacles.some(o=>o.x===h.x&&o.y===h.y)){tone(140,.15);this.reset();return}this.snake.unshift(h);if(h.x===this.food.x&&h.y===this.food.y){this.score++;state.coins++;tone(800,.05);this.food=this.spawn();if(this.score>=m.goal){save();finishMission(3);return}}else this.snake.pop()};g.draw=function(){worldBg(m.theme);rr(320,60,640,640,30,'rgba(20,30,60,.55)','#fff');this.obstacles.forEach(o=>{ctx.font='22px serif';ctx.fillText('🪨',this.ox+o.x*this.cell,this.oy+o.y*this.cell)});ctx.font='25px serif';ctx.fillText(m.icon,this.ox+this.food.x*this.cell,this.oy+this.food.y*this.cell);this.snake.forEach((s,i)=>{ctx.fillStyle=i?'#64df78':'#ffe34f';ctx.beginPath();ctx.arc(this.ox+s.x*this.cell,this.oy+s.y*this.cell,11,0,7);ctx.fill()});txt(`${m.icon} ${this.score}/${m.goal}`,W/2,35,25)};return g}

function makeBuilder(m){const g=base(m);g.reset=function(){this.cols=12;this.rows=7;this.cell=66;this.ox=245;this.oy=145;this.blocks=new Set();this.target=m.goal;this.variant=m.variant||'tower';showTouch('🧱','🧹');speak(m.variant==='bridge'?'Build a bridge across the river!':m.variant==='house'?'Build a little house!':'Build the shape!')};g.down=function(p){if(p.x<this.ox||p.y<this.oy)return;const x=Math.floor((p.x-this.ox)/this.cell),y=Math.floor((p.y-this.oy)/this.cell);if(x<0||y<0||x>=this.cols||y>=this.rows)return;const k=`${x},${y}`;if(this.erase)this.blocks.delete(k);else this.blocks.add(k);tone(this.erase?220:560,.04);this.check()};g.actionA=function(){this.erase=false;hud.a.textContent='🧱'};g.actionB=function(){this.erase=!this.erase;hud.b.textContent=this.erase?'🧹':'🖐️'};g.check=function(){let ok=false;if(this.variant==='bridge'){ok=[...Array(this.cols).keys()].every(x=>[...this.blocks].some(k=>k.startsWith(`${x},`)))}else if(this.variant==='tower'){const xs=[...this.blocks].map(k=>+k.split(',')[0]);ok=this.blocks.size>=this.target&&(Math.max(...xs)-Math.min(...xs)<=3)}else if(this.variant==='house'){const a=this.blocks;ok=a.size>=this.target&&[3,4,5,6,7,8].some(x=>a.has(`${x},5`)&&a.has(`${x},4`))}else ok=this.blocks.size>=this.target;if(ok)finishMission(3)};g.draw=function(){worldBg(m.theme);if(this.variant==='bridge'){ctx.fillStyle='#28afe0';ctx.fillRect(0,330,W,180);for(let x=0;x<W;x+=90){ctx.globalAlpha=.2;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x+(time*45)%90,390,24,0,Math.PI);ctx.fill()}ctx.globalAlpha=1}for(let y=0;y<this.rows;y++)for(let x=0;x<this.cols;x++){const k=`${x},${y}`;rr(this.ox+x*this.cell,this.oy+y*this.cell,this.cell-4,this.cell-4,10,this.blocks.has(k)?'#f0a33b':'rgba(255,255,255,.35)',this.blocks.has(k)?'#fff':'rgba(255,255,255,.45)')}txt(`🧱 ${this.blocks.size}/${this.target}+`,W/2,105,25)};return g}

function makeHero(m){const g=base(m);g.reset=function(){this.p={x:180,y:560};this.enemies=Array.from({length:m.goal},(_,i)=>({x:620+i*90,y:560,hp:2,alive:true,phase:rnd(0,6)}));this.shots=[];this.cool=0;this.hp=5;showTouch(m.power==='shield'?'🛡️':'⚡','⬆️')};g.update=function(dt){const c=controls();this.p.x=clamp(this.p.x+c.x*270*dt,70,1180);this.cool-=dt;this.enemies.forEach(e=>{if(!e.alive)return;e.phase+=dt;e.x+=Math.sin(e.phase)*22*dt;if(Math.random()<.006)this.shots.push({x:e.x,y:e.y-25,vx:-180})});this.shots.forEach(s=>s.x+=s.vx*dt);this.shots=this.shots.filter(s=>s.x>0);for(const s of this.shots)if(Math.abs(s.x-this.p.x)<25&&!s.hit){s.hit=true;if(!this.shield){this.hp--;tone(120,.08);burst(this.p.x,this.p.y,'💫',4);if(this.hp<=0)this.reset()}}this.shots=this.shots.filter(s=>!s.hit)};g.actionA=function(){if(this.cool>0)return;this.cool=.35;const e=this.enemies.filter(e=>e.alive).sort((a,b)=>Math.abs(a.x-this.p.x)-Math.abs(b.x-this.p.x))[0];if(e&&Math.abs(e.x-this.p.x)<260){e.hp--;burst(e.x,e.y,'✨',5);tone(720,.07);if(e.hp<=0){e.alive=false;burst(e.x,e.y,'⭐',10);if(this.enemies.every(e=>!e.alive))finishMission(3)}}};g.actionB=function(){this.shield=true;hud.b.textContent='🛡️';setTimeout(()=>{this.shield=false;hud.b.textContent='⬆️'},650)};g.draw=function(){worldBg(m.theme);drawSceneDecor(m.theme);ctx.fillStyle='rgba(20,30,70,.25)';ctx.fillRect(0,600,W,120);this.shots.forEach(s=>{ctx.font='25px serif';ctx.fillText('⚡',s.x,s.y)});this.enemies.forEach(e=>{if(!e.alive)return;drawRobot(e.x,e.y);ctx.fillStyle='#ff536f';ctx.fillRect(e.x-30,e.y-70,60*(e.hp/2),6)});drawMiniHero(this.p.x,this.p.y,this.shield);txt(`❤️ ${this.hp}`,90,110,24,'left');drawParticles()};return g}

function makeRace(m){const g=base(m);g.reset=function(){this.x=640;this.y=570;this.speed=240;this.progress=0;this.ob=[];this.spawn=0;showTouch('⚡','🏎️')};g.update=function(dt){const c=controls();this.x=clamp(this.x+c.x*330*dt,380,900);this.progress+=this.speed*dt;this.spawn-=dt;if(this.spawn<0){this.spawn=.65;this.ob.push({x:pick([440,560,680,800]),y:-40,type:Math.random()<.25?'star':'rock'})}this.ob.forEach(o=>o.y+=this.speed*dt);for(const o of this.ob)if(!o.hit&&Math.abs(o.x-this.x)<42&&Math.abs(o.y-this.y)<48){o.hit=true;if(o.type==='rock'){tone(120,.1);this.progress=Math.max(0,this.progress-120)}else{state.coins+=2;tone(820,.05);burst(o.x,o.y,'⭐',5)}}this.ob=this.ob.filter(o=>o.y<760&&!o.hit);if(this.progress>m.goal*850){save();finishMission(3)}};g.actionA=function(){this.speed=420;setTimeout(()=>this.speed=240,700);tone(700,.08)};g.draw=function(){worldBg(m.theme);ctx.fillStyle='#38435a';ctx.fillRect(350,0,580,H);ctx.strokeStyle='#fff';ctx.lineWidth=7;ctx.setLineDash([45,35]);for(const x of [495,640,785]){ctx.beginPath();ctx.moveTo(x,-(this.progress%80));ctx.lineTo(x,H);ctx.stroke()}ctx.setLineDash([]);this.ob.forEach(o=>{ctx.font='42px serif';ctx.fillText(o.type==='star'?'⭐':'🪨',o.x,o.y)});ctx.save();ctx.translate(this.x,this.y);rr(-35,-55,70,110,18,'#ff4f68','#fff');ctx.fillStyle='#1d2f5d';ctx.fillRect(-24,-35,48,35);ctx.restore();txt(`🏁 ${Math.min(100,Math.floor(this.progress/(m.goal*850)*100))}%`,W/2,100,27)};return g}

function makeMemory(m){const g=base(m);g.reset=function(){const n=clamp(m.goal,4,8),icons=shuffle(['🐶','🚀','🦄','🍉','🦖','⚽','🎸','🐠']).slice(0,n);this.cards=shuffle([...icons,...icons]).map((e,i)=>({e,i,open:false,done:false}));this.first=null;this.lock=false;showTouch('👆','🧠',false)};g.down=function(p){if(this.lock)return;const cols=4,w=160,h=120,ox=280,oy=130,gap=22;for(let i=0;i<this.cards.length;i++){const x=ox+(i%cols)*(w+gap),y=oy+Math.floor(i/cols)*(h+gap);if(p.x>=x&&p.x<x+w&&p.y>=y&&p.y<y+h){const c=this.cards[i];if(c.done||c.open)return;c.open=true;tone(520,.04);if(!this.first)this.first=c;else if(this.first.e===c.e){c.done=this.first.done=true;this.first=null;burst(x+w/2,y+h/2,'⭐',5);if(this.cards.every(c=>c.done))finishMission(3)}else{this.lock=true;setTimeout(()=>{c.open=false;this.first.open=false;this.first=null;this.lock=false},650)}return}}};g.draw=function(){worldBg(m.theme);const cols=4,w=160,h=120,ox=280,oy=130,gap=22;this.cards.forEach((c,i)=>{const x=ox+(i%cols)*(w+gap),y=oy+Math.floor(i/cols)*(h+gap);rr(x,y,w,h,22,c.open||c.done?'#fff':'#654fd0','#fff');txt(c.open||c.done?c.e:'★',x+w/2,y+h/2,48)});drawParticles()};return g}

function makePlatform(m){const g=base(m);g.reset=function(){this.p={x:80,y:500,vx:0,vy:0,on:false};this.platforms=[{x:0,y:620,w:1280,h:100},{x:170,y:520,w:180,h:24},{x:420,y:430,w:160,h:24},{x:670,y:350,w:170,h:24},{x:930,y:270,w:190,h:24}];this.coins=Array.from({length:m.goal},(_,i)=>({x:150+i*105,y:pick([470,380,300,220]),got:false}));showTouch('⚡','⬆️')};g.update=function(dt){const c=controls();this.p.vx=c.x*260;this.p.vy+=900*dt;this.p.x=clamp(this.p.x+this.p.vx*dt,20,W-20);const oldY=this.p.y;this.p.y+=this.p.vy*dt;this.p.on=false;for(const p of this.platforms)if(this.p.x>p.x-18&&this.p.x<p.x+p.w+18&&oldY+24<=p.y&&this.p.y+24>=p.y&&this.p.vy>=0){this.p.y=p.y-24;this.p.vy=0;this.p.on=true}if(this.p.y>H+80)this.reset();this.coins.forEach(c=>{if(!c.got&&Math.hypot(this.p.x-c.x,this.p.y-c.y)<35){c.got=true;tone(800,.04);state.coins++;burst(c.x,c.y,'✨',4);if(this.coins.every(c=>c.got)){save();finishMission(3)}}})};g.actionB=function(){if(this.p.on){this.p.vy=-500;tone(460,.05)}};g.actionA=function(){this.p.vx*=1.6};g.draw=function(){worldBg(m.theme);drawSceneDecor(m.theme);this.platforms.forEach(p=>rr(p.x,p.y,p.w,p.h,10,m.theme==='volcano'?'#362f44':'#6f5bc7','#fff'));this.coins.forEach(c=>{if(!c.got){ctx.font='28px serif';ctx.fillText('🪙',c.x,c.y+Math.sin(time*5+c.x)*4)}});drawMiniHero(this.p.x,this.p.y);txt(`🪙 ${this.coins.filter(c=>c.got).length}/${m.goal}`,W/2,100,25);drawParticles()};return g}

function makePattern(m){const g=base(m);g.reset=function(){this.round=0;this.colors=['#ff4f66','#4f7cff','#48d77e','#ffd84b'];this.seq=[ri(0,3),ri(0,3),ri(0,3)];this.input=[];this.flash=-1;this.lock=true;showTouch('👆','✨',false);this.playSeq()};g.playSeq=function(){this.lock=true;let i=0;const step=()=>{if(i>=this.seq.length){this.flash=-1;this.lock=false;return}this.flash=this.seq[i];tone([420,520,620,720][this.flash],.12);setTimeout(()=>{this.flash=-1;i++;setTimeout(step,130)},350)};step()};g.down=function(p){if(this.lock)return;const pts=[[440,260],[840,260],[440,510],[840,510]],i=pts.findIndex(q=>Math.hypot(p.x-q[0],p.y-q[1])<120);if(i<0)return;tone([420,520,620,720][i],.07);if(i===this.seq[this.input.length]){this.input.push(i);if(this.input.length===this.seq.length){this.round++;if(this.round>=m.goal){finishMission(3);return}this.seq.push(ri(0,3));this.input=[];setTimeout(()=>this.playSeq(),500)}}else{this.input=[];tone(140,.1);setTimeout(()=>this.playSeq(),350)}};g.draw=function(){worldBg(m.theme);[[440,260],[840,260],[440,510],[840,510]].forEach((p,i)=>{ctx.globalAlpha=this.flash===i?1:.7;rr(p[0]-115,p[1]-95,230,190,38,this.colors[i],'#fff');ctx.globalAlpha=1});txt(`✨ ${this.round}/${m.goal}`,W/2,100,28)};return g}

function makeLogic(m){const g=base(m);g.reset=function(){this.round=0;this.target=ri(1,4);this.options=shuffle([this.target,...shuffle([1,2,3,4,5,6].filter(x=>x!==this.target)).slice(0,3)]);showTouch('👆','🧠',false)};g.newRound=function(){this.target=ri(1,6);this.options=shuffle([this.target,...shuffle([1,2,3,4,5,6].filter(x=>x!==this.target)).slice(0,3)])};g.down=function(p){const pts=[350,520,690,860],i=pts.findIndex(x=>Math.abs(p.x-x)<70&&p.y>390&&p.y<540);if(i<0)return;if(this.options[i]===this.target){this.round++;tone(760,.05);burst(pts[i],460,'✨',5);if(this.round>=m.goal)finishMission(3);else this.newRound()}else tone(150,.08)};g.draw=function(){worldBg(m.theme);txt(m.theme==='robot'?'⚙️ → ?':'🔗 → ?',W/2,230,80);const pts=[350,520,690,860];pts.forEach((x,i)=>{rr(x-65,400,130,130,25,'#fff','#654fd0');txt(['🔺','🟦','⭐','💎','⚙️','🔗'][this.options[i]-1],x,465,48)});txt(`🧠 ${this.round}/${m.goal}`,W/2,100,25)};return g}

function makeMatch(m){const g=base(m);g.reset=function(){this.round=0;this.target=pick(['🔴','🔵','🟢','🟡','🔺','🟦']);this.opts=shuffle([this.target,...shuffle(['🔴','🔵','🟢','🟡','🔺','🟦'].filter(x=>x!==this.target)).slice(0,3)]);showTouch('👆','🍬',false)};g.down=function(p){const xs=[350,520,690,860],i=xs.findIndex(x=>Math.abs(p.x-x)<75&&p.y>410&&p.y<560);if(i<0)return;if(this.opts[i]===this.target){this.round++;tone(760,.05);if(this.round>=m.goal)finishMission(3);else this.resetRound()}else tone(140,.08)};g.resetRound=function(){this.target=pick(['🔴','🔵','🟢','🟡','🔺','🟦']);this.opts=shuffle([this.target,...shuffle(['🔴','🔵','🟢','🟡','🔺','🟦'].filter(x=>x!==this.target)).slice(0,3)])};g.draw=function(){worldBg(m.theme);txt(this.target,W/2,260,100);const xs=[350,520,690,860];xs.forEach((x,i)=>{rr(x-70,410,140,140,25,'#fff','#fff');txt(this.opts[i],x,480,65)});txt(`${this.round}/${m.goal}`,W/2,100,24)};return g}

function makeHidden(m){const g=base(m);g.reset=function(){this.items=[];let tries=0;while(this.items.length<m.goal&&tries++<300){const o={x:rnd(80,1200),y:rnd(135,650),got:false};if(this.items.every(q=>dist(o,q)>70))this.items.push(o)}showTouch('👆','🔎',false)};g.down=function(p){const o=this.items.find(o=>!o.got&&Math.hypot(o.x-p.x,o.y-p.y)<38);if(o){o.got=true;tone(800,.05);burst(o.x,o.y,'✨',5);if(this.items.every(o=>o.got))finishMission(3)}};g.draw=function(){worldBg(m.theme);drawSceneDecor(m.theme);for(let i=0;i<32;i++){ctx.globalAlpha=.9;ctx.font=`${26+(i%4)*4}px serif`;ctx.fillText(['🌳','🪨','🌸','🍄','🌿','🐚'][i%6],50+(i*137)%1180,130+(i*83)%520)}ctx.globalAlpha=1;this.items.forEach(o=>{if(!o.got){ctx.globalAlpha=.7;ctx.font='28px serif';ctx.fillText(m.icon,o.x,o.y);ctx.globalAlpha=1}});txt(`${m.icon} ${this.items.filter(o=>o.got).length}/${m.goal}`,W/2,100,25);drawParticles()};return g}

function makeMath(m){const g=base(m);g.reset=function(){this.round=0;this.newQ();showTouch('👆','➕',false)};g.newQ=function(){const a=ri(1,8),b=ri(1,8);this.op=Math.random()<.55?'+':'−';this.a=this.op==='−'?Math.max(a,b):a;this.b=this.op==='−'?Math.min(a,b):b;this.ans=this.op==='+'?this.a+this.b:this.a-this.b;this.opts=shuffle([this.ans,...shuffle([this.ans+1,this.ans+2,Math.max(0,this.ans-1),Math.max(0,this.ans-2)]).filter((v,i,a)=>a.indexOf(v)===i&&v!==this.ans).slice(0,3)])};g.down=function(p){const xs=[350,520,690,860],i=xs.findIndex(x=>Math.abs(p.x-x)<70&&p.y>420&&p.y<550);if(i<0)return;if(this.opts[i]===this.ans){this.round++;tone(800,.05);if(this.round>=m.goal)finishMission(3);else this.newQ()}else tone(130,.08)};g.draw=function(){worldBg(m.theme);txt(`${this.a} ${this.op} ${this.b} = ?`,W/2,260,72);const xs=[350,520,690,860];xs.forEach((x,i)=>{rr(x-65,420,130,120,24,'#fff','#fff');txt(String(this.opts[i]),x,480,45,'center','#27345f')});txt(`⭐ ${this.round}/${m.goal}`,W/2,100,25)};return g}

function makeScience(m){const g=base(m);g.reset=function(){this.round=0;this.qs=m.theme==='dino'?[['🦴','🦖'],['🥚','🦕'],['🌿','🦕'],['🦷','🦖']]:[['🐟','🌊'],['🐦','🌳'],['🐝','🌸'],['🐻','🌲'],['🐸','💧'],['🐑','🌾']];this.newQ();showTouch('👆','🔬',false)};g.newQ=function(){this.q=pick(this.qs);const pool=['🌊','🌳','🌸','🌲','💧','🌾','🦖','🦕'];this.opts=shuffle([this.q[1],...shuffle(pool.filter(x=>x!==this.q[1])).slice(0,3)])};g.down=function(p){const xs=[350,520,690,860],i=xs.findIndex(x=>Math.abs(p.x-x)<70&&p.y>410&&p.y<550);if(i<0)return;if(this.opts[i]===this.q[1]){this.round++;tone(780,.05);if(this.round>=m.goal)finishMission(3);else this.newQ()}else tone(140,.08)};g.draw=function(){worldBg(m.theme);txt(this.q[0],W/2,250,105);const xs=[350,520,690,860];xs.forEach((x,i)=>{rr(x-65,410,130,130,25,'#fff','#fff');txt(this.opts[i],x,475,55)});txt(`🔬 ${this.round}/${m.goal}`,W/2,100,25)};return g}

function makeWord(m){const g=base(m);g.reset=function(){this.round=0;this.words=[['CAT','🐱'],['DOG','🐶'],['SUN','☀️'],['FISH','🐟'],['TREE','🌳'],['MOON','🌙'],['BALL','⚽']];this.newQ();showTouch('👆','🔤',false)};g.newQ=function(){this.q=pick(this.words);const letters=shuffle([...new Set((this.q[0]+'ABCDEFGHLMNOPRSTU').split(''))]);this.opts=letters.slice(0,8);for(const ch of this.q[0])if(!this.opts.includes(ch))this.opts[ri(0,this.opts.length-1)]=ch;this.input=''};g.down=function(p){const cols=4,w=120,gap=18,ox=350,oy=410;for(let i=0;i<this.opts.length;i++){const x=ox+(i%cols)*(w+gap),y=oy+Math.floor(i/cols)*90;if(p.x>x&&p.x<x+w&&p.y>y&&p.y<y+70){this.input+=this.opts[i];tone(520,.04);if(this.q[0].startsWith(this.input)){if(this.input===this.q[0]){this.round++;if(this.round>=m.goal)finishMission(3);else this.newQ()}}else{this.input='';tone(130,.08)}return}}};g.draw=function(){worldBg(m.theme);txt(this.q[1],W/2,220,100);txt(this.input.padEnd(this.q[0].length,'_').split('').join('  '),W/2,330,48);const cols=4,w=120,gap=18,ox=350,oy=410;this.opts.forEach((ch,i)=>{const x=ox+(i%cols)*(w+gap),y=oy+Math.floor(i/cols)*90;rr(x,y,w,70,18,'#fff','#fff');txt(ch,x+w/2,y+35,35,'center','#293260')});txt(`🔤 ${this.round}/${m.goal}`,W/2,100,25)};return g}

function makeBoss(m){const g=base(m);g.reset=function(){this.hp=m.goal;this.p={x:180,y:570};this.boss={x:990,y:500};this.seq=[ri(0,3),ri(0,3),ri(0,3)];this.answer=null;this.shield=true;this.timer=0;showTouch('⚡','🛡️')};g.update=function(dt){const c=controls();this.p.x=clamp(this.p.x+c.x*260*dt,80,800);this.timer+=dt;if(this.timer>4){this.timer=0;this.shield=true;this.seq=[ri(0,3),ri(0,3),ri(0,3)];this.answer=null}};g.actionA=function(){if(this.shield){this.answer=ri(0,3);if(this.answer===this.seq[2]){this.shield=false;tone(760,.07);toast('Shield down! ⚡')}else tone(140,.08);return}this.hp--;tone(220,.07);burst(this.boss.x,this.boss.y,'✨',8);this.shield=true;if(this.hp<=0)finishMission(3)};g.actionB=function(){tone(450,.06);this.timer=0};g.draw=function(){worldBg(m.theme);drawSceneDecor(m.theme);drawMiniHero(this.p.x,this.p.y,true);drawRobot(this.boss.x,this.boss.y,1.7);if(this.shield){ctx.strokeStyle='#5ce2ff';ctx.lineWidth=12;ctx.beginPath();ctx.arc(this.boss.x,this.boss.y-20,105,0,7);ctx.stroke();txt(this.seq.map(i=>['🔴','🔵','🟢','🟡'][i]).join(' '),W/2,190,45)}ctx.fillStyle='#ff5470';ctx.fillRect(810,120,340*(this.hp/m.goal),20);txt('BOSS',980,95,23);drawParticles()};return g}

function drawSceneDecor(theme){ctx.globalAlpha=.9;const sets={forest:['🌳','🌲','🌼','🦋'],castle:['🏰','🌳','🛡️','🌷'],space:['🪐','⭐','☄️','🌙'],dino:['🌴','🪨','🌿','🦕'],robot:['🏭','⚙️','🔋','🤖'],ocean:['🪸','🐠','🐚','🌊'],island:['🌴','🪨','🦜','🌊'],cave:['🪨','💎','🕯️','🦇'],lab:['⚗️','🔬','⚙️','🧪'],volcano:['🪨','🔥','🌋','💨'],academy:['🏙️','⭐','🛡️','⚡'],candy:['🍭','🍬','🍪','🧁']};const a=sets[theme]||sets.forest;for(let i=0;i<12;i++){ctx.font=`${38+(i%3)*8}px serif`;ctx.fillText(a[i%a.length],70+(i*113)%1160,160+(i*83)%470)}ctx.globalAlpha=1}
function drawMiniHero(x,y,shield=false){ctx.save();ctx.translate(x,y);ctx.fillStyle='#2d3563';ctx.beginPath();ctx.ellipse(0,23,20,7,0,0,7);ctx.fill();rr(-16,-2,32,37,12,'#3c72ea');ctx.fillStyle='#efb07a';ctx.beginPath();ctx.arc(0,-17,15,0,7);ctx.fill();ctx.fillStyle='#342938';ctx.beginPath();ctx.arc(0,-23,15,Math.PI,Math.PI*2);ctx.fill();if(shield){ctx.strokeStyle='#62e6ff';ctx.lineWidth=6;ctx.beginPath();ctx.arc(0,0,34,0,7);ctx.stroke()}ctx.restore()}
function drawRobot(x,y,s=1){ctx.save();ctx.translate(x,y);ctx.scale(s,s);rr(-32,-42,64,72,14,'#75829c','#fff');ctx.fillStyle='#2d345a';ctx.beginPath();ctx.arc(-12,-18,6,0,7);ctx.arc(12,-18,6,0,7);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,-42);ctx.lineTo(0,-60);ctx.stroke();ctx.beginPath();ctx.arc(0,-64,5,0,7);ctx.stroke();ctx.restore()}

canvas.onpointerdown=e=>{if(scene!=='mission'||!game)return;const p=canvasPos(e);game.down?.(p);canvas.setPointerCapture?.(e.pointerId)};canvas.onpointermove=e=>{if(scene==='mission'&&game&&e.buttons)game.move?.(canvasPos(e))};canvas.onpointerup=e=>{if(scene==='mission'&&game)game.up?.(canvasPos(e))};function canvasPos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}

$('#homeBtn').onclick=()=>goHub();$('#audioBtn').onclick=()=>{state.settings.music=!state.settings.music;state.settings.sfx=state.settings.music;$('#audioBtn').textContent=state.settings.music?'🔊':'🔇';if(state.settings.music)startMusic();else stopMusic();save()};$('#parentBtn').onclick=()=>openGate();$('#modalClose').onclick=closeModal;function closeModal(){$('#modal').classList.add('hidden')}
function openGate(){$('#parentGate').classList.remove('hidden');gateDown={l:false,r:false};gateStart=0;$('#gateProgress').style.width='0'}$('#gateBack').onclick=()=>$('#parentGate').classList.add('hidden');let gateDown={l:false,r:false},gateStart=0,gateRAF=0;function gatePress(side,on){gateDown[side]=on;$('#gate'+(side==='l'?'L':'R')).classList.toggle('down',on);if(gateDown.l&&gateDown.r&&!gateStart){gateStart=performance.now();tickGate()}if(!gateDown.l||!gateDown.r){gateStart=0;$('#gateProgress').style.width='0';cancelAnimationFrame(gateRAF)}}function tickGate(){if(!gateStart)return;const p=Math.min(1,(performance.now()-gateStart)/3000);$('#gateProgress').style.width=p*100+'%';if(p>=1){$('#parentGate').classList.add('hidden');openParent();gateStart=0;return}gateRAF=requestAnimationFrame(tickGate)}for(const [id,s] of [['gateL','l'],['gateR','r']]){const b=$('#'+id);b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);gatePress(s,true)};b.onpointerup=()=>gatePress(s,false);b.onpointercancel=()=>gatePress(s,false)}
function openParent(){const completed=Object.keys(state.completed).length;$('#modalBody').innerHTML=`<h1>Parent Dashboard</h1><div class="parent-grid"><div class="stat"><b>${Math.floor(state.playSeconds/60)}</b>minutes played</div><div class="stat"><b>${completed}/50</b>missions</div><div class="stat"><b>${state.stars}</b>stars</div></div><h3>Skills practised</h3><div class="parent-grid">${Object.entries(state.skills).map(([k,v])=>`<div class="stat"><b>${v}</b>${k}</div>`).join('')}</div><h3>Safety</h3><p>No chat, no strangers, no advertising, no purchases and no personal information is required. Progress is stored only on this device.</p><button id="resetProgress" class="secondary">Reset progress</button>`;$('#modal').classList.remove('hidden');$('#resetProgress').onclick=()=>{if(confirm('Reset all BrainQuest progress on this device?')){localStorage.removeItem('brainquestAdventureV10');location.reload()}}}

function loop(now){let dt=Math.min(.033,(now-last)/1000);last=now;time+=dt;if(scene==='hub'){updateHub(dt);drawHub()}else if(game){game.elapsed+=dt;game.update(dt);game.draw()}requestAnimationFrame(loop)}
setInterval(()=>{state.playSeconds++;if(state.playSeconds%15===0)save()},1000);syncHud();showTouch('⚡','🏃');startMusic();requestAnimationFrame(loop);
